// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopStartupService exposes local API startup state to the loading screen.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Quit exits the desktop application from the startup failure screen.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(4016114987);
}

/**
 * Snapshot returns a consistent point-in-time startup status.
 */
export function Snapshot(): $CancellablePromise<$models.DesktopStartupSnapshot> {
    return $Call.ByID(411152216);
}
