// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopLogService exposes the desktop-only log viewer surface to generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListDays(): $CancellablePromise<$models.DesktopLogDay[] | null> {
    return $Call.ByID(3050303072);
}

export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(3240492663);
}

export function ReadPage(day: string, level: string, query: string, offset: number, limit: number): $CancellablePromise<$models.DesktopLogPage> {
    return $Call.ByID(4222000680, day, level, query, offset, limit);
}
