// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopLinkService from "./desktoplinkservice.js";
import * as DesktopLogService from "./desktoplogservice.js";
import * as DesktopStartupService from "./desktopstartupservice.js";
import * as DesktopUpdateService from "./desktopupdateservice.js";
export {
    DesktopLinkService,
    DesktopLogService,
    DesktopStartupService,
    DesktopUpdateService
};

export type {
    DesktopLogDay,
    DesktopLogLine,
    DesktopLogPage,
    DesktopStartupSnapshot,
    DesktopUpdateResult
} from "./models.js";
