// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DesktopLogDay {
    "day": string;
}

export interface DesktopLogLine {
    "level": string;
    "text": string;
}

export interface DesktopLogPage {
    "day": string;
    "logDir": string;
    "items": DesktopLogLine[] | null;
    "offset": number;
    "limit": number;
    "total": number;
    "nextOffset"?: number | null;
}

export interface DesktopUpdateResult {
    "currentVersion": string;
    "available": boolean;
    "latestVersion"?: string;
    "releaseUrl"?: string;
    "publishedAt"?: string;
    "notes"?: string;
}
