// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/pineworker.proto

package pineworkerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PineWorker_HealthCheck_FullMethodName   = "/jftrade.strategy.pineworker.v1.PineWorker/HealthCheck"
	PineWorker_AnalyzeScript_FullMethodName = "/jftrade.strategy.pineworker.v1.PineWorker/AnalyzeScript"
	PineWorker_RunScript_FullMethodName     = "/jftrade.strategy.pineworker.v1.PineWorker/RunScript"
)

// PineWorkerClient is the client API for PineWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PineWorkerClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	AnalyzeScript(ctx context.Context, in *AnalyzeScriptRequest, opts ...grpc.CallOption) (*AnalyzeScriptResponse, error)
	RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error)
}

type pineWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewPineWorkerClient(cc grpc.ClientConnInterface) PineWorkerClient {
	return &pineWorkerClient{cc}
}

func (c *pineWorkerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PineWorker_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineWorkerClient) AnalyzeScript(ctx context.Context, in *AnalyzeScriptRequest, opts ...grpc.CallOption) (*AnalyzeScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeScriptResponse)
	err := c.cc.Invoke(ctx, PineWorker_AnalyzeScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineWorkerClient) RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScriptResponse)
	err := c.cc.Invoke(ctx, PineWorker_RunScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PineWorkerServer is the server API for PineWorker service.
// All implementations must embed UnimplementedPineWorkerServer
// for forward compatibility.
type PineWorkerServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	AnalyzeScript(context.Context, *AnalyzeScriptRequest) (*AnalyzeScriptResponse, error)
	RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error)
	mustEmbedUnimplementedPineWorkerServer()
}

// UnimplementedPineWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPineWorkerServer struct{}

func (UnimplementedPineWorkerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPineWorkerServer) AnalyzeScript(context.Context, *AnalyzeScriptRequest) (*AnalyzeScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeScript not implemented")
}
func (UnimplementedPineWorkerServer) RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScript not implemented")
}
func (UnimplementedPineWorkerServer) mustEmbedUnimplementedPineWorkerServer() {}
func (UnimplementedPineWorkerServer) testEmbeddedByValue()                    {}

// UnsafePineWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PineWorkerServer will
// result in compilation errors.
type UnsafePineWorkerServer interface {
	mustEmbedUnimplementedPineWorkerServer()
}

func RegisterPineWorkerServer(s grpc.ServiceRegistrar, srv PineWorkerServer) {
	// If the following call panics, it indicates UnimplementedPineWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PineWorker_ServiceDesc, srv)
}

func _PineWorker_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineWorkerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PineWorker_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineWorkerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PineWorker_AnalyzeScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineWorkerServer).AnalyzeScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PineWorker_AnalyzeScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineWorkerServer).AnalyzeScript(ctx, req.(*AnalyzeScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PineWorker_RunScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineWorkerServer).RunScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PineWorker_RunScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineWorkerServer).RunScript(ctx, req.(*RunScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PineWorker_ServiceDesc is the grpc.ServiceDesc for PineWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PineWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jftrade.strategy.pineworker.v1.PineWorker",
	HandlerType: (*PineWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PineWorker_HealthCheck_Handler,
		},
		{
			MethodName: "AnalyzeScript",
			Handler:    _PineWorker_AnalyzeScript_Handler,
		},
		{
			MethodName: "RunScript",
			Handler:    _PineWorker_RunScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pineworker.proto",
}
