// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/pineworker.proto

package pineworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_pineworker_proto protoreflect.FileDescriptor

const file_proto_pineworker_proto_rawDesc = "" +
	"\n" +
	"\x16proto/pineworker.proto\x12\x1ejftrade.strategy.pineworker.v1\x1a\x1cproto/pineworker_types.proto2\xf4\x02\n" +
	"\n" +
	"PineWorker\x12v\n" +
	"\vHealthCheck\x122.jftrade.strategy.pineworker.v1.HealthCheckRequest\x1a3.jftrade.strategy.pineworker.v1.HealthCheckResponse\x12|\n" +
	"\rAnalyzeScript\x124.jftrade.strategy.pineworker.v1.AnalyzeScriptRequest\x1a5.jftrade.strategy.pineworker.v1.AnalyzeScriptResponse\x12p\n" +
	"\tRunScript\x120.jftrade.strategy.pineworker.v1.RunScriptRequest\x1a1.jftrade.strategy.pineworker.v1.RunScriptResponseBSZQgithub.com/jftrade/jftrade-main/pkg/strategy/pineworker/pineworkerpb;pineworkerpbb\x06proto3"

var file_proto_pineworker_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),    // 0: jftrade.strategy.pineworker.v1.HealthCheckRequest
	(*AnalyzeScriptRequest)(nil),  // 1: jftrade.strategy.pineworker.v1.AnalyzeScriptRequest
	(*RunScriptRequest)(nil),      // 2: jftrade.strategy.pineworker.v1.RunScriptRequest
	(*HealthCheckResponse)(nil),   // 3: jftrade.strategy.pineworker.v1.HealthCheckResponse
	(*AnalyzeScriptResponse)(nil), // 4: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse
	(*RunScriptResponse)(nil),     // 5: jftrade.strategy.pineworker.v1.RunScriptResponse
}
var file_proto_pineworker_proto_depIdxs = []int32{
	0, // 0: jftrade.strategy.pineworker.v1.PineWorker.HealthCheck:input_type -> jftrade.strategy.pineworker.v1.HealthCheckRequest
	1, // 1: jftrade.strategy.pineworker.v1.PineWorker.AnalyzeScript:input_type -> jftrade.strategy.pineworker.v1.AnalyzeScriptRequest
	2, // 2: jftrade.strategy.pineworker.v1.PineWorker.RunScript:input_type -> jftrade.strategy.pineworker.v1.RunScriptRequest
	3, // 3: jftrade.strategy.pineworker.v1.PineWorker.HealthCheck:output_type -> jftrade.strategy.pineworker.v1.HealthCheckResponse
	4, // 4: jftrade.strategy.pineworker.v1.PineWorker.AnalyzeScript:output_type -> jftrade.strategy.pineworker.v1.AnalyzeScriptResponse
	5, // 5: jftrade.strategy.pineworker.v1.PineWorker.RunScript:output_type -> jftrade.strategy.pineworker.v1.RunScriptResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pineworker_proto_init() }
func file_proto_pineworker_proto_init() {
	if File_proto_pineworker_proto != nil {
		return
	}
	file_proto_pineworker_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pineworker_proto_rawDesc), len(file_proto_pineworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pineworker_proto_goTypes,
		DependencyIndexes: file_proto_pineworker_proto_depIdxs,
	}.Build()
	File_proto_pineworker_proto = out.File
	file_proto_pineworker_proto_goTypes = nil
	file_proto_pineworker_proto_depIdxs = nil
}
