// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/pineworker_types.proto

package pineworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_pineworker_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	PinetsVersion string                 `protobuf:"bytes,4,opt,name=pinets_version,json=pinetsVersion,proto3" json:"pinets_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_pineworker_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthCheckResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetPinetsVersion() string {
	if x != nil {
		return x.PinetsVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type AnalyzeScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ScriptId      string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeScriptRequest) Reset() {
	*x = AnalyzeScriptRequest{}
	mi := &file_proto_pineworker_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeScriptRequest) ProtoMessage() {}

func (x *AnalyzeScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeScriptRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeScriptRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalyzeScriptRequest) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *AnalyzeScriptRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnalyzeScriptRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AnalyzeScriptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Ok             bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Diagnostics    []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Inputs         []string               `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Plots          []string               `protobuf:"bytes,5,rep,name=plots,proto3" json:"plots,omitempty"`
	StrategyConfig map[string]string      `protobuf:"bytes,6,rep,name=strategy_config,json=strategyConfig,proto3" json:"strategy_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata       *WorkerMetadata        `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeScriptResponse) Reset() {
	*x = AnalyzeScriptResponse{}
	mi := &file_proto_pineworker_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeScriptResponse) ProtoMessage() {}

func (x *AnalyzeScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeScriptResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeScriptResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalyzeScriptResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AnalyzeScriptResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *AnalyzeScriptResponse) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *AnalyzeScriptResponse) GetPlots() []string {
	if x != nil {
		return x.Plots
	}
	return nil
}

func (x *AnalyzeScriptResponse) GetStrategyConfig() map[string]string {
	if x != nil {
		return x.StrategyConfig
	}
	return nil
}

func (x *AnalyzeScriptResponse) GetMetadata() *WorkerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeScriptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunScriptRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	JobId        string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ScriptId     string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Source       string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Symbol       string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe    string                 `protobuf:"bytes,5,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Mode         string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Candles      *CandleBatch           `protobuf:"bytes,7,opt,name=candles,proto3" json:"candles,omitempty"`
	Params       map[string]string      `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IncludePlots bool                   `protobuf:"varint,9,opt,name=include_plots,json=includePlots,proto3" json:"include_plots,omitempty"`
	// Live sessions retain PineTS state inside one worker. open carries the
	// complete warmup history, append carries only newly closed candles, and
	// close releases the state. Empty means a traditional stateless run.
	SessionId        string `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionOperation string `protobuf:"bytes,11,opt,name=session_operation,json=sessionOperation,proto3" json:"session_operation,omitempty"`
	ExpectedRevision uint64 `protobuf:"varint,12,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunScriptRequest) Reset() {
	*x = RunScriptRequest{}
	mi := &file_proto_pineworker_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptRequest) ProtoMessage() {}

func (x *RunScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptRequest.ProtoReflect.Descriptor instead.
func (*RunScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{4}
}

func (x *RunScriptRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunScriptRequest) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *RunScriptRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RunScriptRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RunScriptRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *RunScriptRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RunScriptRequest) GetCandles() *CandleBatch {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *RunScriptRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RunScriptRequest) GetIncludePlots() bool {
	if x != nil {
		return x.IncludePlots
	}
	return false
}

func (x *RunScriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunScriptRequest) GetSessionOperation() string {
	if x != nil {
		return x.SessionOperation
	}
	return ""
}

func (x *RunScriptRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type RunScriptResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Plots           []*PlotOutput          `protobuf:"bytes,2,rep,name=plots,proto3" json:"plots,omitempty"`
	OrderIntents    []*OrderIntent         `protobuf:"bytes,3,rep,name=order_intents,json=orderIntents,proto3" json:"order_intents,omitempty"`
	Logs            []string               `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	Warnings        []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Diagnostics     []*Diagnostic          `protobuf:"bytes,6,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Metadata        *WorkerMetadata        `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Alerts          []*AlertEvent          `protobuf:"bytes,9,rep,name=alerts,proto3" json:"alerts,omitempty"`
	VisualOutputs   []*VisualOutput        `protobuf:"bytes,10,rep,name=visual_outputs,json=visualOutputs,proto3" json:"visual_outputs,omitempty"`
	StrategyMetrics *StrategyMetrics       `protobuf:"bytes,11,opt,name=strategy_metrics,json=strategyMetrics,proto3" json:"strategy_metrics,omitempty"`
	SessionId       string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionRevision uint64                 `protobuf:"varint,13,opt,name=session_revision,json=sessionRevision,proto3" json:"session_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunScriptResponse) Reset() {
	*x = RunScriptResponse{}
	mi := &file_proto_pineworker_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptResponse) ProtoMessage() {}

func (x *RunScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptResponse.ProtoReflect.Descriptor instead.
func (*RunScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_types_proto_rawDescGZIP(), []int{5}
}

func (x *RunScriptResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunScriptResponse) GetPlots() []*PlotOutput {
	if x != nil {
		return x.Plots
	}
	return nil
}

func (x *RunScriptResponse) GetOrderIntents() []*OrderIntent {
	if x != nil {
		return x.OrderIntents
	}
	return nil
}

func (x *RunScriptResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *RunScriptResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *RunScriptResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *RunScriptResponse) GetMetadata() *WorkerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunScriptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunScriptResponse) GetAlerts() []*AlertEvent {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *RunScriptResponse) GetVisualOutputs() []*VisualOutput {
	if x != nil {
		return x.VisualOutputs
	}
	return nil
}

func (x *RunScriptResponse) GetStrategyMetrics() *StrategyMetrics {
	if x != nil {
		return x.StrategyMetrics
	}
	return nil
}

func (x *RunScriptResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunScriptResponse) GetSessionRevision() uint64 {
	if x != nil {
		return x.SessionRevision
	}
	return 0
}

var File_proto_pineworker_types_proto protoreflect.FileDescriptor

const file_proto_pineworker_types_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/pineworker_types.proto\x12\x1ejftrade.strategy.pineworker.v1\x1a\x1dproto/pineworker_common.proto\"\x14\n" +
	"\x12HealthCheckRequest\"\xa7\x01\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0epinets_version\x18\x04 \x01(\tR\rpinetsVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xf7\x01\n" +
	"\x14AnalyzeScriptRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12X\n" +
	"\x06params\x18\x04 \x03(\v2@.jftrade.strategy.pineworker.v1.AnalyzeScriptRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x03\n" +
	"\x15AnalyzeScriptResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12L\n" +
	"\vdiagnostics\x18\x03 \x03(\v2*.jftrade.strategy.pineworker.v1.DiagnosticR\vdiagnostics\x12\x16\n" +
	"\x06inputs\x18\x04 \x03(\tR\x06inputs\x12\x14\n" +
	"\x05plots\x18\x05 \x03(\tR\x05plots\x12r\n" +
	"\x0fstrategy_config\x18\x06 \x03(\v2I.jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.StrategyConfigEntryR\x0estrategyConfig\x12J\n" +
	"\bmetadata\x18\a \x01(\v2..jftrade.strategy.pineworker.v1.WorkerMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x1aA\n" +
	"\x13StrategyConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x04\n" +
	"\x10RunScriptRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x05 \x01(\tR\ttimeframe\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12E\n" +
	"\acandles\x18\a \x01(\v2+.jftrade.strategy.pineworker.v1.CandleBatchR\acandles\x12T\n" +
	"\x06params\x18\b \x03(\v2<.jftrade.strategy.pineworker.v1.RunScriptRequest.ParamsEntryR\x06params\x12#\n" +
	"\rinclude_plots\x18\t \x01(\bR\fincludePlots\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x12+\n" +
	"\x11session_operation\x18\v \x01(\tR\x10sessionOperation\x12+\n" +
	"\x11expected_revision\x18\f \x01(\x04R\x10expectedRevision\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x05\n" +
	"\x11RunScriptResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12@\n" +
	"\x05plots\x18\x02 \x03(\v2*.jftrade.strategy.pineworker.v1.PlotOutputR\x05plots\x12P\n" +
	"\rorder_intents\x18\x03 \x03(\v2+.jftrade.strategy.pineworker.v1.OrderIntentR\forderIntents\x12\x12\n" +
	"\x04logs\x18\x04 \x03(\tR\x04logs\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12L\n" +
	"\vdiagnostics\x18\x06 \x03(\v2*.jftrade.strategy.pineworker.v1.DiagnosticR\vdiagnostics\x12J\n" +
	"\bmetadata\x18\a \x01(\v2..jftrade.strategy.pineworker.v1.WorkerMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12B\n" +
	"\x06alerts\x18\t \x03(\v2*.jftrade.strategy.pineworker.v1.AlertEventR\x06alerts\x12S\n" +
	"\x0evisual_outputs\x18\n" +
	" \x03(\v2,.jftrade.strategy.pineworker.v1.VisualOutputR\rvisualOutputs\x12Z\n" +
	"\x10strategy_metrics\x18\v \x01(\v2/.jftrade.strategy.pineworker.v1.StrategyMetricsR\x0fstrategyMetrics\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12)\n" +
	"\x10session_revision\x18\r \x01(\x04R\x0fsessionRevisionBSZQgithub.com/jftrade/jftrade-main/pkg/strategy/pineworker/pineworkerpb;pineworkerpbb\x06proto3"

var (
	file_proto_pineworker_types_proto_rawDescOnce sync.Once
	file_proto_pineworker_types_proto_rawDescData []byte
)

func file_proto_pineworker_types_proto_rawDescGZIP() []byte {
	file_proto_pineworker_types_proto_rawDescOnce.Do(func() {
		file_proto_pineworker_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pineworker_types_proto_rawDesc), len(file_proto_pineworker_types_proto_rawDesc)))
	})
	return file_proto_pineworker_types_proto_rawDescData
}

var file_proto_pineworker_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_pineworker_types_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),    // 0: jftrade.strategy.pineworker.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 1: jftrade.strategy.pineworker.v1.HealthCheckResponse
	(*AnalyzeScriptRequest)(nil),  // 2: jftrade.strategy.pineworker.v1.AnalyzeScriptRequest
	(*AnalyzeScriptResponse)(nil), // 3: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse
	(*RunScriptRequest)(nil),      // 4: jftrade.strategy.pineworker.v1.RunScriptRequest
	(*RunScriptResponse)(nil),     // 5: jftrade.strategy.pineworker.v1.RunScriptResponse
	nil,                           // 6: jftrade.strategy.pineworker.v1.AnalyzeScriptRequest.ParamsEntry
	nil,                           // 7: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.StrategyConfigEntry
	nil,                           // 8: jftrade.strategy.pineworker.v1.RunScriptRequest.ParamsEntry
	(*Diagnostic)(nil),            // 9: jftrade.strategy.pineworker.v1.Diagnostic
	(*WorkerMetadata)(nil),        // 10: jftrade.strategy.pineworker.v1.WorkerMetadata
	(*CandleBatch)(nil),           // 11: jftrade.strategy.pineworker.v1.CandleBatch
	(*PlotOutput)(nil),            // 12: jftrade.strategy.pineworker.v1.PlotOutput
	(*OrderIntent)(nil),           // 13: jftrade.strategy.pineworker.v1.OrderIntent
	(*AlertEvent)(nil),            // 14: jftrade.strategy.pineworker.v1.AlertEvent
	(*VisualOutput)(nil),          // 15: jftrade.strategy.pineworker.v1.VisualOutput
	(*StrategyMetrics)(nil),       // 16: jftrade.strategy.pineworker.v1.StrategyMetrics
}
var file_proto_pineworker_types_proto_depIdxs = []int32{
	6,  // 0: jftrade.strategy.pineworker.v1.AnalyzeScriptRequest.params:type_name -> jftrade.strategy.pineworker.v1.AnalyzeScriptRequest.ParamsEntry
	9,  // 1: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.diagnostics:type_name -> jftrade.strategy.pineworker.v1.Diagnostic
	7,  // 2: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.strategy_config:type_name -> jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.StrategyConfigEntry
	10, // 3: jftrade.strategy.pineworker.v1.AnalyzeScriptResponse.metadata:type_name -> jftrade.strategy.pineworker.v1.WorkerMetadata
	11, // 4: jftrade.strategy.pineworker.v1.RunScriptRequest.candles:type_name -> jftrade.strategy.pineworker.v1.CandleBatch
	8,  // 5: jftrade.strategy.pineworker.v1.RunScriptRequest.params:type_name -> jftrade.strategy.pineworker.v1.RunScriptRequest.ParamsEntry
	12, // 6: jftrade.strategy.pineworker.v1.RunScriptResponse.plots:type_name -> jftrade.strategy.pineworker.v1.PlotOutput
	13, // 7: jftrade.strategy.pineworker.v1.RunScriptResponse.order_intents:type_name -> jftrade.strategy.pineworker.v1.OrderIntent
	9,  // 8: jftrade.strategy.pineworker.v1.RunScriptResponse.diagnostics:type_name -> jftrade.strategy.pineworker.v1.Diagnostic
	10, // 9: jftrade.strategy.pineworker.v1.RunScriptResponse.metadata:type_name -> jftrade.strategy.pineworker.v1.WorkerMetadata
	14, // 10: jftrade.strategy.pineworker.v1.RunScriptResponse.alerts:type_name -> jftrade.strategy.pineworker.v1.AlertEvent
	15, // 11: jftrade.strategy.pineworker.v1.RunScriptResponse.visual_outputs:type_name -> jftrade.strategy.pineworker.v1.VisualOutput
	16, // 12: jftrade.strategy.pineworker.v1.RunScriptResponse.strategy_metrics:type_name -> jftrade.strategy.pineworker.v1.StrategyMetrics
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_pineworker_types_proto_init() }
func file_proto_pineworker_types_proto_init() {
	if File_proto_pineworker_types_proto != nil {
		return
	}
	file_proto_pineworker_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pineworker_types_proto_rawDesc), len(file_proto_pineworker_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pineworker_types_proto_goTypes,
		DependencyIndexes: file_proto_pineworker_types_proto_depIdxs,
		MessageInfos:      file_proto_pineworker_types_proto_msgTypes,
	}.Build()
	File_proto_pineworker_types_proto = out.File
	file_proto_pineworker_types_proto_goTypes = nil
	file_proto_pineworker_types_proto_depIdxs = nil
}
