// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/pineworker_common.proto

package pineworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CandleBatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EncodingVersion uint32                 `protobuf:"varint,1,opt,name=encoding_version,json=encodingVersion,proto3" json:"encoding_version,omitempty"`
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CandleBatch) Reset() {
	*x = CandleBatch{}
	mi := &file_proto_pineworker_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandleBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleBatch) ProtoMessage() {}

func (x *CandleBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleBatch.ProtoReflect.Descriptor instead.
func (*CandleBatch) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{0}
}

func (x *CandleBatch) GetEncodingVersion() uint32 {
	if x != nil {
		return x.EncodingVersion
	}
	return 0
}

func (x *CandleBatch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_proto_pineworker_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{1}
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Diagnostic) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type PlotOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotOutput) Reset() {
	*x = PlotOutput{}
	mi := &file_proto_pineworker_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotOutput) ProtoMessage() {}

func (x *PlotOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotOutput.ProtoReflect.Descriptor instead.
func (*PlotOutput) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{2}
}

func (x *PlotOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlotOutput) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type AlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Frequency     string                 `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	BarIndex      int32                  `protobuf:"varint,6,opt,name=bar_index,json=barIndex,proto3" json:"bar_index,omitempty"`
	Time          int64                  `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_proto_pineworker_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{3}
}

func (x *AlertEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertEvent) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *AlertEvent) GetBarIndex() int32 {
	if x != nil {
		return x.BarIndex
	}
	return 0
}

func (x *AlertEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type VisualOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualOutput) Reset() {
	*x = VisualOutput{}
	mi := &file_proto_pineworker_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualOutput) ProtoMessage() {}

func (x *VisualOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualOutput.ProtoReflect.Descriptor instead.
func (*VisualOutput) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{4}
}

func (x *VisualOutput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VisualOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VisualOutput) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type StrategyMetrics struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	BuyAndHoldPnl             float64                `protobuf:"fixed64,1,opt,name=buy_and_hold_pnl,json=buyAndHoldPnl,proto3" json:"buy_and_hold_pnl,omitempty"`
	BuyAndHoldPerGain         float64                `protobuf:"fixed64,2,opt,name=buy_and_hold_per_gain,json=buyAndHoldPerGain,proto3" json:"buy_and_hold_per_gain,omitempty"`
	StrategyOutperformance    float64                `protobuf:"fixed64,3,opt,name=strategy_outperformance,json=strategyOutperformance,proto3" json:"strategy_outperformance,omitempty"`
	HasBuyAndHoldPnl          bool                   `protobuf:"varint,4,opt,name=has_buy_and_hold_pnl,json=hasBuyAndHoldPnl,proto3" json:"has_buy_and_hold_pnl,omitempty"`
	HasBuyAndHoldPerGain      bool                   `protobuf:"varint,5,opt,name=has_buy_and_hold_per_gain,json=hasBuyAndHoldPerGain,proto3" json:"has_buy_and_hold_per_gain,omitempty"`
	HasStrategyOutperformance bool                   `protobuf:"varint,6,opt,name=has_strategy_outperformance,json=hasStrategyOutperformance,proto3" json:"has_strategy_outperformance,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StrategyMetrics) Reset() {
	*x = StrategyMetrics{}
	mi := &file_proto_pineworker_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyMetrics) ProtoMessage() {}

func (x *StrategyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyMetrics.ProtoReflect.Descriptor instead.
func (*StrategyMetrics) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{5}
}

func (x *StrategyMetrics) GetBuyAndHoldPnl() float64 {
	if x != nil {
		return x.BuyAndHoldPnl
	}
	return 0
}

func (x *StrategyMetrics) GetBuyAndHoldPerGain() float64 {
	if x != nil {
		return x.BuyAndHoldPerGain
	}
	return 0
}

func (x *StrategyMetrics) GetStrategyOutperformance() float64 {
	if x != nil {
		return x.StrategyOutperformance
	}
	return 0
}

func (x *StrategyMetrics) GetHasBuyAndHoldPnl() bool {
	if x != nil {
		return x.HasBuyAndHoldPnl
	}
	return false
}

func (x *StrategyMetrics) GetHasBuyAndHoldPerGain() bool {
	if x != nil {
		return x.HasBuyAndHoldPerGain
	}
	return false
}

func (x *StrategyMetrics) GetHasStrategyOutperformance() bool {
	if x != nil {
		return x.HasStrategyOutperformance
	}
	return false
}

type OrderIntent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FromEntry      string                 `protobuf:"bytes,3,opt,name=from_entry,json=fromEntry,proto3" json:"from_entry,omitempty"`
	Direction      string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity       float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuantityPct    float64                `protobuf:"fixed64,6,opt,name=quantity_pct,json=quantityPct,proto3" json:"quantity_pct,omitempty"`
	LimitPrice     float64                `protobuf:"fixed64,7,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	StopPrice      float64                `protobuf:"fixed64,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	Comment        string                 `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	AlertMessage   string                 `protobuf:"bytes,10,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message,omitempty"`
	DisableAlert   bool                   `protobuf:"varint,11,opt,name=disable_alert,json=disableAlert,proto3" json:"disable_alert,omitempty"`
	BarIndex       int32                  `protobuf:"varint,12,opt,name=bar_index,json=barIndex,proto3" json:"bar_index,omitempty"`
	Time           int64                  `protobuf:"varint,13,opt,name=time,proto3" json:"time,omitempty"`
	HasQuantity    bool                   `protobuf:"varint,14,opt,name=has_quantity,json=hasQuantity,proto3" json:"has_quantity,omitempty"`
	HasQuantityPct bool                   `protobuf:"varint,15,opt,name=has_quantity_pct,json=hasQuantityPct,proto3" json:"has_quantity_pct,omitempty"`
	HasLimitPrice  bool                   `protobuf:"varint,16,opt,name=has_limit_price,json=hasLimitPrice,proto3" json:"has_limit_price,omitempty"`
	HasStopPrice   bool                   `protobuf:"varint,17,opt,name=has_stop_price,json=hasStopPrice,proto3" json:"has_stop_price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderIntent) Reset() {
	*x = OrderIntent{}
	mi := &file_proto_pineworker_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIntent) ProtoMessage() {}

func (x *OrderIntent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIntent.ProtoReflect.Descriptor instead.
func (*OrderIntent) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{6}
}

func (x *OrderIntent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OrderIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderIntent) GetFromEntry() string {
	if x != nil {
		return x.FromEntry
	}
	return ""
}

func (x *OrderIntent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OrderIntent) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderIntent) GetQuantityPct() float64 {
	if x != nil {
		return x.QuantityPct
	}
	return 0
}

func (x *OrderIntent) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *OrderIntent) GetStopPrice() float64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *OrderIntent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OrderIntent) GetAlertMessage() string {
	if x != nil {
		return x.AlertMessage
	}
	return ""
}

func (x *OrderIntent) GetDisableAlert() bool {
	if x != nil {
		return x.DisableAlert
	}
	return false
}

func (x *OrderIntent) GetBarIndex() int32 {
	if x != nil {
		return x.BarIndex
	}
	return 0
}

func (x *OrderIntent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *OrderIntent) GetHasQuantity() bool {
	if x != nil {
		return x.HasQuantity
	}
	return false
}

func (x *OrderIntent) GetHasQuantityPct() bool {
	if x != nil {
		return x.HasQuantityPct
	}
	return false
}

func (x *OrderIntent) GetHasLimitPrice() bool {
	if x != nil {
		return x.HasLimitPrice
	}
	return false
}

func (x *OrderIntent) GetHasStopPrice() bool {
	if x != nil {
		return x.HasStopPrice
	}
	return false
}

type WorkerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PinetsVersion string                 `protobuf:"bytes,3,opt,name=pinets_version,json=pinetsVersion,proto3" json:"pinets_version,omitempty"`
	ScriptHash    string                 `protobuf:"bytes,4,opt,name=script_hash,json=scriptHash,proto3" json:"script_hash,omitempty"`
	DataHash      string                 `protobuf:"bytes,5,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RequestBytes  int32                  `protobuf:"varint,7,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes int32                  `protobuf:"varint,8,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	PeakRssBytes  int64                  `protobuf:"varint,9,opt,name=peak_rss_bytes,json=peakRssBytes,proto3" json:"peak_rss_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetadata) Reset() {
	*x = WorkerMetadata{}
	mi := &file_proto_pineworker_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetadata) ProtoMessage() {}

func (x *WorkerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pineworker_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetadata.ProtoReflect.Descriptor instead.
func (*WorkerMetadata) Descriptor() ([]byte, []int) {
	return file_proto_pineworker_common_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerMetadata) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkerMetadata) GetPinetsVersion() string {
	if x != nil {
		return x.PinetsVersion
	}
	return ""
}

func (x *WorkerMetadata) GetScriptHash() string {
	if x != nil {
		return x.ScriptHash
	}
	return ""
}

func (x *WorkerMetadata) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *WorkerMetadata) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *WorkerMetadata) GetRequestBytes() int32 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *WorkerMetadata) GetResponseBytes() int32 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

func (x *WorkerMetadata) GetPeakRssBytes() int64 {
	if x != nil {
		return x.PeakRssBytes
	}
	return 0
}

var File_proto_pineworker_common_proto protoreflect.FileDescriptor

const file_proto_pineworker_common_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/pineworker_common.proto\x12\x1ejftrade.strategy.pineworker.v1\"R\n" +
	"\vCandleBatch\x12)\n" +
	"\x10encoding_version\x18\x01 \x01(\rR\x0fencodingVersion\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x82\x01\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\"8\n" +
	"\n" +
	"PlotOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\"\xaf\x01\n" +
	"\n" +
	"AlertEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\tR\tfrequency\x12\x1b\n" +
	"\tbar_index\x18\x06 \x01(\x05R\bbarIndex\x12\x12\n" +
	"\x04time\x18\a \x01(\x03R\x04time\"Y\n" +
	"\fVisualOutput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"\xce\x02\n" +
	"\x0fStrategyMetrics\x12'\n" +
	"\x10buy_and_hold_pnl\x18\x01 \x01(\x01R\rbuyAndHoldPnl\x120\n" +
	"\x15buy_and_hold_per_gain\x18\x02 \x01(\x01R\x11buyAndHoldPerGain\x127\n" +
	"\x17strategy_outperformance\x18\x03 \x01(\x01R\x16strategyOutperformance\x12.\n" +
	"\x14has_buy_and_hold_pnl\x18\x04 \x01(\bR\x10hasBuyAndHoldPnl\x127\n" +
	"\x19has_buy_and_hold_per_gain\x18\x05 \x01(\bR\x14hasBuyAndHoldPerGain\x12>\n" +
	"\x1bhas_strategy_outperformance\x18\x06 \x01(\bR\x19hasStrategyOutperformance\"\x9d\x04\n" +
	"\vOrderIntent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"from_entry\x18\x03 \x01(\tR\tfromEntry\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12!\n" +
	"\fquantity_pct\x18\x06 \x01(\x01R\vquantityPct\x12\x1f\n" +
	"\vlimit_price\x18\a \x01(\x01R\n" +
	"limitPrice\x12\x1d\n" +
	"\n" +
	"stop_price\x18\b \x01(\x01R\tstopPrice\x12\x18\n" +
	"\acomment\x18\t \x01(\tR\acomment\x12#\n" +
	"\ralert_message\x18\n" +
	" \x01(\tR\falertMessage\x12#\n" +
	"\rdisable_alert\x18\v \x01(\bR\fdisableAlert\x12\x1b\n" +
	"\tbar_index\x18\f \x01(\x05R\bbarIndex\x12\x12\n" +
	"\x04time\x18\r \x01(\x03R\x04time\x12!\n" +
	"\fhas_quantity\x18\x0e \x01(\bR\vhasQuantity\x12(\n" +
	"\x10has_quantity_pct\x18\x0f \x01(\bR\x0ehasQuantityPct\x12&\n" +
	"\x0fhas_limit_price\x18\x10 \x01(\bR\rhasLimitPrice\x12$\n" +
	"\x0ehas_stop_price\x18\x11 \x01(\bR\fhasStopPrice\"\xbf\x02\n" +
	"\x0eWorkerMetadata\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0epinets_version\x18\x03 \x01(\tR\rpinetsVersion\x12\x1f\n" +
	"\vscript_hash\x18\x04 \x01(\tR\n" +
	"scriptHash\x12\x1b\n" +
	"\tdata_hash\x18\x05 \x01(\tR\bdataHash\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rrequest_bytes\x18\a \x01(\x05R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\b \x01(\x05R\rresponseBytes\x12$\n" +
	"\x0epeak_rss_bytes\x18\t \x01(\x03R\fpeakRssBytesBSZQgithub.com/jftrade/jftrade-main/pkg/strategy/pineworker/pineworkerpb;pineworkerpbb\x06proto3"

var (
	file_proto_pineworker_common_proto_rawDescOnce sync.Once
	file_proto_pineworker_common_proto_rawDescData []byte
)

func file_proto_pineworker_common_proto_rawDescGZIP() []byte {
	file_proto_pineworker_common_proto_rawDescOnce.Do(func() {
		file_proto_pineworker_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pineworker_common_proto_rawDesc), len(file_proto_pineworker_common_proto_rawDesc)))
	})
	return file_proto_pineworker_common_proto_rawDescData
}

var file_proto_pineworker_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_pineworker_common_proto_goTypes = []any{
	(*CandleBatch)(nil),     // 0: jftrade.strategy.pineworker.v1.CandleBatch
	(*Diagnostic)(nil),      // 1: jftrade.strategy.pineworker.v1.Diagnostic
	(*PlotOutput)(nil),      // 2: jftrade.strategy.pineworker.v1.PlotOutput
	(*AlertEvent)(nil),      // 3: jftrade.strategy.pineworker.v1.AlertEvent
	(*VisualOutput)(nil),    // 4: jftrade.strategy.pineworker.v1.VisualOutput
	(*StrategyMetrics)(nil), // 5: jftrade.strategy.pineworker.v1.StrategyMetrics
	(*OrderIntent)(nil),     // 6: jftrade.strategy.pineworker.v1.OrderIntent
	(*WorkerMetadata)(nil),  // 7: jftrade.strategy.pineworker.v1.WorkerMetadata
}
var file_proto_pineworker_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pineworker_common_proto_init() }
func file_proto_pineworker_common_proto_init() {
	if File_proto_pineworker_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pineworker_common_proto_rawDesc), len(file_proto_pineworker_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pineworker_common_proto_goTypes,
		DependencyIndexes: file_proto_pineworker_common_proto_depIdxs,
		MessageInfos:      file_proto_pineworker_common_proto_msgTypes,
	}.Build()
	File_proto_pineworker_common_proto = out.File
	file_proto_pineworker_common_proto_goTypes = nil
	file_proto_pineworker_common_proto_depIdxs = nil
}
