import { fa } from "vuetify/iconsets/fa";

// 图标映射：需要根据 Vuetify 的默认图标集进行映射，确保所有组件都能正确显示图标
// https://vuetifyjs.com/en/features/icon-fonts/

const aliases = {
  collapse: "fa-solid fa-chevron-up",
  complete: "fa-solid fa-check",
  cancel: "fa-solid fa-circle-xmark",
  close: "fa-solid fa-xmark",
  delete: "fa-solid fa-circle-xmark",
  clear: "fa-solid fa-circle-xmark",
  success: "fa-solid fa-circle-check",
  info: "fa-solid fa-circle-info",
  warning: "fa-solid fa-triangle-exclamation",
  error: "fa-solid fa-circle-xmark",
  prev: "fa-solid fa-chevron-left",
  next: "fa-solid fa-chevron-right",
  checkboxOn: "fa-solid fa-square-check",
  checkboxOff: "fa-regular fa-square",
  checkboxIndeterminate: "fa-solid fa-square-minus",
  delimiter: "fa-solid fa-circle",
  sortAsc: "fa-solid fa-arrow-up",
  sortDesc: "fa-solid fa-arrow-down",
  expand: "fa-solid fa-chevron-down",
  menu: "fa-solid fa-bars",
  subgroup: "fa-solid fa-caret-down",
  dropdown: "fa-solid fa-caret-down",
  radioOn: "fa-regular fa-circle-dot",
  radioOff: "fa-regular fa-circle",
  edit: "fa-solid fa-pencil",
  ratingEmpty: "fa-regular fa-star",
  ratingFull: "fa-solid fa-star",
  ratingHalf: "fa-solid fa-star-half-stroke",
  loading: "fa-solid fa-arrows-rotate",
  first: "fa-solid fa-angles-left",
  last: "fa-solid fa-angles-right",
  unfold: "fa-solid fa-up-down",
  file: "fa-solid fa-paperclip",
  plus: "fa-solid fa-plus",
  minus: "fa-solid fa-minus",
  calendar: "fa-regular fa-calendar",
  treeviewCollapse: "fa-solid fa-caret-down",
  treeviewExpand: "fa-solid fa-caret-right",
  tableGroupExpand: "fa-solid fa-chevron-right",
  tableGroupCollapse: "fa-solid fa-chevron-down",
  eyeDropper: "fa-solid fa-eye-dropper",
  upload: "fa-solid fa-cloud-arrow-up",
  color: "fa-solid fa-palette",
  command: "fa-solid fa-keyboard",
  ctrl: "fa-solid fa-keyboard",
  space: "fa-solid fa-square",
  shift: "fa-solid fa-up-long",
  alt: "fa-solid fa-keyboard",
  enter: "fa-solid fa-reply",
  arrowup: "fa-solid fa-arrow-up",
  arrowdown: "fa-solid fa-arrow-down",
  arrowleft: "fa-solid fa-arrow-left",
  arrowright: "fa-solid fa-arrow-right",
  backspace: "fa-solid fa-delete-left",
  play: "fa-solid fa-play",
  pause: "fa-solid fa-pause",
  fullscreen: "fa-solid fa-maximize",
  fullscreenExit: "fa-solid fa-minimize",
  volumeHigh: "fa-solid fa-volume-high",
  volumeMedium: "fa-solid fa-volume-low",
  volumeLow: "fa-solid fa-volume-off",
  volumeOff: "fa-solid fa-volume-xmark",
  search: "fa-solid fa-magnifying-glass",
};

export const fontAwesomeIcons = {
  defaultSet: "fa",
  aliases,
  sets: { fa },
};
