#[derive(Clone, Copy)]
pub(crate) struct ProductionToolDefinition {
    pub(crate) id: &'static str,
    pub(crate) category: &'static str,
    pub(crate) display_name: &'static str,
    pub(crate) adapter: ProductionRouteAdapter,
    /// Optional operation-level readiness key.  This is used for research
    /// tools whose public HTTP routes share the `ResearchRead` umbrella.
    pub(crate) research_operation: Option<&'static str>,
}

pub(crate) const PRODUCTION_TOOL_DEFINITIONS: &[ProductionToolDefinition] = &[
    ProductionToolDefinition {
        id: "interaction.request_user",
        category: "interaction",
        display_name: "向用户提问",
        adapter: ProductionRouteAdapter::AdkChat,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "workflow.wait",
        category: "workflow",
        display_name: "等待工作流",
        adapter: ProductionRouteAdapter::AdkChat,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "tools.search",
        category: "system",
        display_name: "搜索工具",
        adapter: ProductionRouteAdapter::AdkChat,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "models.list",
        category: "system",
        display_name: "查询可调用模型",
        adapter: ProductionRouteAdapter::AdkRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "system.status",
        category: "system",
        display_name: "查询系统状态",
        adapter: ProductionRouteAdapter::SystemCore,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "system.futu_opend",
        category: "system",
        display_name: "查询 OpenD 状态",
        adapter: ProductionRouteAdapter::SystemRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "plugins.catalog",
        category: "plugins",
        display_name: "查询插件目录",
        adapter: ProductionRouteAdapter::PluginsRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.capabilities",
        category: "market",
        display_name: "查询行情能力",
        adapter: ProductionRouteAdapter::MarketDataProviderRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.search",
        category: "market",
        display_name: "搜索标的",
        adapter: ProductionRouteAdapter::MarketDataSearchRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.snapshot",
        category: "market",
        display_name: "查询行情快照",
        adapter: ProductionRouteAdapter::MarketDataSnapshotsRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.snapshots",
        category: "market",
        display_name: "批量查询行情快照",
        adapter: ProductionRouteAdapter::MarketDataBatchSnapshotsWrite,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.candles",
        category: "market",
        display_name: "查询 K 线",
        adapter: ProductionRouteAdapter::MarketDataCandlesRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.intraday",
        category: "market",
        display_name: "查询分时行情",
        adapter: ProductionRouteAdapter::MarketDataIntradayRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.subscriptions",
        category: "market",
        display_name: "查询行情订阅",
        adapter: ProductionRouteAdapter::MarketDataSubscriptionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "watchlist.list",
        category: "watchlist",
        display_name: "查询自选列表",
        adapter: ProductionRouteAdapter::WatchlistRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "research.instrument",
        category: "research",
        display_name: "查询标的信息",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("instrument"),
    },
    ProductionToolDefinition {
        id: "research.financials",
        category: "research",
        display_name: "查询财务数据",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("financials"),
    },
    ProductionToolDefinition {
        id: "research.valuation",
        category: "research",
        display_name: "查询估值数据",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("valuation"),
    },
    ProductionToolDefinition {
        id: "research.news",
        category: "research",
        display_name: "查询研究新闻",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("news"),
    },
    ProductionToolDefinition {
        id: "research.screen",
        category: "research",
        display_name: "执行研究筛选",
        adapter: ProductionRouteAdapter::ResearchScreenWrite,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "account.orders",
        category: "account",
        display_name: "查询订单",
        adapter: ProductionRouteAdapter::ExecutionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "risk.state",
        category: "risk",
        display_name: "查询风控状态",
        adapter: ProductionRouteAdapter::SystemCore,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.definitions",
        category: "strategy",
        display_name: "查询策略定义",
        adapter: ProductionRouteAdapter::StrategyDefinitionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.validate_pine",
        category: "strategy",
        display_name: "校验 Pine 策略",
        adapter: ProductionRouteAdapter::StrategyPine,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.research_backtest",
        category: "strategy",
        display_name: "执行策略回测",
        adapter: ProductionRouteAdapter::BacktestStart,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "backtest.runs",
        category: "backtest",
        display_name: "查询回测运行",
        adapter: ProductionRouteAdapter::BacktestRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "backtest.result_view",
        category: "backtest",
        display_name: "查询回测结果",
        adapter: ProductionRouteAdapter::BacktestRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "backtest.kline_sync_status",
        category: "backtest",
        display_name: "查询 K 线同步状态",
        adapter: ProductionRouteAdapter::BacktestSyncRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "portfolio.accounts",
        category: "portfolio",
        display_name: "账户发现",
        adapter: ProductionRouteAdapter::PortfolioRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "portfolio.overview",
        category: "portfolio",
        display_name: "组合概览",
        adapter: ProductionRouteAdapter::PortfolioRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "portfolio.positions",
        category: "portfolio",
        display_name: "组合持仓",
        adapter: ProductionRouteAdapter::PortfolioRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "portfolio.summary",
        category: "portfolio",
        display_name: "查询组合摘要",
        adapter: ProductionRouteAdapter::PortfolioRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.providers",
        category: "market",
        display_name: "查询行情源列表",
        adapter: ProductionRouteAdapter::MarketDataProviderRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.instrument_profile",
        category: "market",
        display_name: "查询标的档案",
        adapter: ProductionRouteAdapter::MarketDataProfileRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.ticks",
        category: "market",
        display_name: "查询逐笔成交",
        adapter: ProductionRouteAdapter::MarketDataTicksRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.depth",
        category: "market",
        display_name: "查询深度摆盘",
        adapter: ProductionRouteAdapter::MarketDataDepthRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.broker_queue",
        category: "market",
        display_name: "查询经纪席位队列",
        adapter: ProductionRouteAdapter::MarketDataBrokerQueueRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "market.capital_flow",
        category: "market",
        display_name: "查询资金流向",
        adapter: ProductionRouteAdapter::MarketDataCapitalFlowRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "broker.cash_flows",
        category: "broker",
        display_name: "查询资金流水",
        adapter: ProductionRouteAdapter::BrokerRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "broker.fees",
        category: "broker",
        display_name: "查询佣金费用",
        adapter: ProductionRouteAdapter::BrokerRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "broker.margin_ratios",
        category: "broker",
        display_name: "查询保证金比率",
        adapter: ProductionRouteAdapter::BrokerRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "broker.orders",
        category: "broker",
        display_name: "查询券商委托",
        adapter: ProductionRouteAdapter::BrokerRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "broker.fills",
        category: "broker",
        display_name: "查询成交明细",
        adapter: ProductionRouteAdapter::BrokerRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "execution.order_events",
        category: "execution",
        display_name: "查询订单事件",
        adapter: ProductionRouteAdapter::ExecutionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "execution.buying_power",
        category: "execution",
        display_name: "查询购买力",
        adapter: ProductionRouteAdapter::ExecutionWrite,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "watchlist.remote.list",
        category: "watchlist",
        display_name: "查询远端自选列表",
        adapter: ProductionRouteAdapter::RemoteWatchlistRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.definition_versions.list",
        category: "strategy",
        display_name: "查询策略版本列表",
        adapter: ProductionRouteAdapter::StrategyDefinitionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.definition_versions.get",
        category: "strategy",
        display_name: "查询策略版本详情",
        adapter: ProductionRouteAdapter::StrategyDefinitionRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.instance_activity",
        category: "strategy",
        display_name: "查询策略实例活动",
        adapter: ProductionRouteAdapter::StrategyRuntimeRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "strategy.pine_spec",
        category: "strategy",
        display_name: "查询 Pine 规范",
        adapter: ProductionRouteAdapter::StrategyPine,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "risk.events",
        category: "risk",
        display_name: "查询风控事件",
        adapter: ProductionRouteAdapter::SystemRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "system.runtime_dependencies",
        category: "system",
        display_name: "查询系统运行时依赖",
        adapter: ProductionRouteAdapter::SystemRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "alerts.price.list",
        category: "alerts",
        display_name: "查询价格预警列表",
        adapter: ProductionRouteAdapter::AlertsRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "alerts.option_event.list",
        category: "alerts",
        display_name: "查询期权事件预警列表",
        adapter: ProductionRouteAdapter::AlertsRead,
        research_operation: None,
    },
    ProductionToolDefinition {
        id: "research.institutions",
        category: "research",
        display_name: "查询机构持仓研究",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("institutions"),
    },
    ProductionToolDefinition {
        id: "research.analyst",
        category: "research",
        display_name: "查询分析师评级",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("analyst"),
    },
    ProductionToolDefinition {
        id: "research.ownership",
        category: "research",
        display_name: "查询股权结构",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("ownership"),
    },
    ProductionToolDefinition {
        id: "research.corporate_actions",
        category: "research",
        display_name: "查询公司行动",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("corporate_actions"),
    },
    ProductionToolDefinition {
        id: "research.short_interest",
        category: "research",
        display_name: "查询做空数据",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("short_interest"),
    },
    ProductionToolDefinition {
        id: "research.technical_indicators",
        category: "research",
        display_name: "查询技术指标",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("technical_indicators"),
    },
    ProductionToolDefinition {
        id: "research.rankings",
        category: "research",
        display_name: "查询市场排行",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("rankings"),
    },
    ProductionToolDefinition {
        id: "research.industry",
        category: "research",
        display_name: "查询行业板块",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("industry"),
    },
    ProductionToolDefinition {
        id: "research.calendar",
        category: "research",
        display_name: "查询财经日历",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("calendar"),
    },
    ProductionToolDefinition {
        id: "research.macro",
        category: "research",
        display_name: "查询宏观经济数据",
        adapter: ProductionRouteAdapter::ResearchRead,
        research_operation: Some("macro"),
    },
    ProductionToolDefinition {
        id: "research.screen_catalog",
        category: "research",
        display_name: "查询研究选股条件目录",
        adapter: ProductionRouteAdapter::ResearchCatalog,
        research_operation: None,
    },
];
