#[allow(dead_code)]
impl AdkMutationOperation {
    pub const fn name(self) -> &'static str {
        match self {
            Self::DeleteAgent => "delete-agent",
            Self::DeleteMemory => "delete-memory",
            Self::DeleteProvider => "delete-provider",
            Self::DeleteSession => "delete-session",
            Self::DeleteSkill => "delete-skill",
            Self::DeleteTask => "delete-task",
            Self::DeleteWorkflow => "delete-workflow",
            Self::DeleteWorkflowTrigger => "delete-workflow-trigger",
            Self::UpdateRunObjective => "update-run-objective",
            Self::UpdateSessionComposerState => "update-session-composer-state",
            Self::CreateAgent => "create-agent",
            Self::Approve => "approve",
            Self::Deny => "deny",
            Self::CreateMemory => "create-memory",
            Self::CancelOptimizationTask => "cancel-optimization-task",
            Self::CreateProvider => "create-provider",
            Self::SetDefaultProvider => "set-default-provider",
            Self::TestProvider => "test-provider",
            Self::CancelRun => "cancel-run",
            Self::RespondToInput => "respond-to-input",
            Self::PauseRun => "pause-run",
            Self::ResumeRun => "resume-run",
            Self::CreateSession => "create-session",
            Self::CompactSessionContext => "compact-session-context",
            Self::InstallSkill => "install-skill",
            Self::CreateTask => "create-task",
            Self::RunWorkflowTrigger => "run-workflow-trigger",
            Self::RunWorkflowWebhook => "run-workflow-webhook",
            Self::CreateWorkflow => "create-workflow",
            Self::RunWorkflow => "run-workflow",
            Self::CreateWorkflowTrigger => "create-workflow-trigger",
            Self::UpdateAgent => "update-agent",
            Self::UpdateProvider => "update-provider",
            Self::RenameSession => "rename-session",
            Self::UpdateTask => "update-task",
            Self::UpdateWorkflow => "update-workflow",
            Self::UpdateWorkflowTrigger => "update-workflow-trigger",
        }
    }
}
