// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Notify.proto

package notify

import (
	common "github.com/jftrade/jftrade-main/pkg/futu/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GtwEventType int32

const (
	GtwEventType_GtwEventType_None                GtwEventType = 0  //正常无错
	GtwEventType_GtwEventType_LocalCfgLoadFailed  GtwEventType = 1  //加载本地配置失败
	GtwEventType_GtwEventType_APISvrRunFailed     GtwEventType = 2  //服务器启动失败
	GtwEventType_GtwEventType_ForceUpdate         GtwEventType = 3  //客户端版本过低
	GtwEventType_GtwEventType_LoginFailed         GtwEventType = 4  //登录失败
	GtwEventType_GtwEventType_UnAgreeDisclaimer   GtwEventType = 5  //未同意免责声明
	GtwEventType_GtwEventType_NetCfgMissing       GtwEventType = 6  //缺少必要网络配置信息
	GtwEventType_GtwEventType_KickedOut           GtwEventType = 7  //牛牛帐号在别处登录
	GtwEventType_GtwEventType_LoginPwdChanged     GtwEventType = 8  //登录密码被修改
	GtwEventType_GtwEventType_BanLogin            GtwEventType = 9  //用户被禁止登录
	GtwEventType_GtwEventType_NeedPicVerifyCode   GtwEventType = 10 //需要图形验证码
	GtwEventType_GtwEventType_NeedPhoneVerifyCode GtwEventType = 11 //需要手机验证码
	GtwEventType_GtwEventType_AppDataNotExist     GtwEventType = 12 //程序自带数据不存在
	GtwEventType_GtwEventType_NessaryDataMissing  GtwEventType = 13 //缺少必要数据
	GtwEventType_GtwEventType_TradePwdChanged     GtwEventType = 14 //交易密码被修改
	GtwEventType_GtwEventType_EnableDeviceLock    GtwEventType = 15 //启用设备锁
)

// Enum value maps for GtwEventType.
var (
	GtwEventType_name = map[int32]string{
		0:  "GtwEventType_None",
		1:  "GtwEventType_LocalCfgLoadFailed",
		2:  "GtwEventType_APISvrRunFailed",
		3:  "GtwEventType_ForceUpdate",
		4:  "GtwEventType_LoginFailed",
		5:  "GtwEventType_UnAgreeDisclaimer",
		6:  "GtwEventType_NetCfgMissing",
		7:  "GtwEventType_KickedOut",
		8:  "GtwEventType_LoginPwdChanged",
		9:  "GtwEventType_BanLogin",
		10: "GtwEventType_NeedPicVerifyCode",
		11: "GtwEventType_NeedPhoneVerifyCode",
		12: "GtwEventType_AppDataNotExist",
		13: "GtwEventType_NessaryDataMissing",
		14: "GtwEventType_TradePwdChanged",
		15: "GtwEventType_EnableDeviceLock",
	}
	GtwEventType_value = map[string]int32{
		"GtwEventType_None":                0,
		"GtwEventType_LocalCfgLoadFailed":  1,
		"GtwEventType_APISvrRunFailed":     2,
		"GtwEventType_ForceUpdate":         3,
		"GtwEventType_LoginFailed":         4,
		"GtwEventType_UnAgreeDisclaimer":   5,
		"GtwEventType_NetCfgMissing":       6,
		"GtwEventType_KickedOut":           7,
		"GtwEventType_LoginPwdChanged":     8,
		"GtwEventType_BanLogin":            9,
		"GtwEventType_NeedPicVerifyCode":   10,
		"GtwEventType_NeedPhoneVerifyCode": 11,
		"GtwEventType_AppDataNotExist":     12,
		"GtwEventType_NessaryDataMissing":  13,
		"GtwEventType_TradePwdChanged":     14,
		"GtwEventType_EnableDeviceLock":    15,
	}
)

func (x GtwEventType) Enum() *GtwEventType {
	p := new(GtwEventType)
	*p = x
	return p
}

func (x GtwEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GtwEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_Notify_proto_enumTypes[0].Descriptor()
}

func (GtwEventType) Type() protoreflect.EnumType {
	return &file_Notify_proto_enumTypes[0]
}

func (x GtwEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GtwEventType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GtwEventType(num)
	return nil
}

// Deprecated: Use GtwEventType.Descriptor instead.
func (GtwEventType) EnumDescriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{0}
}

type NotifyType int32

const (
	NotifyType_NotifyType_None          NotifyType = 0 //无
	NotifyType_NotifyType_GtwEvent      NotifyType = 1 //OpenD 运行事件通知
	NotifyType_NotifyType_ProgramStatus NotifyType = 2 //程序状态
	NotifyType_NotifyType_ConnStatus    NotifyType = 3 //连接状态
	NotifyType_NotifyType_QotRight      NotifyType = 4 //行情权限
	NotifyType_NotifyType_APILevel      NotifyType = 5 //用户等级，已在2.10版本之后废弃
	NotifyType_NotifyType_APIQuota      NotifyType = 6 //API 额度
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0: "NotifyType_None",
		1: "NotifyType_GtwEvent",
		2: "NotifyType_ProgramStatus",
		3: "NotifyType_ConnStatus",
		4: "NotifyType_QotRight",
		5: "NotifyType_APILevel",
		6: "NotifyType_APIQuota",
	}
	NotifyType_value = map[string]int32{
		"NotifyType_None":          0,
		"NotifyType_GtwEvent":      1,
		"NotifyType_ProgramStatus": 2,
		"NotifyType_ConnStatus":    3,
		"NotifyType_QotRight":      4,
		"NotifyType_APILevel":      5,
		"NotifyType_APIQuota":      6,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_Notify_proto_enumTypes[1].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_Notify_proto_enumTypes[1]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NotifyType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NotifyType(num)
	return nil
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{1}
}

type APILevel int32

const (
	APILevel_APILevel_None APILevel = 0 //已废弃
)

// Enum value maps for APILevel.
var (
	APILevel_name = map[int32]string{
		0: "APILevel_None",
	}
	APILevel_value = map[string]int32{
		"APILevel_None": 0,
	}
)

func (x APILevel) Enum() *APILevel {
	p := new(APILevel)
	*p = x
	return p
}

func (x APILevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APILevel) Descriptor() protoreflect.EnumDescriptor {
	return file_Notify_proto_enumTypes[2].Descriptor()
}

func (APILevel) Type() protoreflect.EnumType {
	return &file_Notify_proto_enumTypes[2]
}

func (x APILevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *APILevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = APILevel(num)
	return nil
}

// Deprecated: Use APILevel.Descriptor instead.
func (APILevel) EnumDescriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{2}
}

type GtwEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int32                 `protobuf:"varint,1,req,name=type" json:"type,omitempty"` //GtwEventType, OpenD 运行事件类型
	Desc          *string                `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`  //事件描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GtwEvent) Reset() {
	*x = GtwEvent{}
	mi := &file_Notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GtwEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwEvent) ProtoMessage() {}

func (x *GtwEvent) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwEvent.ProtoReflect.Descriptor instead.
func (*GtwEvent) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{0}
}

func (x *GtwEvent) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *GtwEvent) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

type ConnectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QotLogined    *bool                  `protobuf:"varint,1,req,name=qotLogined" json:"qotLogined,omitempty"` //是否登录行情服务器
	TrdLogined    *bool                  `protobuf:"varint,2,req,name=trdLogined" json:"trdLogined,omitempty"` //是否登录交易服务器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectStatus) Reset() {
	*x = ConnectStatus{}
	mi := &file_Notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectStatus) ProtoMessage() {}

func (x *ConnectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectStatus.ProtoReflect.Descriptor instead.
func (*ConnectStatus) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectStatus) GetQotLogined() bool {
	if x != nil && x.QotLogined != nil {
		return *x.QotLogined
	}
	return false
}

func (x *ConnectStatus) GetTrdLogined() bool {
	if x != nil && x.TrdLogined != nil {
		return *x.TrdLogined
	}
	return false
}

type QotRight struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HkQotRight            *int32                 `protobuf:"varint,1,opt,name=hkQotRight" json:"hkQotRight,omitempty"`                        //Qot_Common.QotRight, 港股权限
	HkOptionQotRight      *int32                 `protobuf:"varint,2,opt,name=hkOptionQotRight" json:"hkOptionQotRight,omitempty"`            //Qot_Common.QotRight, 港股期权权限
	HkFutureQotRight      *int32                 `protobuf:"varint,3,opt,name=hkFutureQotRight" json:"hkFutureQotRight,omitempty"`            //Qot_Common.QotRight, 港股期货权限
	UsQotRight            *int32                 `protobuf:"varint,4,opt,name=usQotRight" json:"usQotRight,omitempty"`                        //Qot_Common.QotRight, 美股权限
	UsOptionQotRight      *int32                 `protobuf:"varint,5,opt,name=usOptionQotRight" json:"usOptionQotRight,omitempty"`            //Qot_Common.QotRight, 美股期权权限
	UsFutureQotRight      *int32                 `protobuf:"varint,6,opt,name=usFutureQotRight" json:"usFutureQotRight,omitempty"`            //Qot_Common.QotRight, 美股期货权限（已废弃）
	CnQotRight            *int32                 `protobuf:"varint,7,opt,name=cnQotRight" json:"cnQotRight,omitempty"`                        //Qot_Common.QotRight, A 股权限
	UsIndexQotRight       *int32                 `protobuf:"varint,8,opt,name=usIndexQotRight" json:"usIndexQotRight,omitempty"`              //Qot_Common.QotRight, 美股指数权限
	UsOTCQotRight         *int32                 `protobuf:"varint,9,opt,name=usOTCQotRight" json:"usOTCQotRight,omitempty"`                  //Qot_Common.QotRight, 美股 OTC 权限
	SgFutureQotRight      *int32                 `protobuf:"varint,10,opt,name=sgFutureQotRight" json:"sgFutureQotRight,omitempty"`           //Qot_Common.QotRight, 新加坡期货权限
	JpFutureQotRight      *int32                 `protobuf:"varint,11,opt,name=jpFutureQotRight" json:"jpFutureQotRight,omitempty"`           //Qot_Common.QotRight, 日本期货权限
	UsFutureQotRightCME   *int32                 `protobuf:"varint,12,opt,name=usFutureQotRightCME" json:"usFutureQotRightCME,omitempty"`     //Qot_Common.QotRight, CME 期货权限
	UsFutureQotRightCBOT  *int32                 `protobuf:"varint,13,opt,name=usFutureQotRightCBOT" json:"usFutureQotRightCBOT,omitempty"`   //Qot_Common.QotRight, CBOT 期货权限
	UsFutureQotRightNYMEX *int32                 `protobuf:"varint,14,opt,name=usFutureQotRightNYMEX" json:"usFutureQotRightNYMEX,omitempty"` //Qot_Common.QotRight, NYMEX 期货权限
	UsFutureQotRightCOMEX *int32                 `protobuf:"varint,15,opt,name=usFutureQotRightCOMEX" json:"usFutureQotRightCOMEX,omitempty"` //Qot_Common.QotRight, COMEX 期货权限
	UsFutureQotRightCBOE  *int32                 `protobuf:"varint,16,opt,name=usFutureQotRightCBOE" json:"usFutureQotRightCBOE,omitempty"`   //Qot_Common.QotRight, CBOE 期货权限
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QotRight) Reset() {
	*x = QotRight{}
	mi := &file_Notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QotRight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QotRight) ProtoMessage() {}

func (x *QotRight) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QotRight.ProtoReflect.Descriptor instead.
func (*QotRight) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{2}
}

func (x *QotRight) GetHkQotRight() int32 {
	if x != nil && x.HkQotRight != nil {
		return *x.HkQotRight
	}
	return 0
}

func (x *QotRight) GetHkOptionQotRight() int32 {
	if x != nil && x.HkOptionQotRight != nil {
		return *x.HkOptionQotRight
	}
	return 0
}

func (x *QotRight) GetHkFutureQotRight() int32 {
	if x != nil && x.HkFutureQotRight != nil {
		return *x.HkFutureQotRight
	}
	return 0
}

func (x *QotRight) GetUsQotRight() int32 {
	if x != nil && x.UsQotRight != nil {
		return *x.UsQotRight
	}
	return 0
}

func (x *QotRight) GetUsOptionQotRight() int32 {
	if x != nil && x.UsOptionQotRight != nil {
		return *x.UsOptionQotRight
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRight() int32 {
	if x != nil && x.UsFutureQotRight != nil {
		return *x.UsFutureQotRight
	}
	return 0
}

func (x *QotRight) GetCnQotRight() int32 {
	if x != nil && x.CnQotRight != nil {
		return *x.CnQotRight
	}
	return 0
}

func (x *QotRight) GetUsIndexQotRight() int32 {
	if x != nil && x.UsIndexQotRight != nil {
		return *x.UsIndexQotRight
	}
	return 0
}

func (x *QotRight) GetUsOTCQotRight() int32 {
	if x != nil && x.UsOTCQotRight != nil {
		return *x.UsOTCQotRight
	}
	return 0
}

func (x *QotRight) GetSgFutureQotRight() int32 {
	if x != nil && x.SgFutureQotRight != nil {
		return *x.SgFutureQotRight
	}
	return 0
}

func (x *QotRight) GetJpFutureQotRight() int32 {
	if x != nil && x.JpFutureQotRight != nil {
		return *x.JpFutureQotRight
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRightCME() int32 {
	if x != nil && x.UsFutureQotRightCME != nil {
		return *x.UsFutureQotRightCME
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRightCBOT() int32 {
	if x != nil && x.UsFutureQotRightCBOT != nil {
		return *x.UsFutureQotRightCBOT
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRightNYMEX() int32 {
	if x != nil && x.UsFutureQotRightNYMEX != nil {
		return *x.UsFutureQotRightNYMEX
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRightCOMEX() int32 {
	if x != nil && x.UsFutureQotRightCOMEX != nil {
		return *x.UsFutureQotRightCOMEX
	}
	return 0
}

func (x *QotRight) GetUsFutureQotRightCBOE() int32 {
	if x != nil && x.UsFutureQotRightCBOE != nil {
		return *x.UsFutureQotRightCBOE
	}
	return 0
}

type APIQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsed     *int32                 `protobuf:"varint,1,opt,name=totalUsed" json:"totalUsed,omitempty"` //所有连接已使用的订阅额度
	OwnUsed       *int32                 `protobuf:"varint,2,opt,name=ownUsed" json:"ownUsed,omitempty"`     //当前连接已使用的订阅额度
	Remain        *int32                 `protobuf:"varint,3,opt,name=remain" json:"remain,omitempty"`       //剩余订阅额度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIQuota) Reset() {
	*x = APIQuota{}
	mi := &file_Notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIQuota) ProtoMessage() {}

func (x *APIQuota) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIQuota.ProtoReflect.Descriptor instead.
func (*APIQuota) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{3}
}

func (x *APIQuota) GetTotalUsed() int32 {
	if x != nil && x.TotalUsed != nil {
		return *x.TotalUsed
	}
	return 0
}

func (x *APIQuota) GetOwnUsed() int32 {
	if x != nil && x.OwnUsed != nil {
		return *x.OwnUsed
	}
	return 0
}

func (x *APIQuota) GetRemain() int32 {
	if x != nil && x.Remain != nil {
		return *x.Remain
	}
	return 0
}

// 推送协议，无 C2S 和 Request 结构，retType 始终是 RetType_Succeed。
type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int32                 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`                              //NotifyType, 通知类型
	Event         *GtwEvent              `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`                             //事件信息
	ProgramStatus *common.ProgramStatus  `protobuf:"bytes,3,opt,name=programStatus" json:"programStatus,omitempty"`             //程序状态
	ConnectStatus *ConnectStatus         `protobuf:"bytes,4,opt,name=connectStatus" json:"connectStatus,omitempty"`             //连接状态
	QotRight      *QotRight              `protobuf:"bytes,5,opt,name=qotRight" json:"qotRight,omitempty"`                       //行情权限
	ApiLevel      *APILevel              `protobuf:"varint,6,opt,name=apiLevel,enum=Notify.APILevel" json:"apiLevel,omitempty"` //用户等级，已在 2.10 版本之后废弃
	ApiQuota      *APIQuota              `protobuf:"bytes,7,opt,name=apiQuota" json:"apiQuota,omitempty"`                       //API 额度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{4}
}

func (x *S2C) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *S2C) GetEvent() *GtwEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *S2C) GetProgramStatus() *common.ProgramStatus {
	if x != nil {
		return x.ProgramStatus
	}
	return nil
}

func (x *S2C) GetConnectStatus() *ConnectStatus {
	if x != nil {
		return x.ConnectStatus
	}
	return nil
}

func (x *S2C) GetQotRight() *QotRight {
	if x != nil {
		return x.QotRight
	}
	return nil
}

func (x *S2C) GetApiLevel() APILevel {
	if x != nil && x.ApiLevel != nil {
		return *x.ApiLevel
	}
	return APILevel_APILevel_None
}

func (x *S2C) GetApiQuota() *APIQuota {
	if x != nil {
		return x.ApiQuota
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下 3 个字段每条协议都有，注释说明在 InitConnect.proto 中。
	RetType       *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Notify_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Notify_proto protoreflect.FileDescriptor

const file_Notify_proto_rawDesc = "" +
	"\n" +
	"\fNotify.proto\x12\x06Notify\x1a\fCommon.proto\"2\n" +
	"\bGtwEvent\x12\x12\n" +
	"\x04type\x18\x01 \x02(\x05R\x04type\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"O\n" +
	"\rConnectStatus\x12\x1e\n" +
	"\n" +
	"qotLogined\x18\x01 \x02(\bR\n" +
	"qotLogined\x12\x1e\n" +
	"\n" +
	"trdLogined\x18\x02 \x02(\bR\n" +
	"trdLogined\"\xc8\x05\n" +
	"\bQotRight\x12\x1e\n" +
	"\n" +
	"hkQotRight\x18\x01 \x01(\x05R\n" +
	"hkQotRight\x12*\n" +
	"\x10hkOptionQotRight\x18\x02 \x01(\x05R\x10hkOptionQotRight\x12*\n" +
	"\x10hkFutureQotRight\x18\x03 \x01(\x05R\x10hkFutureQotRight\x12\x1e\n" +
	"\n" +
	"usQotRight\x18\x04 \x01(\x05R\n" +
	"usQotRight\x12*\n" +
	"\x10usOptionQotRight\x18\x05 \x01(\x05R\x10usOptionQotRight\x12*\n" +
	"\x10usFutureQotRight\x18\x06 \x01(\x05R\x10usFutureQotRight\x12\x1e\n" +
	"\n" +
	"cnQotRight\x18\a \x01(\x05R\n" +
	"cnQotRight\x12(\n" +
	"\x0fusIndexQotRight\x18\b \x01(\x05R\x0fusIndexQotRight\x12$\n" +
	"\rusOTCQotRight\x18\t \x01(\x05R\rusOTCQotRight\x12*\n" +
	"\x10sgFutureQotRight\x18\n" +
	" \x01(\x05R\x10sgFutureQotRight\x12*\n" +
	"\x10jpFutureQotRight\x18\v \x01(\x05R\x10jpFutureQotRight\x120\n" +
	"\x13usFutureQotRightCME\x18\f \x01(\x05R\x13usFutureQotRightCME\x122\n" +
	"\x14usFutureQotRightCBOT\x18\r \x01(\x05R\x14usFutureQotRightCBOT\x124\n" +
	"\x15usFutureQotRightNYMEX\x18\x0e \x01(\x05R\x15usFutureQotRightNYMEX\x124\n" +
	"\x15usFutureQotRightCOMEX\x18\x0f \x01(\x05R\x15usFutureQotRightCOMEX\x122\n" +
	"\x14usFutureQotRightCBOE\x18\x10 \x01(\x05R\x14usFutureQotRightCBOE\"Z\n" +
	"\bAPIQuota\x12\x1c\n" +
	"\ttotalUsed\x18\x01 \x01(\x05R\ttotalUsed\x12\x18\n" +
	"\aownUsed\x18\x02 \x01(\x05R\aownUsed\x12\x16\n" +
	"\x06remain\x18\x03 \x01(\x05R\x06remain\"\xc5\x02\n" +
	"\x03S2C\x12\x12\n" +
	"\x04type\x18\x01 \x02(\x05R\x04type\x12&\n" +
	"\x05event\x18\x02 \x01(\v2\x10.Notify.GtwEventR\x05event\x12;\n" +
	"\rprogramStatus\x18\x03 \x01(\v2\x15.Common.ProgramStatusR\rprogramStatus\x12;\n" +
	"\rconnectStatus\x18\x04 \x01(\v2\x15.Notify.ConnectStatusR\rconnectStatus\x12,\n" +
	"\bqotRight\x18\x05 \x01(\v2\x10.Notify.QotRightR\bqotRight\x12,\n" +
	"\bapiLevel\x18\x06 \x01(\x0e2\x10.Notify.APILevelR\bapiLevel\x12,\n" +
	"\bapiQuota\x18\a \x01(\v2\x10.Notify.APIQuotaR\bapiQuota\"{\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12\x1d\n" +
	"\x03s2c\x18\x04 \x01(\v2\v.Notify.S2CR\x03s2c*\x9b\x04\n" +
	"\fGtwEventType\x12\x15\n" +
	"\x11GtwEventType_None\x10\x00\x12#\n" +
	"\x1fGtwEventType_LocalCfgLoadFailed\x10\x01\x12 \n" +
	"\x1cGtwEventType_APISvrRunFailed\x10\x02\x12\x1c\n" +
	"\x18GtwEventType_ForceUpdate\x10\x03\x12\x1c\n" +
	"\x18GtwEventType_LoginFailed\x10\x04\x12\"\n" +
	"\x1eGtwEventType_UnAgreeDisclaimer\x10\x05\x12\x1e\n" +
	"\x1aGtwEventType_NetCfgMissing\x10\x06\x12\x1a\n" +
	"\x16GtwEventType_KickedOut\x10\a\x12 \n" +
	"\x1cGtwEventType_LoginPwdChanged\x10\b\x12\x19\n" +
	"\x15GtwEventType_BanLogin\x10\t\x12\"\n" +
	"\x1eGtwEventType_NeedPicVerifyCode\x10\n" +
	"\x12$\n" +
	" GtwEventType_NeedPhoneVerifyCode\x10\v\x12 \n" +
	"\x1cGtwEventType_AppDataNotExist\x10\f\x12#\n" +
	"\x1fGtwEventType_NessaryDataMissing\x10\r\x12 \n" +
	"\x1cGtwEventType_TradePwdChanged\x10\x0e\x12!\n" +
	"\x1dGtwEventType_EnableDeviceLock\x10\x0f*\xbe\x01\n" +
	"\n" +
	"NotifyType\x12\x13\n" +
	"\x0fNotifyType_None\x10\x00\x12\x17\n" +
	"\x13NotifyType_GtwEvent\x10\x01\x12\x1c\n" +
	"\x18NotifyType_ProgramStatus\x10\x02\x12\x19\n" +
	"\x15NotifyType_ConnStatus\x10\x03\x12\x17\n" +
	"\x13NotifyType_QotRight\x10\x04\x12\x17\n" +
	"\x13NotifyType_APILevel\x10\x05\x12\x17\n" +
	"\x13NotifyType_APIQuota\x10\x06*\x1d\n" +
	"\bAPILevel\x12\x11\n" +
	"\rAPILevel_None\x10\x00BP\n" +
	"\x13com.futu.openapi.pbZ9github.com/jftrade/jftrade-main/pkg/futu/pb/notify;notify"

var (
	file_Notify_proto_rawDescOnce sync.Once
	file_Notify_proto_rawDescData []byte
)

func file_Notify_proto_rawDescGZIP() []byte {
	file_Notify_proto_rawDescOnce.Do(func() {
		file_Notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Notify_proto_rawDesc), len(file_Notify_proto_rawDesc)))
	})
	return file_Notify_proto_rawDescData
}

var file_Notify_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Notify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Notify_proto_goTypes = []any{
	(GtwEventType)(0),            // 0: Notify.GtwEventType
	(NotifyType)(0),              // 1: Notify.NotifyType
	(APILevel)(0),                // 2: Notify.APILevel
	(*GtwEvent)(nil),             // 3: Notify.GtwEvent
	(*ConnectStatus)(nil),        // 4: Notify.ConnectStatus
	(*QotRight)(nil),             // 5: Notify.QotRight
	(*APIQuota)(nil),             // 6: Notify.APIQuota
	(*S2C)(nil),                  // 7: Notify.S2C
	(*Response)(nil),             // 8: Notify.Response
	(*common.ProgramStatus)(nil), // 9: Common.ProgramStatus
}
var file_Notify_proto_depIdxs = []int32{
	3, // 0: Notify.S2C.event:type_name -> Notify.GtwEvent
	9, // 1: Notify.S2C.programStatus:type_name -> Common.ProgramStatus
	4, // 2: Notify.S2C.connectStatus:type_name -> Notify.ConnectStatus
	5, // 3: Notify.S2C.qotRight:type_name -> Notify.QotRight
	2, // 4: Notify.S2C.apiLevel:type_name -> Notify.APILevel
	6, // 5: Notify.S2C.apiQuota:type_name -> Notify.APIQuota
	7, // 6: Notify.Response.s2c:type_name -> Notify.S2C
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_Notify_proto_init() }
func file_Notify_proto_init() {
	if File_Notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Notify_proto_rawDesc), len(file_Notify_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Notify_proto_goTypes,
		DependencyIndexes: file_Notify_proto_depIdxs,
		EnumInfos:         file_Notify_proto_enumTypes,
		MessageInfos:      file_Notify_proto_msgTypes,
	}.Build()
	File_Notify_proto = out.File
	file_Notify_proto_goTypes = nil
	file_Notify_proto_depIdxs = nil
}
