import {
  nextGetTechnicalIndicatorNodeText,
  nextTechnicalIndicatorConditionNodeText,
} from "./strategyVisualBuilderIndicatorBlock";
import { RISK_RULE_BLOCK_DEFINITION } from "./strategyVisualBuilderRiskBlock";
import type { StrategyBlockDefinition } from "./strategyVisualBuilderCatalog";

export const STRATEGY_BLOCK_CATALOG: StrategyBlockDefinition[] = [
  {
    kind: "onInit",
    label: "策略启动",
    description: "策略启动时执行一次，适合打印上下文或做预热。",
    shape: "circle",
    text: "策略启动",
    properties: { blockKind: "onInit" },
    accent: "#0f766e",
  },
  {
    kind: "onKLineClosed",
    label: "K 线收盘",
    description: "每次 K 线收盘触发，是当前 Pine 策略的核心入口。",
    shape: "circle",
    text: "K 线收盘",
    properties: { blockKind: "onKLineClosed" },
    accent: "#1d4ed8",
  },
  {
    kind: "getTechnicalIndicator",
    label: "指标数据",
    description: "加载一个技术指标结果，供后续判断节点或动作节点复用。",
    shape: "rect",
    text: nextGetTechnicalIndicatorNodeText({
      blockKind: "getTechnicalIndicator",
      indicatorType: "rsi",
      period: 14,
    }),
    properties: {
      blockKind: "getTechnicalIndicator",
      indicatorType: "rsi",
      period: 14,
    },
    accent: "#0f766e",
    paletteVisible: false,
  },
  {
    kind: "technicalIndicatorCondition",
    label: "指标条件判断",
    description: "基于已定义变量里的指标结果做数值或形态判断，并提供 true / false 两个后续分支。",
    shape: "diamond",
    text: nextTechnicalIndicatorConditionNodeText({
      blockKind: "technicalIndicatorCondition",
      indicatorType: "rsi",
      conditionMode: "numeric",
      operator: "<",
      threshold: 30,
    }),
    properties: {
      blockKind: "technicalIndicatorCondition",
      indicatorType: "rsi",
      conditionMode: "numeric",
      operator: "<",
      threshold: 30,
    },
    accent: "#ca8a04",
    paletteVisible: true,
  },
  {
    kind: "seriesCondition",
    label: "序列条件判断",
    description: "基于价格、成交量或派生序列做比较、ta.rising/ta.falling、ta.barssince/ta.valuewhen 判断。",
    shape: "diamond",
    text: "Close > 阈值",
    properties: {
      blockKind: "seriesCondition",
      mode: "compare",
      source: "close",
      operator: ">",
      threshold: 520,
      length: 3,
      eventSource: "close",
      eventOperator: ">",
      eventThreshold: 520,
      valueSource: "close",
      occurrence: 0,
    },
    accent: "#7c3aed",
    paletteVisible: true,
  },
  {
    kind: "strategyInput",
    label: "策略参数",
    description: "声明 Pine input 默认参数，供指标、条件、MTF 或自定义表达式引用。",
    shape: "rect",
    text: "参数 length = 20",
    properties: {
      blockKind: "strategyInput",
      variableName: "length",
      inputType: "int",
      title: "Length",
      defaultValue: 20,
    },
    accent: "#2563eb",
  },
  {
    kind: "derivedSeries",
    label: "派生序列",
    description: "生成 history、nz、math、四则表达式或 cross 系列派生变量。",
    shape: "rect",
    text: "派生序列 signal",
    properties: {
      blockKind: "derivedSeries",
      variableName: "signal",
      mode: "history",
      source: "close",
      historyOffset: 1,
      fallbackValue: 0,
      mathFunction: "max",
      leftExpression: "close",
      operator: "-",
      rightExpression: "open",
      crossFunction: "crossover",
    },
    accent: "#0891b2",
  },
  {
    kind: "mtfSeries",
    label: "高周期序列",
    description: "生成同标的静态 timeframe request.security 一阶序列。",
    shape: "rect",
    text: "MTF 日线 close",
    properties: {
      blockKind: "mtfSeries",
      variableName: "mtf_close",
      timeframe: "D",
      expressionType: "source",
      source: "close",
      historyOffset: 1,
      indicatorExpression: "ta.ema(close, 20)",
    },
    accent: "#4f46e5",
  },
  {
    kind: "stateVariable",
    label: "持久状态",
    description: "声明 var 标量状态，支持 number/bool/string 默认值。",
    shape: "rect",
    text: "状态 armed = false",
    properties: {
      blockKind: "stateVariable",
      variableName: "armed",
      valueType: "bool",
      initialValue: false,
    },
    accent: "#64748b",
  },
  {
    kind: "stateUpdate",
    label: "更新状态",
    description: "对已声明的标量状态执行 := 更新。",
    shape: "rect",
    text: "更新状态 armed",
    properties: {
      blockKind: "stateUpdate",
      variableName: "armed",
      expression: "close > open",
    },
    accent: "#64748b",
  },
  {
    kind: "collectionStat",
    label: "集合统计",
    description: "对固定 source 列表执行 array.from(...).min/max/avg/sum/median/stdev/variance/percentile 只读统计。",
    shape: "rect",
    text: "集合统计 range_median",
    properties: {
      blockKind: "collectionStat",
      variableName: "range_median",
      statFunction: "median",
      sourceA: "close",
      sourceB: "open",
      sourceC: "high",
      percentile: 50,
    },
    accent: "#0369a1",
  },
  {
    kind: "timeFilter",
    label: "时间过滤",
    description: "基于闭盘 K 线 hour/minute/dayofweek 生成安全时间条件。",
    shape: "diamond",
    text: "时间过滤",
    properties: {
      blockKind: "timeFilter",
      mode: "between",
      startHour: 9,
      startMinute: 30,
      endHour: 16,
      endMinute: 0,
      dayOfWeek: 2,
    },
    accent: "#0e7490",
  },
  {
    kind: "sessionFilter",
    label: "交易时段过滤",
    description: "基于 PineTS worker 的 session.ismarket / ispremarket / ispostmarket 状态过滤。",
    shape: "diamond",
    text: "交易时段过滤",
    properties: {
      blockKind: "sessionFilter",
      scope: "market",
    },
    accent: "#0e7490",
  },
  {
    kind: "ifCloseAbove",
    label: "收盘价高于",
    description: "当 ctx.kline.close 高于阈值时执行后续动作。",
    shape: "diamond",
    text: "收盘价 > 阈值",
    properties: {
      blockKind: "ifCloseAbove",
      threshold: 520,
    },
    accent: "#d97706",
  },
  {
    kind: "ifCloseBelow",
    label: "收盘价低于",
    description: "当 ctx.kline.close 低于阈值时执行后续动作。",
    shape: "diamond",
    text: "收盘价 < 阈值",
    properties: {
      blockKind: "ifCloseBelow",
      threshold: 480,
    },
    accent: "#b45309",
  },
  {
    kind: "log",
    label: "输出日志",
    description: "调用 console.log，把上下文或信号写入运行日志。",
    shape: "rect",
    text: "输出日志",
    properties: {
      blockKind: "log",
      message: "观察到新的策略事件",
    },
    accent: "#475569",
  },
  {
    kind: "notify",
    label: "发送通知",
    description: "生成 alert()，把策略信号发到控制台通知流。",
    shape: "rect",
    text: "发送通知",
    properties: {
      blockKind: "notify",
      message: "策略条件命中，准备处理后续动作",
    },
    accent: "#be123c",
  },
  {
    kind: "placeOrder",
    label: "下单",
    description: "向券商提交买入或卖出订单，支持固定股数、固定金额和账户权益百分比三种 Pine 对齐数量模式。",
    shape: "rect",
    text: "下单",
    properties: {
      blockKind: "placeOrder",
      orderAction: "entry",
      orderId: "Long",
      side: "BUY",
      orderType: "MARKET",
      entryPositionPolicy: "sameDirection",
      quantityMode: "shares",
      quantityValue: 100,
      limitPrice: 0,
      stopPrice: 0,
      riskAllowedDirection: "all",
    },
    accent: "#0f766e",
  },
  RISK_RULE_BLOCK_DEFINITION,
  {
    kind: "stopLoss",
    label: "止损",
    description: "基于 Go 预计算的风险快照，对当前多空仓位执行止损、止盈或追踪止损平仓。",
    shape: "rect",
    text: "自动止损 1柱 2%",
    properties: {
      blockKind: "stopLoss",
      mode: "stopLoss",
      direction: "auto",
      timeValue: 1,
      timeUnit: "bar",
      percentage: 2,
      windowPolicy: "continuous",
    },
    accent: "#b91c1c",
  },
];
