import type {
  TechnicalIndicatorConditionMode,
  TechnicalIndicatorDefinition,
  TechnicalIndicatorInputSlot,
  TechnicalIndicatorPatternOption,
  TechnicalIndicatorType,
} from "./strategyVisualBuilderIndicatorBlock";

export const TECHNICAL_INDICATOR_DEFINITION_MAP: Record<
  TechnicalIndicatorType,
  TechnicalIndicatorDefinition
> = {
  movingAverage: {
    label: "双均线",
    getterLabel: "均线",
    conditionModes: ["pattern"],
    defaultConditionMode: "pattern",
    capabilityId: "indicator.ma_source_aware",
    parameterShape: "windowSize",
    defaultSource: "close",
    defaultWindowSize: 20,
  },
  rsi: {
    label: "RSI",
    conditionModes: ["numeric", "pattern"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.rsi",
    parameterShape: "period",
    defaultSource: "close",
    defaultPeriod: 14,
    numericTargetLabel: "RSI 值",
  },
  macd: {
    label: "MACD",
    conditionModes: ["numeric", "pattern"],
    defaultConditionMode: "pattern",
    capabilityId: "indicator.macd",
    parameterShape: "macd",
    defaultFastPeriod: 12,
    defaultSlowPeriod: 26,
    defaultSignalPeriod: 9,
    numericTargetLabel: "柱状图",
  },
  kdj: {
    label: "KDJ",
    conditionModes: ["numeric", "pattern"],
    defaultConditionMode: "pattern",
    capabilityId: "indicator.v15_common_ta_set",
    parameterShape: "kdj",
    defaultPeriod: 9,
    defaultM1: 3,
    defaultM2: 3,
    numericTargetLabel: "J 值",
  },
  atr: {
    label: "ATR",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.atr",
    parameterShape: "period",
    defaultPeriod: 14,
    numericTargetLabel: "ATR 值",
  },
  cci: {
    label: "CCI",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.cci",
    parameterShape: "period",
    defaultSource: "hlc3",
    defaultPeriod: 20,
    numericTargetLabel: "CCI 值",
  },
  williamsR: {
    label: "Williams %R",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.williams_r",
    parameterShape: "period",
    defaultPeriod: 14,
    numericTargetLabel: "Williams %R 值",
  },
  bollinger: {
    label: "布林带",
    conditionModes: ["pattern"],
    defaultConditionMode: "pattern",
    capabilityId: "indicator.bollinger",
    parameterShape: "bollinger",
    defaultSource: "close",
    defaultPeriod: 20,
    defaultMultiplier: 2,
  },
  stdev: {
    label: "标准差",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.source_aware_core",
    parameterShape: "period",
    defaultSource: "close",
    defaultPeriod: 20,
    numericTargetLabel: "标准差",
  },
  variance: {
    label: "方差",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.source_aware_core",
    parameterShape: "period",
    defaultSource: "close",
    defaultPeriod: 20,
    numericTargetLabel: "方差",
  },
  highest: {
    label: "最高值",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.rolling_window",
    parameterShape: "period",
    defaultSource: "high",
    defaultPeriod: 20,
    numericTargetLabel: "最高值",
  },
  lowest: {
    label: "最低值",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.rolling_window",
    parameterShape: "period",
    defaultSource: "low",
    defaultPeriod: 20,
    numericTargetLabel: "最低值",
  },
  sum: {
    label: "区间求和",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.sum",
    parameterShape: "period",
    defaultSource: "volume",
    defaultPeriod: 20,
    numericTargetLabel: "求和值",
  },
  vwap: {
    label: "VWAP",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.vwap_mfi_dmi_supertrend",
    parameterShape: "sourceOnly",
    defaultSource: "hlc3",
    numericTargetLabel: "VWAP",
  },
  mfi: {
    label: "MFI",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.vwap_mfi_dmi_supertrend",
    parameterShape: "period",
    defaultSource: "hlc3",
    defaultPeriod: 14,
    numericTargetLabel: "MFI",
  },
  dmi: {
    label: "DMI/ADX",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.vwap_mfi_dmi_supertrend",
    parameterShape: "dmi",
    defaultPeriod: 14,
    defaultAdxSmoothing: 14,
    numericTargetLabel: "ADX",
  },
  supertrend: {
    label: "Supertrend",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.vwap_mfi_dmi_supertrend",
    parameterShape: "supertrend",
    defaultPeriod: 10,
    defaultFactor: 3,
    numericTargetLabel: "方向",
  },
  sar: {
    label: "Parabolic SAR",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.sar",
    parameterShape: "sar",
    defaultStart: 0.02,
    defaultIncrement: 0.02,
    defaultMaximum: 0.2,
    numericTargetLabel: "SAR 值",
  },
  linreg: {
    label: "线性回归",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.linreg_obv_pivots",
    parameterShape: "linreg",
    defaultSource: "close",
    defaultPeriod: 5,
    defaultOffset: 0,
    numericTargetLabel: "线性回归值",
  },
  obv: {
    label: "OBV",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.linreg_obv_pivots",
    parameterShape: "sourceOnly",
    defaultSource: "close",
    numericTargetLabel: "OBV",
  },
  pivotHigh: {
    label: "Pivot High",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.linreg_obv_pivots",
    parameterShape: "pivot",
    defaultSource: "high",
    defaultLeftBars: 2,
    defaultRightBars: 2,
    numericTargetLabel: "Pivot High",
  },
  pivotLow: {
    label: "Pivot Low",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.linreg_obv_pivots",
    parameterShape: "pivot",
    defaultSource: "low",
    defaultLeftBars: 2,
    defaultRightBars: 2,
    numericTargetLabel: "Pivot Low",
  },
  keltner: {
    label: "Keltner 通道",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.keltner_alma",
    parameterShape: "sourcePeriodMultiplier",
    defaultSource: "close",
    defaultPeriod: 20,
    defaultMultiplier: 1.5,
    numericTargetLabel: "上轨",
  },
  alma: {
    label: "ALMA",
    conditionModes: ["numeric"],
    defaultConditionMode: "numeric",
    capabilityId: "indicator.keltner_alma",
    parameterShape: "alma",
    defaultSource: "close",
    defaultPeriod: 20,
    defaultOffset: 0.85,
    defaultSigma: 6,
    numericTargetLabel: "ALMA",
  },
};

export const CONDITION_MODE_LABEL_MAP: Record<
  TechnicalIndicatorConditionMode,
  string
> = {
  none: "仅加载指标",
  numeric: "数值型",
  pattern: "形态型",
};

export const PATTERN_OPTION_MAP: Record<TechnicalIndicatorType, TechnicalIndicatorPatternOption[]> = {
  movingAverage: [
    { value: "goldenCross", label: "金叉" },
    { value: "deathCross", label: "死叉" },
  ],
  rsi: [
    { value: "topDivergence", label: "顶背离" },
    { value: "bottomDivergence", label: "底背离" },
  ],
  macd: [
    { value: "goldenCross", label: "金叉" },
    { value: "deathCross", label: "死叉" },
    { value: "topDivergence", label: "顶背离" },
    { value: "bottomDivergence", label: "底背离" },
  ],
  kdj: [
    { value: "goldenCross", label: "金叉" },
    { value: "deathCross", label: "死叉" },
    { value: "topDivergence", label: "顶背离" },
    { value: "bottomDivergence", label: "底背离" },
  ],
  atr: [],
  cci: [],
  williamsR: [],
  bollinger: [
    { value: "closeAboveUpperBand", label: "收盘价突破上轨" },
    { value: "closeBelowLowerBand", label: "收盘价跌破下轨" },
  ],
  stdev: [],
  variance: [],
  highest: [],
  lowest: [],
  sum: [],
  vwap: [],
  mfi: [],
  dmi: [],
  supertrend: [],
  sar: [],
  linreg: [],
  obv: [],
  pivotHigh: [],
  pivotLow: [],
  keltner: [],
  alma: [],
};

export const TECHNICAL_INDICATOR_INPUT_SLOTS: Record<
  TechnicalIndicatorType,
  TechnicalIndicatorInputSlot[]
> = {
  movingAverage: ["fast", "slow"],
  rsi: ["primary"],
  macd: ["primary"],
  kdj: ["primary"],
  atr: ["primary"],
  cci: ["primary"],
  williamsR: ["primary"],
  bollinger: ["primary"],
  stdev: ["primary"],
  variance: ["primary"],
  highest: ["primary"],
  lowest: ["primary"],
  sum: ["primary"],
  vwap: ["primary"],
  mfi: ["primary"],
  dmi: ["primary"],
  supertrend: ["primary"],
  sar: ["primary"],
  linreg: ["primary"],
  obv: ["primary"],
  pivotHigh: ["primary"],
  pivotLow: ["primary"],
  keltner: ["primary"],
  alma: ["primary"],
};


