package broker

// BuiltinCapabilityCatalog is deliberately explicit: adding generated OpenD
// protocols without mapping their product surface here does not silently expose
// them. CI validates this catalog and the adapter protocol coverage manifest.
var BuiltinCapabilityCatalog = CapabilityCatalog{
	Version: "2026-07-17.opend-10.9.6908",
	Features: []CapabilityDefinition{
		catalogRead(FeatureMarketSearch, "InstrumentProfileReader", "/api/v1/market-data/instruments", "/workspace", "market.search", "TestCapabilityCatalog"),
		catalogRead(FeatureInstrumentProfile, "InstrumentProfileReader", "/api/v1/market-data/instruments/{instrumentId}/profile", "/workspace?tab=company", "market.instrument_profile", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketSnapshot, "BatchSnapshotSource", "/api/v1/market-data/snapshots/{market}/{symbol}", "/workspace?tab=chart", "market.snapshot", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketSnapshots, "BatchSnapshotSource", "/api/v1/market-data/snapshots", "/workspace", "market.snapshots", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketCandles, "MarketDataReader", "/api/v1/market-data/candles/{market}/{symbol}", "/workspace?tab=chart", "market.candles", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketIntraday, "MarketMicrostructureReader", "/api/v1/market-data/intraday/{instrumentId}", "/workspace?tab=chart", "market.intraday", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketTicks, "MarketMicrostructureReader", "/api/v1/market-data/ticks/{instrumentId}", "/workspace?tab=chart", "market.ticks", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketDepth, "MarketMicrostructureReader", "/api/v1/market-data/depth/{market}/{symbol}", "/workspace?tab=chart", "market.depth", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketBrokerQueue, "MarketMicrostructureReader", "/api/v1/market-data/broker-queue/{instrumentId}", "/workspace?tab=chart", "market.broker_queue", "TestCapabilityCatalog"),
		catalogRead(FeatureMarketCapitalFlow, "MarketMicrostructureReader", "/api/v1/market-data/capital-flow/{instrumentId}", "/workspace?tab=company", "market.capital_flow", "TestCapabilityCatalog"),
		catalogRead(FeatureOptionChain, "DerivativeCatalogReader", "/api/v1/market-data/options/chains/{instrumentId}", "/workspace?tab=options", "derivatives.option_chain", "TestCapabilityCatalog"),
		catalogRead(FeatureOptionScreen, "DerivativeCatalogReader", "/api/v1/market-data/options/screens", "/research?section=options", "derivatives.option_screen", "TestCapabilityCatalog"),
		catalogRead(FeatureOptionAnalysis, "OptionAnalyticsReader", "/api/v1/market-data/options/analysis/{instrumentId}", "/workspace?tab=options", "derivatives.option_analysis", "TestCapabilityCatalog"),
		catalogRead(FeatureOptionEvents, "OptionAnalyticsReader", "/api/v1/market-data/options/events", "/research?section=options", "derivatives.option_events", "TestCapabilityCatalog"),
		catalogRead(FeatureWarrants, "DerivativeCatalogReader", "/api/v1/market-data/warrants", "/workspace?tab=warrants", "derivatives.warrants", "TestCapabilityCatalog"),
		catalogRead(FeatureFutures, "DerivativeCatalogReader", "/api/v1/market-data/futures", "/workspace", "derivatives.futures", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchInstrument, "InstrumentResearchReader", "/api/v1/research/instruments/{instrumentId}", "/workspace?tab=company", "research.instrument", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchFinancials, "InstrumentResearchReader", "/api/v1/research/financials/{instrumentId}", "/workspace?tab=company", "research.financials", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchValuation, "InstrumentResearchReader", "/api/v1/research/valuation/{instrumentId}", "/workspace?tab=company", "research.valuation", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchAnalyst, "InstrumentResearchReader", "/api/v1/research/analyst/{instrumentId}", "/workspace?tab=company", "research.analyst", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchOwnership, "InstrumentResearchReader", "/api/v1/research/ownership/{instrumentId}", "/workspace?tab=company", "research.ownership", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchCorporateAction, "InstrumentResearchReader", "/api/v1/research/corporate-actions/{instrumentId}", "/workspace?tab=company", "research.corporate_actions", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchShortInterest, "InstrumentResearchReader", "/api/v1/research/short-interest/{instrumentId}", "/workspace?tab=company", "research.short_interest", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchNews, "InstrumentResearchReader", "/api/v1/market-data/news", "/workspace?tab=news", "research.news", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchScreen, "MarketResearchReader", "/api/v1/research/screens", "/research?section=screens", "research.screen", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchCalendar, "MarketResearchReader", "/api/v1/research/calendars", "/research?section=calendar", "research.calendar", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchMacro, "MarketResearchReader", "/api/v1/research/macro", "/research?section=macro", "research.macro", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchRankings, "MarketResearchReader", "/api/v1/research/rankings", "/research?section=market", "research.rankings", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchInstitutions, "MarketResearchReader", "/api/v1/research/institutions", "/research?section=institutions", "research.institutions", "TestCapabilityCatalog"),
		catalogRead(FeatureResearchIndustry, "MarketResearchReader", "/api/v1/research/industries", "/research?section=industries", "research.industry", "TestCapabilityCatalog"),
		catalogRead(FeatureTechnicalIndicator, "TechnicalIndicatorReader", "/api/v1/research/technical-indicators/{instrumentId}", "/research?section=market", "research.technical_indicators", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionDiscover, "PredictionMarketReader", "/api/v1/market-data/prediction/categories", "/research?section=prediction", "prediction.discover", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionSnapshot, "PredictionMarketReader", "/api/v1/market-data/prediction/contracts/{code}/snapshot", "/workspace?tab=contract&marketSegment=prediction", "prediction.snapshot", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionDepth, "PredictionMarketReader", "/api/v1/market-data/prediction/contracts/{code}/order-book", "/workspace?tab=depth&marketSegment=prediction", "prediction.depth", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionHistory, "PredictionMarketReader", "/api/v1/market-data/prediction/contracts/{code}/candles", "/workspace?tab=chart&marketSegment=prediction", "prediction.history", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionComboEligible, "PredictionMarketReader", "/api/v1/market-data/prediction/combos/eligible-events", "/research?section=prediction", "prediction.combo_eligible", "TestCapabilityCatalog"),
		catalogRead(FeaturePredictionComboQuote, "PredictionMarketReader", "/api/v1/market-data/prediction/combos/quotes", "/research?section=prediction", "prediction.combo_quote", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionOrderPreview, "ProductRuleProvider", "/api/v1/execution/previews", "/workspace?surface=order", "execution.order_preview", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionOrderPlace, "TradingService", "/api/v1/execution/orders", "/workspace?surface=order", "execution.order_place", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionOrderCancel, "TradingService", "/api/v1/execution/orders/{internalOrderId}/cancel", "/workspace?surface=order", "execution.order_cancel", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionComboPreview, "ComboTradingService", "/api/v1/execution/combos/previews", "/workspace?tab=options", "execution.combo_preview", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionComboPlace, "ComboTradingService", "/api/v1/execution/combos", "/workspace?tab=options", "execution.combo_place", "TestCapabilityCatalog"),
		catalogTrade(FeatureExecutionComboCancel, "ComboTradingService", "/api/v1/execution/combos/{internalOrderId}/cancel", "/workspace?tab=options", "execution.combo_cancel", "TestCapabilityCatalog"),
		catalogRead(FeatureExecutionBuyingPower, "ProductRuleProvider", "/api/v1/execution/buying-power", "/workspace?surface=order", "execution.buying_power", "TestCapabilityCatalog"),
		catalogRead(FeaturePriceAlertList, "CustomizationService", "/api/v1/alerts/price", "", "alerts.price.list", "TestCapabilityCatalog"),
		catalogWrite(FeaturePriceAlertSet, "CustomizationService", "/api/v1/alerts/price", "", "alerts.price.set", "TestCapabilityCatalog"),
		catalogRead(FeatureOptionEventAlertList, "CustomizationService", "/api/v1/alerts/option-events", "/workspace?tab=options", "alerts.option_event.list", "TestCapabilityCatalog"),
		catalogWrite(FeatureOptionEventAlertSet, "CustomizationService", "/api/v1/alerts/option-events", "/workspace?tab=options", "alerts.option_event.set", "TestCapabilityCatalog"),
		catalogRead(FeatureRemoteWatchlistList, "CustomizationService", "/api/v1/watchlists/remote", "/watchlist", "watchlist.remote.list", "TestCapabilityCatalog"),
		catalogWrite(FeatureRemoteWatchlistModify, "CustomizationService", "/api/v1/watchlists/remote", "/watchlist", "watchlist.remote.modify", "TestCapabilityCatalog"),
	},
}
