<script setup lang="ts">
import { provide } from "vue";

import {
  adkChatComposerContextKey,
  useADKChatComposer,
  type ADKChatComposerEmit,
  type ADKChatComposerProps,
} from "@/composables/adk/useADKChatComposer";
import ADKComposerControls from "./ADKComposerControls.vue";
import ADKComposerGoalEditor from "./ADKComposerGoalEditor.vue";
import ADKComposerInput from "./ADKComposerInput.vue";
import ADKComposerMobileSummary from "./ADKComposerMobileSummary.vue";
import ADKComposerQueue from "./ADKComposerQueue.vue";

const props = withDefaults(defineProps<ADKChatComposerProps>(), {
  layout: "desktop",
  activeRunId: "",
  activeRunStatus: "",
  agentOptions: () => [],
  canInterruptChat: false,
  composerBlockMessage: "",
  contextBusy: false,
  contextDetailsOpen: false,
  contextSnapshot: null,
  goalObjectiveDraft: "",
  goalObjectiveError: "",
  goalObjectiveSaving: false,
  goalLifecycleBusy: false,
  goalPaused: false,
  goalTimedOut: false,
  goalPauseRequested: false,
  showGoalObjectiveEditor: false,
  canSaveGoalObjective: false,
  canPauseGoal: false,
  canResumeGoal: false,
  hasBlockingRun: false,
  interruptingRunId: "",
  loading: false,
  placeholder: "输入问题或任务...",
  providerOptions: () => [],
  queuedMessages: () => [],
  queueDispatchingId: "",
  savingProviderSelection: false,
  selectedAgent: null,
  selectedAgentId: "",
  selectedSessionId: "",
  selectedProvider: null,
  selectedProviderId: "",
  slashCommands: () => [],
  suggestions: () => [],
  defaultWorkMode: "chat",
  defaultPermissionMode: "approval",
  permissionModeOverride: "",
  workModeOverride: "",
});
const emit = defineEmits<ADKChatComposerEmit>();

const composer = useADKChatComposer(props, emit);
provide(adkChatComposerContextKey, composer);

const {
  layout,
  activeRunId,
  activeRunStatus,
  agentOptions,
  canInterruptChat,
  canSendChat,
  chatDraft,
  composerBlockMessage,
  contextBusy,
  contextDetailsOpen,
  contextSnapshot,
  goalObjectiveDraft,
  goalObjectiveError,
  goalObjectiveSaving,
  goalLifecycleBusy,
  goalPaused,
  goalTimedOut,
  goalPauseRequested,
  showGoalObjectiveEditor,
  canSaveGoalObjective,
  canPauseGoal,
  canResumeGoal,
  hasBlockingRun,
  interruptingRunId,
  loading,
  placeholder,
  providerOptions,
  queuedMessages,
  queueDispatchingId,
  revokeQueuedMessage,
  savingProviderSelection,
  selectedAgent,
  selectedAgentId,
  selectedSessionId,
  selectedProvider,
  selectedProviderId,
  sendingChat,
  slashCommands,
  suggestions,
  defaultWorkMode,
  defaultPermissionMode,
  permissionModeOverride,
  workModeOverride,
  cancelActiveRun,
  handleAgentChange,
  handleComposerKeydown,
  handleProviderChange,
  interruptAndQueueChat,
  openContextDetails,
  openProviderSettings,
  runSlashCommand,
  sendChat,
  applySuggestion,
  cancelGoalObjective,
  pauseGoalRun,
  resumeGoalRun,
  updateGoalObjective,
  updateGoalObjectiveDraft,
  mobileControlsExpanded,
  selectedSlashIndex,
  dismissedSlashDraft,
  goalEditorExpanded,
  isMobileLayout,
  supportedWorkModes,
  normalizedDefaultWorkMode,
  workModeOptions,
  effectiveWorkModeSelection,
  permissionModeOptions,
  normalizedDefaultPermissionMode,
  effectivePermissionMode,
  effectivePermissionOption,
  contextMenuOpen,
  slashDraft,
  filteredSlashCommands,
  showSlashMenu,
  selectedSlashCommand,
  exactSlashCommand,
  queueItems,
  goalObjectiveSummary,
  goalObjectiveStatus,
  goalObjectiveTone,
  showGoalLifecycleButton,
  goalLifecycleButtonLabel,
  goalLifecycleButtonIcon,
  goalLifecycleButtonDisabled,
  sendButtonLoading,
  showInterruptButton,
  showStopButton,
  contextTone,
  hasContextUsage,
  showContextControl,
  hasKnownContextWindow,
  contextStatusLabel,
  contextPercent,
  contextProgressValue,
  contextProgressColor,
  contextPillLabel,
  selectedAgentLabel,
  selectedProviderLabel,
  selectedProviderTitle,
  selectedWorkModeLabel,
  mobileContextSummaryLabel,
  contextSummaryPreview,
  breakdownRows,
  rawBreakdownRows,
  rawContextDiagnosticsVisible,
  updatePermissionModeSelection,
  updateWorkModeSelection,
  updateAgentSelection,
  updateProviderSelection,
  openContextPopover,
  handlePrimaryAction,
  handleCancelGoalObjective,
  handleGoalLifecycleAction,
  updateChatDraft,
  handleGoalObjectiveInput,
  executeSlashCommand,
  dismissSlashMenu,
  handleKeydown,
  formatTokenCount,
  contextWindowLabel,
  contextRevisionLabel,
  compactionModeLabel,
  queueItemBadge,
  queueItemStateClass,
  canRevokeQueueItem,
} = composer;
</script>

<template>
  <div
    class="adk-composer"
    :class="{ 'adk-composer--mobile': layout === 'mobile' }"
  >
    <div class="adk-composer-card">
      <div v-if="composerBlockMessage" class="adk-composer-block">
        <v-icon size="13">fa-solid fa-circle-exclamation</v-icon>
        <span>{{ composerBlockMessage }}</span>
      </div>

      <ADKComposerGoalEditor />
      <ADKComposerQueue />
      <ADKComposerInput />
      <ADKComposerMobileSummary />
      <ADKComposerControls />
    </div>
  </div>
</template>
