import type { StrategyVisualModelDocument } from "@/contracts";

import {
  createATRVolatilityStrategyVisualModel,
  createBollingerReversionStrategyVisualModel,
  createBreakoutStrategyVisualModel,
  createCCIReversionStrategyVisualModel,
  createCollectionStatFilterStrategyVisualModel,
  createCooldownStateStrategyVisualModel,
  createDefaultStrategyVisualModel,
  createDoubleMovingAverageStrategyVisualModel,
  createKDJReversionStrategyVisualModel,
  createBracketExitStrategyVisualModel,
  createMACDMomentumStrategyVisualModel,
  createMeanReversionStrategyVisualModel,
  createMFIReversionStrategyVisualModel,
  createMTFMomentumStrategyVisualModel,
  createParameterizedMtfTrendStrategyVisualModel,
  createPartialExitStrategyVisualModel,
  createStructuredLimitExitStrategyVisualModel,
  createTimeSessionMtfRiskStrategyVisualModel,
  createRSIReversionStrategyVisualModel,
  createSupertrendStrategyVisualModel,
  createWilliamsRReversionStrategyVisualModel,
} from "./strategyVisualBuilderModels";
import {
  buildStrategyPineFromVisualModel,
  type StrategyScriptContext,
} from "./strategyVisualBuilderPine";

export interface StrategyAuthoringTemplate {
  id: string;
  label: string;
  description: string;
  mode: "visual" | "code";
  defaultId: string;
  defaultName: string;
  defaultVersion: string;
  defaultDescription: string;
  defaultSymbol: string;
  defaultInterval: string;
  visualModel: StrategyVisualModelDocument;
  syncVisualToCode: boolean;
  buildScript: (context: StrategyScriptContext) => string;
}

export function getStrategyAuthoringTemplates(): StrategyAuthoringTemplate[] {
  return [
    {
      id: "logic-flow-starter",
      label: "逻辑流起步骨架",
      description: "给一份可视化起步图，适合从拖拽块开始搭策略。",
      mode: "visual",
      defaultId: "dsl-logic-flow-starter",
      defaultName: "逻辑流起步骨架",
      defaultVersion: "0.1.0",
      defaultDescription: "用流程图拖拽块，快速搭一个可保存的 Pine 策略骨架。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createDefaultStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createDefaultStrategyVisualModel(), context),
    },
    {
      id: "double-moving-average",
      label: "双均线系统",
      description: "经典快慢均线交叉模板，图和代码都使用同一套金叉/死叉流程。",
      mode: "visual",
      defaultId: "dsl-double-moving-average",
      defaultName: "双均线系统",
      defaultVersion: "0.1.0",
      defaultDescription: "双均线交叉示例，使用 5/20 周期均线，金叉买入、死叉卖出，含持仓与重复买入检查。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createDoubleMovingAverageStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createDoubleMovingAverageStrategyVisualModel(), context),
    },
    {
      id: "rsi-reversion",
      label: "RSI 反转交易",
      description: "RSI 超买超卖模板，超卖买入、超买卖出，含持仓与重复买入检查。",
      mode: "visual",
      defaultId: "dsl-rsi-reversion",
      defaultName: "RSI 反转交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 RSI 14 在超卖区间买入、超买区间卖出，自动管理持仓。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createRSIReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createRSIReversionStrategyVisualModel(), context),
    },
    {
      id: "macd-momentum",
      label: "MACD 动能交易",
      description: "MACD 动能模板，多头买入、空头卖出，含持仓与重复买入检查。",
      mode: "visual",
      defaultId: "dsl-macd-momentum",
      defaultName: "MACD 动能交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 MACD 12/26/9 金叉买入、死叉卖出，自动管理持仓。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createMACDMomentumStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createMACDMomentumStrategyVisualModel(), context),
    },
    {
      id: "kdj-reversion",
      label: "KDJ 交叉交易",
      description: "KDJ 金叉/死叉模板，适合短周期动量反转。",
      mode: "visual",
      defaultId: "dsl-kdj-reversion",
      defaultName: "KDJ 交叉交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 KDJ 9/3/3 金叉买入、死叉卖出，自动管理持仓。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createKDJReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createKDJReversionStrategyVisualModel(), context),
    },
    {
      id: "bollinger-reversion",
      label: "布林带回归交易",
      description: "布林带模板，下轨买入、上轨卖出，含持仓与重复买入检查。",
      mode: "visual",
      defaultId: "dsl-bollinger-reversion",
      defaultName: "布林带回归交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过布林带 20x2 在下轨买入、上轨卖出，自动管理持仓。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createBollingerReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createBollingerReversionStrategyVisualModel(), context),
    },
    {
      id: "atr-volatility",
      label: "ATR 波动率过滤",
      description: "ATR 高低阈值模板，适合作为波动率开关或风险过滤。",
      mode: "visual",
      defaultId: "dsl-atr-volatility",
      defaultName: "ATR 波动率过滤",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 ATR 14 判断波动率状态，波动升高买入、回落卖出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createATRVolatilityStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createATRVolatilityStrategyVisualModel(), context),
    },
    {
      id: "cci-reversion",
      label: "CCI 反转交易",
      description: "CCI 超买超卖模板，适合顺势回撤与区间反转。",
      mode: "visual",
      defaultId: "dsl-cci-reversion",
      defaultName: "CCI 反转交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 CCI 20 在低于 -100 买入、高于 100 卖出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createCCIReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createCCIReversionStrategyVisualModel(), context),
    },
    {
      id: "williamsr-reversion",
      label: "Williams %R 反转交易",
      description: "Williams %R 超买超卖模板，适合高频回归场景。",
      mode: "visual",
      defaultId: "dsl-williamsr-reversion",
      defaultName: "Williams %R 反转交易",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 Williams %R 14 在超卖区买入、超买区卖出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createWilliamsRReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createWilliamsRReversionStrategyVisualModel(), context),
    },
    {
      id: "mfi-reversion",
      label: "MFI 资金流反转",
      description: "MFI 超买超卖模板，使用已支持的 hlc3 + volume 资金流指标和 1柱止损。",
      mode: "visual",
      defaultId: "dsl-mfi-reversion",
      defaultName: "MFI 资金流反转",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 MFI 14 在资金流超卖区买入、超买区卖出，并使用 1柱连续风控退出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createMFIReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createMFIReversionStrategyVisualModel(), context),
    },
    {
      id: "mtf-momentum",
      label: "MTF 动能确认",
      description: "日线 EMA 作为高周期变量，短周期 MACD 金叉触发下单，覆盖 request.security 图块路径。",
      mode: "visual",
      defaultId: "dsl-mtf-momentum",
      defaultName: "MTF 动能确认",
      defaultVersion: "0.1.0",
      defaultDescription: "生成日线 EMA 与当前周期 MACD，使用 MACD 金叉作为动能确认信号。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createMTFMomentumStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createMTFMomentumStrategyVisualModel(), context),
    },
    {
      id: "supertrend-follow",
      label: "Supertrend 趋势跟随",
      description: "Supertrend 方向模板，方向转多买入、转空卖出，附带 supported 1柱止损。",
      mode: "visual",
      defaultId: "dsl-supertrend-follow",
      defaultName: "Supertrend 趋势跟随",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 Supertrend 3/10 的方向字段判断趋势，并使用 1柱连续风控退出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createSupertrendStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createSupertrendStrategyVisualModel(), context),
    },
    {
      id: "parameterized-mtf-trend",
      label: "参数化 MTF 趋势",
      description: "用 input 参数驱动日线 EMA，并把高周期序列和交叉信号保留为可编辑图块。",
      mode: "visual",
      defaultId: "dsl-parameterized-mtf-trend",
      defaultName: "参数化 MTF 趋势",
      defaultVersion: "0.1.0",
      defaultDescription: "通过 trend_len 参数生成日线 MTF EMA，当前周期上穿时按权益百分比开仓。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createParameterizedMtfTrendStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createParameterizedMtfTrendStrategyVisualModel(), context),
    },
    {
      id: "cooldown-state-trade",
      label: "冷却状态交易",
      description: "展示 var 标量状态与 := 更新路径，用冷却计数管理交易节奏。",
      mode: "visual",
      defaultId: "dsl-cooldown-state-trade",
      defaultName: "冷却状态交易",
      defaultVersion: "0.1.0",
      defaultDescription: "使用 cooldown 状态变量做简单冷却计数，突破后开仓并重置冷却值。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createCooldownStateStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createCooldownStateStrategyVisualModel(), context),
    },
    {
      id: "partial-exit-risk",
      label: "部分止盈止损",
      description: "突破开仓后使用 bracket exit 的 qty_percent 做部分退出。",
      mode: "visual",
      defaultId: "dsl-partial-exit-risk",
      defaultName: "部分止盈止损",
      defaultVersion: "0.1.0",
      defaultDescription: "收盘价突破后开多，并用 50% qty_percent 的 bracket exit 做部分止盈止损。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createPartialExitStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createPartialExitStrategyVisualModel(), context),
    },
    {
      id: "collection-stat-filter",
      label: "集合统计过滤",
      description: "展示只读 array.from 统计图块，并把统计结果作为派生序列输入。",
      mode: "visual",
      defaultId: "dsl-collection-stat-filter",
      defaultName: "集合统计过滤",
      defaultVersion: "0.1.0",
      defaultDescription: "使用 collectionStat 计算固定价格序列统计，再进入派生序列和突破过滤流程。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createCollectionStatFilterStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createCollectionStatFilterStrategyVisualModel(), context),
    },
    {
      id: "time-session-mtf-risk",
      label: "时间时段 MTF 风控",
      description: "使用 time/session 过滤、参数化 MTF 趋势和部分 bracket exit。",
      mode: "visual",
      defaultId: "dsl-time-session-mtf-risk",
      defaultName: "时间时段 MTF 风控",
      defaultVersion: "0.1.0",
      defaultDescription: "常规交易时段内用日线 EMA 趋势过滤，命中后开仓并用部分 bracket exit 管理风险。",
      defaultSymbol: "US.AAPL",
      defaultInterval: "5m",
      visualModel: createTimeSessionMtfRiskStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createTimeSessionMtfRiskStrategyVisualModel(), context),
    },
    {
      id: "structured-limit-exit",
      label: "结构化限价退出",
      description: "展示订单 limit/stop 与 bracket exit 的结构化表达式价格。",
      mode: "visual",
      defaultId: "dsl-structured-limit-exit",
      defaultName: "结构化限价退出",
      defaultVersion: "0.1.0",
      defaultDescription: "用结构化表达式生成限价/止损开仓参数，并用表达式 stop/limit 做部分退出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createStructuredLimitExitStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createStructuredLimitExitStrategyVisualModel(), context),
    },
    {
      id: "bracket-exit-risk",
      label: "Bracket Exit 风控",
      description: "突破后开多，并用同一个 strategy.exit 同时设置 stop/limit 风控。",
      mode: "visual",
      defaultId: "dsl-bracket-exit-risk",
      defaultName: "Bracket Exit 风控",
      defaultVersion: "0.1.0",
      defaultDescription: "收盘价突破后买入，使用 1柱连续止盈止损组合退出。",
      defaultSymbol: "00700",
      defaultInterval: "5m",
      visualModel: createBracketExitStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createBracketExitStrategyVisualModel(), context),
    },
    {
      id: "breakout-alert",
      label: "突破交易",
      description: "突破模板，收盘价上穿阈值后买入，含重复买入检查。",
      mode: "visual",
      defaultId: "dsl-breakout-alert",
      defaultName: "突破交易",
      defaultVersion: "0.1.0",
      defaultDescription: "收盘价突破阈值后买入，含持仓检查防止重复下单。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createBreakoutStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createBreakoutStrategyVisualModel(), context),
    },
    {
      id: "mean-reversion-alert",
      label: "均值回归交易",
      description: "均值回归模板，收盘价跌破阈值后低吸买入，含重复买入检查。",
      mode: "visual",
      defaultId: "dsl-mean-reversion-alert",
      defaultName: "均值回归交易",
      defaultVersion: "0.1.0",
      defaultDescription: "收盘价跌破阈值时低吸买入，含持仓检查防止重复下单。",
      defaultSymbol: "00700",
      defaultInterval: "1m",
      visualModel: createMeanReversionStrategyVisualModel(),
      syncVisualToCode: true,
      buildScript: (context) =>
        buildStrategyPineFromVisualModel(createMeanReversionStrategyVisualModel(), context),
    },
  ];
}
