import type { MonacoCompletionDefinition } from "./strategyMonacoIntelliSenseTypes";

export const strategyPineEditorCompletionCatalogPart2: MonacoCompletionDefinition[] = [
  {
    label: "ta.obv",
    detail: "indicator",
    documentation: "按价格 source 涨跌对 volume 做增量累计。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "065552",
    insertText: "ta.obv",
  },
  {
    label: "ta.pivothigh",
    detail: "indicator",
    documentation: "在 right bars 后确认 pivot high；确认前返回 na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065553",
    insertText: "ta.pivothigh(${1:high}, ${2:2}, ${3:2})",
  },
  {
    label: "ta.pivotlow",
    detail: "indicator",
    documentation: "在 right bars 后确认 pivot low；确认前返回 na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065554",
    insertText: "ta.pivotlow(${1:low}, ${2:2}, ${3:2})",
  },
  {
    label: "ta.kc",
    detail: "indicator tuple",
    documentation: "Keltner Channel 三元组，返回 basis/upper/lower。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "065555",
    insertText: "[${1:basis}, ${2:upper}, ${3:lower}] = ta.kc(${4:close}, ${5:20}, ${6:1.5})",
  },
  {
    label: "ta.kcw",
    detail: "indicator",
    documentation: "返回归一化 Keltner Channel 宽度。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065556",
    insertText: "ta.kcw(${1:close}, ${2:20}, ${3:1.5})",
  },
  {
    label: "ta.alma",
    detail: "indicator",
    documentation: "Arnaud Legoux Moving Average。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065557",
    insertText: "ta.alma(${1:close}, ${2:20}, ${3:0.85}, ${4:6})",
  },
  {
    label: "ta.cmo",
    detail: "indicator",
    documentation: "Chande Momentum Oscillator；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065558",
    insertText: "ta.cmo(${1:close}, ${2:14})",
  },
  {
    label: "ta.tsi",
    detail: "indicator",
    documentation: "True Strength Index；使用短/长 EMA 平滑。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065559",
    insertText: "ta.tsi(${1:close}, ${2:13}, ${3:25})",
  },
  {
    label: "ta.correlation",
    detail: "rolling statistic",
    documentation: "滚动 Pearson 相关系数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065560",
    insertText: "ta.correlation(${1:close}, ${2:high}, ${3:20})",
  },
  {
    label: "ta.dev",
    detail: "rolling statistic",
    documentation: "滚动平均绝对偏差。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065561",
    insertText: "ta.dev(${1:close}, ${2:20})",
  },
  {
    label: "ta.median",
    detail: "rolling statistic",
    documentation: "滚动中位数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065562",
    insertText: "ta.median(${1:close}, ${2:20})",
  },
  {
    label: "ta.percentile_linear_interpolation",
    detail: "rolling statistic",
    documentation: "滚动百分位线性插值，percentage 必须为 0..100。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065563",
    insertText: "ta.percentile_linear_interpolation(${1:close}, ${2:20}, ${3:50})",
  },
  {
    label: "ta.percentile_nearest_rank",
    detail: "rolling statistic",
    documentation: "滚动 nearest-rank 百分位，percentage 必须为 0..100。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065564",
    insertText: "ta.percentile_nearest_rank(${1:close}, ${2:20}, ${3:80})",
  },
  {
    label: "ta.percentrank",
    detail: "rolling statistic",
    documentation: "当前值在滚动窗口中的百分排名。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065565",
    insertText: "ta.percentrank(${1:close}, ${2:20})",
  },
  {
    label: "ta.swma",
    detail: "moving average",
    documentation: "4-bar symmetric weighted moving average。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065566",
    insertText: "ta.swma(${1:close})",
  },
  {
    label: "ta.barssince",
    detail: "stateful event",
    documentation: "首次触发前返回 na，触发 bar 返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0656",
    insertText: "ta.barssince(${1:condition})",
  },
  {
    label: "ta.valuewhen",
    detail: "stateful event",
    documentation: "返回第 occurrence 次最近触发时的 sourceExpression；occurrence 必须是非负整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0657",
    insertText: "ta.valuewhen(${1:condition}, ${2:close}, ${3:0})",
  },
  {
    label: "timestamp",
    detail: "time",
    documentation: "按当前标的交易所时区解释并返回 Unix milliseconds；支持 timestamp(year, month, day[, hour, minute])，不支持显式 timezone 参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0658",
    insertText: "timestamp(${1:2026}, ${2:1}, ${3:1}, ${4:9}, ${5:30})",
  },
  {
    label: "barstate.isconfirmed",
    detail: "bar state",
    documentation: "PineTS worker 中已确认 K 线为 true；可用于兼容 TradingView 模板过滤。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06581",
    insertText: "barstate.isconfirmed",
  },
  {
    label: "session.ismarket",
    detail: "session state",
    documentation: "当前 K 线属于 regular market session 时为 true。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06582",
    insertText: "session.ismarket",
  },
  {
    label: "dayofweek.monday",
    detail: "Pine constant",
    documentation: "TradingView dayofweek 常量；PineTS worker normalizes 为数值 2。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06583",
    insertText: "dayofweek.monday",
  },
  {
    label: "month.january",
    detail: "Pine constant",
    documentation: "TradingView month 常量；PineTS worker normalizes 为数值 1。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06584",
    insertText: "month.january",
  },
  {
    label: "color.rgb",
    detail: "color helper",
    documentation: "返回稳定颜色字符串；主要用于 input.color/视觉模板兼容。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06585",
    insertText: "color.rgb(${1:76}, ${2:175}, ${3:80})",
  },
  {
    label: "color.new",
    detail: "color helper",
    documentation: "JFTrade 当前忽略透明度并返回原颜色，用于兼容模板。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06586",
    insertText: "color.new(color.${1:green}, ${2:80})",
  },
  {
    label: "var",
    detail: "persistent variable",
    documentation: "声明跨 K 线保留的 Pine 变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "var ${1:name} = ${2:0}",
  },
  {
    label: ":=",
    detail: "reassign",
    documentation: "更新已声明变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "066",
    insertText: "${1:name} := ${2:expression}",
  },
  {
    label: "nz",
    detail: "na helper",
    documentation: "当 value 为 na 时返回 fallback，未传 fallback 时返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "067",
    insertText: "nz(${1:value}, ${2:0})",
  },
  {
    label: "history reference",
    detail: "series[n]",
    documentation: "读取前 n 根 closed bar 的序列值；支持简单 identifier/member，最大 lookback 500。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068",
    insertText: "${1:close}[${2:1}]",
  },
  {
    label: "expression function",
    detail: "UDF expression",
    documentation: "UDF 会在编译期内联；支持局部赋值和最终 if/else 返回，不支持递归、method/type。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06801",
    insertText: "${1:isBull}(${2:src}) => ${2:src} > ${2:src}[1]",
  },
  {
    label: "switch expression",
    detail: "static switch",
    documentation: "switch 作为 PineTS worker 可执行分支表达式使用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068015",
    insertText: ["${1:signal} = switch", "    ${2:condition} => ${3:value}", "    => ${4:fallback}"].join("\n"),
  },
  {
    label: "for static",
    detail: "static for unroll",
    documentation: "静态 for 会按 inclusive to 语义编译期展开；v2.4 中包含条件 break/continue 时会 fallback 到有界 runtime loop。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06802",
    insertText: ["for ${1:i} = ${2:0} to ${3:3}", "    ${4:sum} := ${4:sum} + ${5:close}[${1:i}]"].join("\n"),
  },
  {
    label: "for dynamic",
    detail: "v2.2 dynamic loop",
    documentation: "v2.2 支持动态 for、break/continue；PineTS worker 会限制嵌套深度和单 bar 最大迭代数。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068021",
    insertText: ["for ${1:i} = ${2:0} to ${3:limit}", "    ${4:total} := ${4:total} + ${1:i}"].join("\n"),
  },
  {
    label: "while",
    detail: "v2.2 bounded loop",
    documentation: "v2.2 支持 while、break/continue；请确保循环状态会在同一根 closed bar 内推进。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068022",
    insertText: ["while ${1:count} < ${2:limit}", "    ${1:count} := ${1:count} + 1"].join("\n"),
  },
  {
    label: "tuple destructure",
    detail: "v2.2 tuple",
    documentation: "v2.2 支持 2 到 8 元 tuple literal/destructure，支持 _ discard。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068023",
    insertText: "[${1:a}, ${2:b}, _, ${3:d}] = [${4:open}, ${5:high}, ${6:low}, ${7:close}]",
  },
  {
    label: "plot",
    detail: "PineTS visual output",
    documentation: "PineTS worker 会计算 plot 序列并通过 worker response 透出；交易执行仍只消费 strategy.* order intents。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0681",
    insertText: "plot(${1:close})",
  },
  {
    label: "plotshape",
    detail: "PineTS visual output",
    documentation: "PineTS 支持形状标记；JFTrade 将其归入 visual output，不参与 Go 侧下单和风控。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06811",
    insertText: "plotshape(${1:condition}, title=\"${2:Signal}\", text=\"${3:S}\")",
  },
  {
    label: "plotchar",
    detail: "PineTS visual output",
    documentation: "PineTS 支持字符标记；JFTrade 将其归入 visual output，不参与 Go 侧下单和风控。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06812",
    insertText: "plotchar(${1:condition}, title=\"${2:Signal}\", char=\"${3:*}\")",
  },
  {
    label: "label.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 drawing 对象；JFTrade worker 会按 visual output 边界透出，流程图块不把绘图对象当作交易动作。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06813",
    insertText: "label.new(bar_index, ${1:close}, \"${2:Signal}\")",
  },
  {
    label: "line.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 line drawing；JFTrade worker 会按 visual output 边界透出，交易语义仍由 strategy.* 决定。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06814",
    insertText: "line.new(bar_index[1], ${1:close[1]}, bar_index, ${2:close})",
  },
  {
    label: "box.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 box drawing；JFTrade worker 会按 visual output 边界透出，不进入订单 intent。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06815",
    insertText: "box.new(bar_index[1], ${1:high[1]}, bar_index, ${2:low})",
  },
  {
    label: "table.new",
    detail: "PineTS table output",
    documentation: "PineTS 支持 table 对象；JFTrade 将 table 归为 visual output，不作为流程图交易图块。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06816",
    insertText: "table.new(position.${1|top_right,bottom_right,top_left,bottom_left|}, ${2:2}, ${3:2})",
  },
  {
    label: "hline/fill",
    detail: "PineTS visual output",
    documentation: "PineTS 支持 hline/fill 视觉层；JFTrade 将其归为 visual output。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06817",
    insertText: ["${1:upper} = hline(${2:70})", "${3:lower} = hline(${4:30})", "fill(${1:upper}, ${3:lower})"].join("\n"),
  },
  {
    label: "alertcondition",
    detail: "PineTS alert event",
    documentation: "PineTS worker 会产出 alertcondition 事件；JFTrade 将其通过 alerts 边界透出，交易通知仍建议用 alert() 或订单 alert metadata 明确表达。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0682",
    insertText: "alertcondition(${1:condition}, \"${2:Title}\")",
  },
  {
    label: "array.new_float",
    detail: "v2.4 executable collection",
    documentation: "v2.4 支持 array constructor、from/concat/sort/sort_indices/binary_search/join/median/mode/range 和常用读写，并保留跨 K 线引用状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06831",
    insertText: "${1:arr} = array.new_float(${2:0})",
  },
  {
    label: "array.copy/slice",
    detail: "v2.3 executable collection",
    documentation: "复制并切片 array；slice 使用 [from, to) 范围，结果可继续调用 array method。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068311",
    insertText: ["${1:copyValues} = ${2:arr}.copy()", "${3:window} = ${1:copyValues}.slice(${4:0}, ${5:2})"].join("\n"),
  },
  {
    label: "array.aggregate",
    detail: "v2.4 executable collection",
    documentation: "array min/max/avg/sum/median/mode/range/includes/indexof/lastindexof 可在表达式、条件和受限 request.security 纯表达式中使用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068312",
    insertText: "${1:total} = ${2:arr}.${3|sum,avg,min,max,median,mode,range,size,last,first|}()",
  },
  {
    label: "array.from/concat/join",
    detail: "v2.4 executable collection",
    documentation: "array.from(...) 构造值列表；concat 会追加另一个 array；join 使用稳定字符串化结果。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068313",
    insertText: ["${1:values} = array.from(${2:close}, ${3:open})", "${1:values}.concat(array.from(${4:high}))", "${5:text} = ${1:values}.join(\"${6:,}\")"].join("\n"),
  },
  {
    label: "array.sort/sort_indices",
    detail: "v2.4 deterministic sort",
    documentation: "支持 number/string/bool/nil；nil 稳定放末尾。order.ascending/order.descending 表示确定性排序方向。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068314",
    insertText: ["${1:values}.sort(order.${2|ascending,descending|})", "${3:idx} = ${1:values}.sort_indices(order.${4|ascending,descending|})"].join("\n"),
  },
  {
    label: "array.binary_search",
    detail: "v2.4 executable collection",
    documentation: "在已排序 array 中查找目标值，未命中返回 -1；排序比较采用 JFTrade deterministic 规则。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068315",
    insertText: "${1:index} = ${2:values}.binary_search(${3:close})",
  },
  {
    label: "array.stats",
    detail: "v2.5 executable collection",
    documentation: "v2.5 支持 array abs、leftmost/rightmost binary search、percentrank、percentile、stdev、variance、covariance。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683151",
    insertText: "${1:value} = ${2:values}.${3|percentrank,percentile_nearest_rank,percentile_linear_interpolation,stdev,variance,covariance,abs|}(${4:50})",
  },
  {
    label: "for in array",
    detail: "v2.6 collection loop",
    documentation: "v2.6 支持 array for-in；map 请先使用 keys()/values() 得到确定性 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683152",
    insertText: ["for [${1:i}, ${2:value}] in ${3:values}", "    ${4:total} := ${4:total} + ${2:value}"].join("\n"),
  },
  {
    label: "collection history",
    detail: "v2.6 read-only snapshot",
    documentation: "v2.6 支持只读 array history snapshot，例如 arr[1].get(0)/size()/first()/last()。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683153",
    insertText: "${1:previousValue} = ${2:values}[${3:1}].${4|get,size,first,last|}(${5:0})",
  },
  {
    label: "collection history aggregate",
    detail: "v2.7 read-only aggregate",
    documentation: "v2.7 支持历史 array 上的 range/median/mode/stdev/variance 等只读 aggregate/stat snapshot。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683154",
    insertText: "${1:previousStat} = ${2:values}[${3:1}].${4|range,median,mode,stdev,variance|}()",
  },
  {
    label: "order.ascending",
    detail: "v2.4 sort constant",
    documentation: "array.sort/sort_indices 排序方向常量；同批支持 order.descending。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "068316",
    insertText: "order.ascending",
  },
  {
    label: "map.new",
    detail: "v2.4 executable collection",
    documentation: "v2.4 支持 map.new/get/put/remove/contains/size/clear/copy/keys/values；keys/values 按 key 的稳定字符串序返回 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06832",
    insertText: "${1:values} = map.new<${2:string}, ${3:float}>()",
  },
  {
    label: "map.keys/values",
    detail: "v2.4 deterministic views",
    documentation: "keys() 和 values() 返回 array，并按 key 的稳定字符串序排序，保证回测可复现。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068321",
    insertText: ["${1:keys} = ${2:values}.keys()", "${3:items} = ${2:values}.values()", "${4:copy} = ${2:values}.copy()"].join("\n"),
  },
  {
    label: "for in map keys",
    detail: "v2.7 deterministic map iteration",
    documentation: "v2.7 支持通过 map.keys()/values() 返回的确定性 array 进行 for-in。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068322",
    insertText: ["for ${1:key} in ${2:values}.keys()", "    ${3:total} := ${3:total} + ${2:values}.get(${1:key})"].join("\n"),
  },
  {
    label: "matrix.new",
    detail: "v2.3 executable collection",
    documentation: "v2.3 支持 matrix.new/get/set/rows/columns/fill/copy/reshape/add_row/add_col/remove_row/remove_col，并保留跨 K 线引用状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06833",
    insertText: "${1:grid} = matrix.new<${2:float}>(${3:1}, ${4:1})",
  },
  {
    label: "matrix.reshape",
    detail: "v2.3 executable collection",
    documentation: "matrix.reshape(rows, columns) 要求总 cell 数不变；remove_row/remove_col 返回 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068331",
    insertText: ["${1:grid}.reshape(${2:1}, ${3:4})", "${4:row} = ${1:grid}.remove_row(${5:0})"].join("\n"),
  },
  {
    label: "matrix cell",
    detail: "v2.7 matrix read/write",
    documentation: "v2.7 锁定 matrix rows/columns/get/set 组合，用于 PineTS worker 中的基础二维状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068332",
    insertText: ["${1:grid}.set(${2:0}, ${3:0}, ${4:close})", "${5:value} = ${1:grid}.get(${2:0}, ${3:0})", "${6:rows} = ${1:grid}.rows()", "${7:cols} = ${1:grid}.columns()"].join("\n"),
  },
];
