import type { MonacoCompletionDefinition } from "./strategyMonacoIntelliSenseTypes";

export const strategyPineEditorCompletionCatalogPart1: MonacoCompletionDefinition[] = [
  {
    label: "//@version=6",
    detail: "Pine version",
    documentation: "声明 Pine Script v6。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "01",
    insertText: "//@version=6",
  },
  {
    label: "strategy",
    detail: "Pine strategy declaration",
    documentation: "声明可由 JFTrade 编译的 Pine 策略；支持默认仓位、initial_capital、commission_type/value、slippage 和 process_orders_on_close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "02",
    insertText: "strategy(\"${1:策略名称}\", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=${2:10}, initial_capital=${3:100000}, commission_type=strategy.commission.percent, commission_value=${4:0.1}, slippage=${5:0}, process_orders_on_close=true)",
  },
  {
    label: "ta.ema",
    detail: "indicator",
    documentation: "EMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "03",
    insertText: "ta.ema(${1:close}, ${2:20})",
  },
  {
    label: "ta.sma",
    detail: "indicator",
    documentation: "SMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04",
    insertText: "ta.sma(${1:close}, ${2:20})",
  },
  {
    label: "input.int",
    detail: "input default",
    documentation: "读取默认整数值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "041",
    insertText: "input.int(${1:20}, \"${2:Length}\")",
  },
  {
    label: "input",
    detail: "input default",
    documentation: "读取默认值；JFTrade 不实现 TradingView 设置面板运行时覆盖。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0410",
    insertText: "input(${1:20}, \"${2:Value}\")",
  },
  {
    label: "input.float",
    detail: "input default",
    documentation: "读取默认浮点值；支持 defval= 命名参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "042",
    insertText: "input.float(defval=${1:2.0}, title=\"${2:Mult}\")",
  },
  {
    label: "input.bool",
    detail: "input default",
    documentation: "读取默认 bool 值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0421",
    insertText: "input.bool(${1:true}, \"${2:Enabled}\")",
  },
  {
    label: "input.string",
    detail: "input default",
    documentation: "读取默认字符串值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0422",
    insertText: "input.string(\"${1:value}\", \"${2:Text}\")",
  },
  {
    label: "input.source",
    detail: "input default",
    documentation: "读取默认 source；第一版请使用 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "043",
    insertText: "input.source(${1:close}, \"${2:Source}\")",
  },
  {
    label: "input.time",
    detail: "input default",
    documentation: "读取默认时间值；常配合 timestamp(...)，JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0431",
    insertText: "input.time(timestamp(${1:2026}, ${2:1}, ${3:1}), \"${4:Start}\")",
  },
  {
    label: "input.timeframe",
    detail: "input default",
    documentation: "读取默认 timeframe 字符串；可用于受支持的 request.security 周期。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04315",
    insertText: "input.timeframe(\"${1|15,30,60,240,D,W,M|}\", \"${2:Timeframe}\")",
  },
  {
    label: "input.color",
    detail: "input default",
    documentation: "读取默认颜色值；主要用于兼容 TradingView 模板和视觉参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0432",
    insertText: "input.color(color.${1|green,red,blue,orange,purple,gray,white,black|}, \"${2:Color}\")",
  },
  {
    label: "math.max",
    detail: "math",
    documentation: "取最大值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "044",
    insertText: "math.max(${1:left}, ${2:right})",
  },
  {
    label: "math.min",
    detail: "math",
    documentation: "取最小值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "045",
    insertText: "math.min(${1:left}, ${2:right})",
  },
  {
    label: "math.abs",
    detail: "math",
    documentation: "取绝对值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0451",
    insertText: "math.abs(${1:value})",
  },
  {
    label: "math.avg",
    detail: "math",
    documentation: "返回参数平均值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0452",
    insertText: "math.avg(${1:left}, ${2:right})",
  },
  {
    label: "math.round",
    detail: "math",
    documentation: "四舍五入；可选 precision。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0453",
    insertText: "math.round(${1:value})",
  },
  {
    label: "math.round_to_mintick",
    detail: "math",
    documentation: "按当前市场 tick size 四舍五入，缺省 tick 为 0.01。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0454",
    insertText: "math.round_to_mintick(${1:close})",
  },
  {
    label: "math.floor",
    detail: "math",
    documentation: "向下取整；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0455",
    insertText: "math.floor(${1:value})",
  },
  {
    label: "math.ceil",
    detail: "math",
    documentation: "向上取整；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0456",
    insertText: "math.ceil(${1:value})",
  },
  {
    label: "math.sqrt",
    detail: "math",
    documentation: "平方根；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0457",
    insertText: "math.sqrt(${1:value})",
  },
  {
    label: "math.pow",
    detail: "math",
    documentation: "幂运算；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0458",
    insertText: "math.pow(${1:base}, ${2:exponent})",
  },
  {
    label: "math.log",
    detail: "math",
    documentation: "自然对数；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0459",
    insertText: "math.log(${1:value})",
  },
  {
    label: "math.sign",
    detail: "math",
    documentation: "返回 -1、0 或 1；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0460",
    insertText: "math.sign(${1:value})",
  },
  {
    label: "ta.rsi",
    detail: "indicator",
    documentation: "RSI 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "05",
    insertText: "ta.rsi(${1:close}, ${2:14})",
  },
  {
    label: "ta.macd",
    detail: "indicator",
    documentation: "MACD 指标三元组。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06",
    insertText: "[${1:macdLine}, ${2:signalLine}, ${3:histLine}] = ta.macd(close, ${4:12}, ${5:26}, ${6:9})",
  },
  {
    label: "ta.highest",
    detail: "rolling window",
    documentation: "窗口最高值；单参数形式默认 source=high。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "061",
    insertText: "ta.highest(${1:high}, ${2:20})",
  },
  {
    label: "ta.lowest",
    detail: "rolling window",
    documentation: "窗口最低值；单参数形式默认 source=low。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "062",
    insertText: "ta.lowest(${1:low}, ${2:20})",
  },
  {
    label: "ta.roc",
    detail: "rolling window",
    documentation: "Rate of Change；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "063",
    insertText: "ta.roc(${1:close}, ${2:12})",
  },
  {
    label: "ta.sum",
    detail: "rolling window",
    documentation: "滚动求和；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0635",
    insertText: "ta.sum(${1:volume}, ${2:20})",
  },
  {
    label: "ta.rma",
    detail: "moving average",
    documentation: "Pine v6 RMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06351",
    insertText: "ta.rma(${1:close}, ${2:20})",
  },
  {
    label: "ta.wma",
    detail: "moving average",
    documentation: "Pine v6 WMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06352",
    insertText: "ta.wma(${1:close}, ${2:20})",
  },
  {
    label: "ta.hma",
    detail: "moving average",
    documentation: "Pine v6 HMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06353",
    insertText: "ta.hma(${1:close}, ${2:20})",
  },
  {
    label: "ta.vwma",
    detail: "moving average",
    documentation: "Pine v6 VWMA；使用 source 与 volume 计算成交量加权均线。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06354",
    insertText: "ta.vwma(${1:close}, ${2:20})",
  },
  {
    label: "ta.atr",
    detail: "indicator",
    documentation: "Average True Range；length 必须为静态正整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06355",
    insertText: "ta.atr(${1:14})",
  },
  {
    label: "ta.cci",
    detail: "indicator",
    documentation: "Commodity Channel Index；source-aware CCI，默认常用 hlc3。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "063555",
    insertText: "ta.cci(${1:hlc3}, ${2:20})",
  },
  {
    label: "ta.highestbars",
    detail: "rolling window",
    documentation: "返回窗口最高值相对当前 bar 的偏移。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06356",
    insertText: "ta.highestbars(${1:high}, ${2:20})",
  },
  {
    label: "ta.lowestbars",
    detail: "rolling window",
    documentation: "返回窗口最低值相对当前 bar 的偏移。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06357",
    insertText: "ta.lowestbars(${1:low}, ${2:20})",
  },
  {
    label: "ta.change",
    detail: "momentum",
    documentation: "返回 source 与 length 根前的差值；未传 length 时默认 1。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06358",
    insertText: "ta.change(${1:close}, ${2:1})",
  },
  {
    label: "ta.mom",
    detail: "momentum",
    documentation: "Momentum；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06359",
    insertText: "ta.mom(${1:close}, ${2:10})",
  },
  {
    label: "ta.range",
    detail: "rolling window",
    documentation: "窗口最高值与最低值之差。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06360",
    insertText: "ta.range(${1:close}, ${2:20})",
  },
  {
    label: "ta.mode",
    detail: "rolling window",
    documentation: "窗口众数；并列时返回较小值。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06361",
    insertText: "ta.mode(${1:close}, ${2:20})",
  },
  {
    label: "ta.rising",
    detail: "condition",
    documentation: "判断 source 是否连续上升 length 根。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06362",
    insertText: "ta.rising(${1:close}, ${2:3})",
  },
  {
    label: "ta.falling",
    detail: "condition",
    documentation: "判断 source 是否连续下降 length 根。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06363",
    insertText: "ta.falling(${1:close}, ${2:3})",
  },
  {
    label: "ta.stdev",
    detail: "rolling statistic",
    documentation: "滚动标准差；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06364",
    insertText: "ta.stdev(${1:close}, ${2:20})",
  },
  {
    label: "ta.variance",
    detail: "rolling statistic",
    documentation: "滚动方差；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06365",
    insertText: "ta.variance(${1:close}, ${2:20})",
  },
  {
    label: "ta.cum",
    detail: "stateful series",
    documentation: "从首根 bar 起累计 source。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06366",
    insertText: "ta.cum(${1:volume})",
  },
  {
    label: "ta.stoch",
    detail: "indicator",
    documentation: "Stochastic；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06367",
    insertText: "ta.stoch(${1:close}, high, low, ${2:14})",
  },
  {
    label: "ta.tr",
    detail: "indicator",
    documentation: "True Range；可传 handle_na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06368",
    insertText: "ta.tr(${1:true})",
  },
  {
    label: "ta.bb",
    detail: "indicator tuple",
    documentation: "Bollinger Bands 三元组；支持 [basis, upper, lower] = ta.bb(close, length, mult)。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "064",
    insertText: "[${1:basis}, ${2:upper}, ${3:lower}] = ta.bb(close, ${4:20}, ${5:2})",
  },
  {
    label: "ta.wpr",
    detail: "indicator",
    documentation: "Williams %R 指标。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "ta.wpr(${1:14})",
  },
  {
    label: "ta.vwap",
    detail: "indicator",
    documentation: "按交易日累计 VWAP；也支持 timeframe.change(\"D\"|\"W\"|\"M\") 的闭盘锚定重置。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0651",
    insertText: "ta.vwap(${1:hlc3})",
  },
  {
    label: "ta.bbw",
    detail: "indicator",
    documentation: "Bollinger Band Width；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06511",
    insertText: "ta.bbw(${1:close}, ${2:20}, ${3:2})",
  },
  {
    label: "ta.cog",
    detail: "indicator",
    documentation: "Center of Gravity；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06512",
    insertText: "ta.cog(${1:close}, ${2:10})",
  },
  {
    label: "ta.mfi",
    detail: "indicator",
    documentation: "Money Flow Index；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0652",
    insertText: "ta.mfi(${1:hlc3}, ${2:14})",
  },
  {
    label: "ta.dmi",
    detail: "indicator tuple",
    documentation: "DMI 三元组，返回 plusDI/minusDI/adx。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0653",
    insertText: "[${1:plusDI}, ${2:minusDI}, ${3:adx}] = ta.dmi(${4:14}, ${5:14})",
  },
  {
    label: "ta.supertrend",
    detail: "indicator tuple",
    documentation: "Supertrend 二元组，返回 line/direction。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0655",
    insertText: "[${1:st}, ${2:direction}] = ta.supertrend(${3:3}, ${4:10})",
  },
  {
    label: "ta.sar",
    detail: "indicator",
    documentation: "Parabolic SAR；生成 sar:start:increment:max requirement，支持 value/previous。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06555",
    insertText: "ta.sar(${1:0.02}, ${2:0.02}, ${3:0.2})",
  },
  {
    label: "ta.linreg",
    detail: "indicator",
    documentation: "线性回归值；offset 必须是非负静态整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065551",
    insertText: "ta.linreg(${1:close}, ${2:20}, ${3:0})",
  },
];
