import type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export const strategyDslEditorExtraLibs: MonacoExtraLibDefinition[] = [];

export const strategyDslEditorCompletions: MonacoCompletionDefinition[] = [
  {
    label: "strategy",
    detail: "DSL metadata",
    documentation: "声明策略名称。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "01",
    insertText: "strategy ${1:策略名称}",
  },
  {
    label: "on init",
    detail: "DSL lifecycle hook",
    documentation: "策略启动时执行一次。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "02",
    insertText: ["on init:", "  log \"strategy started\"", "  $0"].join("\n"),
  },
  {
    label: "on kline_close",
    detail: "DSL market data hook",
    documentation: "每根 K 线收盘后执行。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "03",
    insertText: ["on kline_close:", "  let rsi14 = rsi(14)", "  if rsi14 < 30:", "    buy shares 100 policy same_direction", "  $0"].join("\n"),
  },
  {
    label: "let ma",
    detail: "indicator binding",
    documentation: "绑定移动平均线指标。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "04",
    insertText: "let ${1:fast} = ma(${2:MA}, ${3:5})",
  },
  {
    label: "let rsi",
    detail: "indicator binding",
    documentation: "绑定 RSI 指标。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "05",
    insertText: "let ${1:rsi14} = rsi(${2:14})",
  },
  {
    label: "let macd",
    detail: "indicator binding",
    documentation: "绑定 MACD 指标。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06",
    insertText: "let ${1:signal} = macd(${2:12}, ${3:26}, ${4:9})",
  },
  {
    label: "cross_over",
    detail: "condition function",
    documentation: "判断左侧指标当前上穿右侧指标。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "07",
    insertText: "cross_over(${1:fast}, ${2:slow})",
  },
  {
    label: "cross_under",
    detail: "condition function",
    documentation: "判断左侧指标当前下穿右侧指标。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "08",
    insertText: "cross_under(${1:fast}, ${2:slow})",
  },
  {
    label: "divergence_top",
    detail: "condition function",
    documentation: "判断指标顶背离信号。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "09",
    insertText: "divergence_top(${1:signal}, ${2:5})",
  },
  {
    label: "divergence_bottom",
    detail: "condition function",
    documentation: "判断指标底背离信号。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "10",
    insertText: "divergence_bottom(${1:signal}, ${2:5})",
  },
  {
    label: "buy",
    detail: "order statement",
    documentation: "按指定数量模式买入开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "11",
    insertText: "buy ${1|shares,amount,cash_percent,margin_buying_power_percent,account_position_percent,symbol_position_percent|} ${2:100} policy ${3|same_direction,flat_only,allow|}",
  },
  {
    label: "sell",
    detail: "order statement",
    documentation: "按指定数量模式卖出平多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "12",
    insertText: "sell ${1|shares,amount,symbol_position_percent,account_position_percent|} ${2:100}",
  },
  {
    label: "short",
    detail: "order statement",
    documentation: "按指定数量模式卖出开空。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "13",
    insertText: "short ${1|shares,amount,short_selling_power_percent|} ${2:100} policy ${3|same_direction,flat_only,allow|}",
  },
  {
    label: "cover",
    detail: "order statement",
    documentation: "按指定数量模式买入平空。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "14",
    insertText: "cover ${1|shares,amount,symbol_position_percent,account_position_percent|} ${2:100}",
  },
  {
    label: "protect",
    detail: "risk statement",
    documentation: "基于预计算风险快照执行止损、止盈或追踪止损。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "15",
    insertText: "protect ${1|auto,long,short|} ${2|stopLoss,takeProfit,trailingStop|} ${3:1} ${4|minute,hour,day,week,month|} ${5:2} window ${6|continuous,session|}",
  },
  {
    label: "log",
    detail: "log statement",
    documentation: "写入策略运行日志。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "16",
    insertText: "log \"${1:message}\"",
  },
  {
    label: "notify",
    detail: "notification statement",
    documentation: "写入策略通知通道。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "17",
    insertText: "notify \"${1:message}\"",
  },
];

export const strategyDslEditorHoverItems: MonacoHoverDefinition[] = [
  {
    target: "cross_over",
    signature: "cross_over(left, right) -> bool",
    documentation: "当 left 的上一根值小于等于 right，且当前值大于 right 时返回 true。",
  },
  {
    target: "cross_under",
    signature: "cross_under(left, right) -> bool",
    documentation: "当 left 的上一根值大于等于 right，且当前值小于 right 时返回 true。",
  },
  {
    target: "divergence_top",
    signature: "divergence_top(indicatorAlias, lookback) -> bool",
    documentation: "读取 Go 侧预计算的顶背离指标信号。",
  },
  {
    target: "divergence_bottom",
    signature: "divergence_bottom(indicatorAlias, lookback) -> bool",
    documentation: "读取 Go 侧预计算的底背离指标信号。",
  },
  {
    target: "close",
    signature: "close: series number",
    documentation: "当前 K 线收盘价，跨线函数会同时使用上一根收盘价。",
  },
  {
    target: "ma",
    signature: "ma(type, period, unit?) -> indicator",
    documentation: "绑定移动平均线指标，例如 ma(MA, 5) 或 ma(EMA, 20, day)。",
  },
  {
    target: "rsi",
    signature: "rsi(period) -> indicator",
    documentation: "绑定 RSI 指标。",
  },
  {
    target: "macd",
    signature: "macd(fast, slow, signal) -> indicator",
    documentation: "绑定 MACD 指标，条件里可访问 signal.diff、signal.signal、signal.histogram。",
  },
];
