import type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export const strategyPineEditorExtraLibs: MonacoExtraLibDefinition[] = [];

export const strategyPineEditorCompletions: MonacoCompletionDefinition[] = [
  {
    label: "//@version=6",
    detail: "Pine version",
    documentation: "声明 Pine Script v6。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "01",
    insertText: "//@version=6",
  },
  {
    label: "strategy",
    detail: "Pine strategy declaration",
    documentation: "声明可由 JFTrade 编译的 Pine 策略；default_qty_type/default_qty_value 会作为未写 qty 的 entry 默认仓位。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "02",
    insertText: "strategy(\"${1:策略名称}\", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=${2:10})",
  },
  {
    label: "ta.ema",
    detail: "indicator",
    documentation: "EMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "03",
    insertText: "ta.ema(${1:close}, ${2:20})",
  },
  {
    label: "ta.sma",
    detail: "indicator",
    documentation: "SMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04",
    insertText: "ta.sma(${1:close}, ${2:20})",
  },
  {
    label: "input.int",
    detail: "input default",
    documentation: "读取默认整数值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "041",
    insertText: "input.int(${1:20}, \"${2:Length}\")",
  },
  {
    label: "input.float",
    detail: "input default",
    documentation: "读取默认浮点值；支持 defval= 命名参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "042",
    insertText: "input.float(defval=${1:2.0}, title=\"${2:Mult}\")",
  },
  {
    label: "input.source",
    detail: "input default",
    documentation: "读取默认 source；第一版请使用 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "043",
    insertText: "input.source(${1:close}, \"${2:Source}\")",
  },
  {
    label: "input.time",
    detail: "input default",
    documentation: "读取默认时间值；常配合 timestamp(...)，JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0431",
    insertText: "input.time(timestamp(${1:2026}, ${2:1}, ${3:1}), \"${4:Start}\")",
  },
  {
    label: "input.timeframe",
    detail: "input default",
    documentation: "读取默认 timeframe 字符串；可用于受支持的 request.security 周期。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04315",
    insertText: "input.timeframe(\"${1|15,30,60,240,D,W,M|}\", \"${2:Timeframe}\")",
  },
  {
    label: "input.color",
    detail: "input default",
    documentation: "读取默认颜色值；主要用于兼容 TradingView 模板和视觉参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0432",
    insertText: "input.color(color.${1|green,red,blue,orange,purple,gray,white,black|}, \"${2:Color}\")",
  },
  {
    label: "math.max",
    detail: "math",
    documentation: "取最大值；math namespace 会 lower 到表达式函数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "044",
    insertText: "math.max(${1:left}, ${2:right})",
  },
  {
    label: "math.min",
    detail: "math",
    documentation: "取最小值；math namespace 会 lower 到表达式函数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "045",
    insertText: "math.min(${1:left}, ${2:right})",
  },
  {
    label: "ta.rsi",
    detail: "indicator",
    documentation: "RSI 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "05",
    insertText: "ta.rsi(${1:close}, ${2:14})",
  },
  {
    label: "ta.macd",
    detail: "indicator",
    documentation: "MACD 指标三元组。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06",
    insertText: "[${1:macdLine}, ${2:signalLine}, ${3:histLine}] = ta.macd(close, ${4:12}, ${5:26}, ${6:9})",
  },
  {
    label: "ta.highest",
    detail: "rolling window",
    documentation: "窗口最高值；单参数形式默认 source=high。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "061",
    insertText: "ta.highest(${1:high}, ${2:20})",
  },
  {
    label: "ta.lowest",
    detail: "rolling window",
    documentation: "窗口最低值；单参数形式默认 source=low。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "062",
    insertText: "ta.lowest(${1:low}, ${2:20})",
  },
  {
    label: "ta.roc",
    detail: "rolling window",
    documentation: "Rate of Change；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "063",
    insertText: "ta.roc(${1:close}, ${2:12})",
  },
  {
    label: "ta.sum",
    detail: "rolling window",
    documentation: "滚动求和；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0635",
    insertText: "ta.sum(${1:volume}, ${2:20})",
  },
  {
    label: "ta.bb",
    detail: "indicator tuple",
    documentation: "Bollinger Bands 三元组；支持 [basis, upper, lower] = ta.bb(close, length, mult)。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "064",
    insertText: "[${1:basis}, ${2:upper}, ${3:lower}] = ta.bb(close, ${4:20}, ${5:2})",
  },
  {
    label: "ta.wpr",
    detail: "indicator",
    documentation: "Williams %R 指标。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "ta.wpr(${1:14})",
  },
  {
    label: "ta.vwap",
    detail: "indicator",
    documentation: "按交易日累计 VWAP；不传 source 时默认 hlc3。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0651",
    insertText: "ta.vwap(${1:hlc3})",
  },
  {
    label: "ta.mfi",
    detail: "indicator",
    documentation: "Money Flow Index；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0652",
    insertText: "ta.mfi(${1:hlc3}, ${2:14})",
  },
  {
    label: "ta.dmi",
    detail: "indicator tuple",
    documentation: "DMI 三元组，返回 plusDI/minusDI/adx。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0653",
    insertText: "[${1:plusDI}, ${2:minusDI}, ${3:adx}] = ta.dmi(${4:14}, ${5:14})",
  },
  {
    label: "ta.adx",
    detail: "indicator",
    documentation: "ADX 快捷写法，lower 到 ta.dmi(length, length).adx。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0654",
    insertText: "ta.adx(${1:14})",
  },
  {
    label: "ta.supertrend",
    detail: "indicator tuple",
    documentation: "Supertrend 二元组，返回 line/direction。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0655",
    insertText: "[${1:st}, ${2:direction}] = ta.supertrend(${3:3}, ${4:10})",
  },
  {
    label: "ta.sar",
    detail: "indicator",
    documentation: "Parabolic SAR；生成 sar:start:increment:max requirement，支持 value/previous。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06555",
    insertText: "ta.sar(${1:0.02}, ${2:0.02}, ${3:0.2})",
  },
  {
    label: "ta.barssince",
    detail: "stateful event",
    documentation: "首次触发前返回 na，触发 bar 返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0656",
    insertText: "ta.barssince(${1:condition})",
  },
  {
    label: "ta.valuewhen",
    detail: "stateful event",
    documentation: "返回第 occurrence 次最近触发时的 sourceExpression；occurrence 必须是非负整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0657",
    insertText: "ta.valuewhen(${1:condition}, ${2:close}, ${3:0})",
  },
  {
    label: "timestamp",
    detail: "time",
    documentation: "返回 Unix milliseconds；支持 timestamp(year, month, day[, hour, minute])，不支持 timezone 参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0658",
    insertText: "timestamp(${1:2026}, ${2:1}, ${3:1}, ${4:9}, ${5:30})",
  },
  {
    label: "barstate.isconfirmed",
    detail: "bar state",
    documentation: "closed-bar runtime 中已确认 K 线为 true；可用于兼容 TradingView 模板过滤。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06581",
    insertText: "barstate.isconfirmed",
  },
  {
    label: "session.ismarket",
    detail: "session state",
    documentation: "当前 K 线属于 regular market session 时为 true。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06582",
    insertText: "session.ismarket",
  },
  {
    label: "dayofweek.monday",
    detail: "Pine constant",
    documentation: "TradingView dayofweek 常量；JFTrade lower 为数值 2。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06583",
    insertText: "dayofweek.monday",
  },
  {
    label: "month.january",
    detail: "Pine constant",
    documentation: "TradingView month 常量；JFTrade lower 为数值 1。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06584",
    insertText: "month.january",
  },
  {
    label: "color.rgb",
    detail: "color helper",
    documentation: "返回稳定颜色字符串；主要用于 input.color/视觉模板兼容。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06585",
    insertText: "color.rgb(${1:76}, ${2:175}, ${3:80})",
  },
  {
    label: "color.new",
    detail: "color helper",
    documentation: "JFTrade 当前忽略透明度并返回原颜色，用于兼容模板。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06586",
    insertText: "color.new(color.${1:green}, ${2:80})",
  },
  {
    label: "var",
    detail: "persistent variable",
    documentation: "声明跨 K 线保留的 Pine 变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "var ${1:name} = ${2:0}",
  },
  {
    label: ":=",
    detail: "reassign",
    documentation: "更新已声明变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "066",
    insertText: "${1:name} := ${2:expression}",
  },
  {
    label: "nz",
    detail: "na helper",
    documentation: "当 value 为 na 时返回 fallback，未传 fallback 时返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "067",
    insertText: "nz(${1:value}, ${2:0})",
  },
  {
    label: "history reference",
    detail: "series[n]",
    documentation: "读取前 n 根 closed bar 的序列值；支持简单 identifier/member，最大 lookback 500。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068",
    insertText: "${1:close}[${2:1}]",
  },
  {
    label: "expression function",
    detail: "UDF expression",
    documentation: "表达式 UDF 会在编译期内联；不支持多语句函数或递归。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06801",
    insertText: "${1:isBull}(${2:src}) => ${2:src} > ${2:src}[1]",
  },
  {
    label: "for static",
    detail: "static for unroll",
    documentation: "静态 for 会按 inclusive to 语义编译期展开；边界必须是整数常量或 input.int 默认值。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06802",
    insertText: ["for ${1:i} = ${2:0} to ${3:3}", "    ${4:sum} := ${4:sum} + ${5:close}[${1:i}]"].join("\n"),
  },
  {
    label: "plot",
    detail: "visual no-op",
    documentation: "兼容 TradingView 模板；JFTrade 会作为 warning no-op 忽略，不影响交易。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0681",
    insertText: "plot(${1:close})",
  },
  {
    label: "alertcondition",
    detail: "alert declaration no-op",
    documentation: "兼容 TradingView 模板；JFTrade 不触发通知，只作为 warning no-op 忽略。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0682",
    insertText: "alertcondition(${1:condition}, \"${2:Title}\")",
  },
  {
    label: "ternary",
    detail: "conditional expression",
    documentation: "基础条件表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "069",
    insertText: "${1:condition} ? ${2:trueValue} : ${3:falseValue}",
  },
  {
    label: "ta.crossover",
    detail: "condition",
    documentation: "判断左侧序列上穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "07",
    insertText: "ta.crossover(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.crossunder",
    detail: "condition",
    documentation: "判断左侧序列下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "08",
    insertText: "ta.crossunder(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.cross",
    detail: "condition",
    documentation: "判断左侧序列上穿或下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "081",
    insertText: "ta.cross(${1:fast}, ${2:slow})",
  },
  {
    label: "if crossover entry",
    detail: "strategy pattern",
    documentation: "均线上穿后开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "09",
    insertText: [
      "if ta.crossover(${1:fast}, ${2:slow})",
      "    strategy.entry(\"${3:Long}\", strategy.long, qty=${4:1})",
    ].join("\n"),
  },
  {
    label: "strategy.entry long",
    detail: "order",
    documentation: "开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "10",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty=${2:1})",
  },
  {
    label: "strategy.entry qty_percent",
    detail: "order",
    documentation: "按账户权益百分比开仓；JFTrade lower 为 account_position_percent。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "101",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty_percent=${2:10})",
  },
  {
    label: "strategy.entry stop",
    detail: "pending order",
    documentation: "基础 stop pending；突破 stop 价后按 closed-bar 语义触发。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "102",
    insertText: "strategy.entry(\"${1:Breakout}\", strategy.long, stop=${2:ta.highest(high, 20)}, qty=${3:1})",
  },
  {
    label: "strategy.entry short",
    detail: "order",
    documentation: "开空。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "11",
    insertText: "strategy.entry(\"${1:Short}\", strategy.short, qty=${2:1})",
  },
  {
    label: "strategy.order",
    detail: "net order",
    documentation: "提交净额买入/卖出；不受 strategy.entry pyramiding gate 限制。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "115",
    insertText: "strategy.order(\"${1:Net}\", strategy.${2|long,short|}, qty=${3:1})",
  },
  {
    label: "strategy.order stop",
    detail: "pending net order",
    documentation: "净额 stop pending；不套用 strategy.entry pyramiding gate。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "116",
    insertText: "strategy.order(\"${1:Net stop}\", strategy.${2|long,short|}, stop=${3:close}, qty=${4:1})",
  },
  {
    label: "strategy.close",
    detail: "order",
    documentation: "按 entry id 平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "12",
    insertText: "strategy.close(\"${1:Long}\")",
  },
  {
    label: "strategy.close qty_percent",
    detail: "order",
    documentation: "按当前 symbol 持仓百分比平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "121",
    insertText: "strategy.close(\"${1:Long}\", qty_percent=${2:50})",
  },
  {
    label: "strategy.close_all",
    detail: "order",
    documentation: "按当前实际持仓方向 flatten 当前策略 symbol。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "122",
    insertText: "strategy.close_all()",
  },
  {
    label: "strategy.cancel",
    detail: "pending order",
    documentation: "取消当前策略 symbol 中指定 id 的未触发 pending order。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "123",
    insertText: "strategy.cancel(\"${1:Breakout}\")",
  },
  {
    label: "strategy.cancel_all",
    detail: "pending order",
    documentation: "取消当前策略 symbol 的全部未触发 pending orders。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "124",
    insertText: "strategy.cancel_all()",
  },
  {
    label: "strategy.exit stop",
    detail: "exit",
    documentation: "基础止损；stop 可使用普通数值表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "125",
    insertText: "strategy.exit(\"${1:Long stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100))",
  },
  {
    label: "strategy.exit qty_percent",
    detail: "exit",
    documentation: "stop/limit/trailing 子集可按当前持仓百分比部分退出。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1251",
    insertText: "strategy.exit(\"${1:Half stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100), qty_percent=${4:50})",
  },
  {
    label: "strategy.exit bracket",
    detail: "exit",
    documentation: "基础 stop+limit bracket；同 bar 两侧触发时采用 stop-first。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1252",
    insertText: "strategy.exit(\"${1:Bracket}\", \"${2:Long}\", stop=${3:close * 0.98}, limit=${4:close * 1.04}, qty_percent=${5:100})",
  },
  {
    label: "request.security MTF MA",
    detail: "multi-timeframe",
    documentation: "受限多周期 source-aware 均线子集；支持 5/15/30/45/60/120/240 分钟和 D/W/M。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "126",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ta.${2|ema,sma,rma,wma,hma,vwma|}(${3|close,hlc3,hl2,ohlc4,open,high,low,volume|}, ${4:20}))",
  },
  {
    label: "request.security MTF source",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 OHLCV/hl2/hlc3/ohlc4 source。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1261",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|})",
  },
  {
    label: "request.security MTF source[1]",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 source 历史值，例如上一根日线 close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1262",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|}[${3:1}])",
  },
  {
    label: "alert",
    detail: "notification",
    documentation: "写入策略通知通道。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "13",
    insertText: "alert(\"${1:message}\")",
  },
];

export const strategyPineEditorHoverItems: MonacoHoverDefinition[] = [
  {
    target: "ta.crossover",
    signature: "ta.crossover(left, right) -> bool",
    documentation: "JFTrade 会 lower 为 cross_over(left, right)。",
  },
  {
    target: "ta.crossunder",
    signature: "ta.crossunder(left, right) -> bool",
    documentation: "JFTrade 会 lower 为 cross_under(left, right)。",
  },
  {
    target: "ta.cross",
    signature: "ta.cross(left, right) -> bool",
    documentation: "JFTrade 会 lower 为 cross_over(left, right) || cross_under(left, right)。",
  },
  {
    target: "ta.highest",
    signature: "ta.highest(source, length) / ta.highest(length)",
    documentation: "JFTrade 支持 open/high/low/close/volume/hl2/hlc3/ohlc4 source；单参数 highest(length) 默认 high。",
  },
  {
    target: "ta.lowest",
    signature: "ta.lowest(source, length) / ta.lowest(length)",
    documentation: "JFTrade 支持 open/high/low/close/volume/hl2/hlc3/ohlc4 source；单参数 lowest(length) 默认 low。",
  },
  {
    target: "ta.bb",
    signature: "[basis, upper, lower] = ta.bb(close, length, mult)",
    documentation: "JFTrade 会 lower 到 Bollinger 指标绑定。",
  },
  {
    target: "ta.wpr",
    signature: "ta.wpr(length)",
    documentation: "JFTrade 会 lower 到 Williams %R 指标。",
  },
  {
    target: "ta.sum",
    signature: "ta.sum(source, length)",
    documentation: "滚动窗口求和；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "hlc3",
    signature: "hlc3",
    documentation: "派生价格源 (high + low + close) / 3；同批支持 hl2 和 ohlc4。",
  },
  {
    target: "series[n]",
    signature: "identifier[n] / object.field[n]",
    documentation: "读取前 n 根 closed bar 的历史值；函数调用结果请先赋值后再使用历史引用。",
  },
  {
    target: "=>",
    signature: "name(arg1, arg2) => expression",
    documentation: "JFTrade 支持顶层表达式 UDF，编译期内联；参数数量必须匹配，不支持递归或多语句函数。",
  },
  {
    target: "for",
    signature: "for i = start to end [by step]",
    documentation: "JFTrade 支持静态整数边界循环，按 Pine inclusive to 语义最多展开 100 次；动态边界、break/continue 暂不支持。",
  },
  {
    target: "alertcondition",
    signature: "alertcondition(condition, title?, message?)",
    documentation: "JFTrade 作为非交易声明 no-op 兼容，不触发通知；需要通知请使用 alert() 或 notify()。",
  },
  {
    target: "plot",
    signature: "plot(series, ...)",
    documentation: "JFTrade 作为视觉 no-op 兼容，会产生 warning 但不进入交易 IR。",
  },
  {
    target: "ta.vwap",
    signature: "ta.vwap(source?)",
    documentation: "JFTrade 按交易日累计 VWAP；source 省略时默认 hlc3。",
  },
  {
    target: "ta.mfi",
    signature: "ta.mfi(source, length)",
    documentation: "JFTrade 支持基于 source 与 volume 的 Money Flow Index。",
  },
  {
    target: "ta.dmi",
    signature: "[plusDI, minusDI, adx] = ta.dmi(diLength, adxSmoothing)",
    documentation: "JFTrade 支持 DMI tuple assignment；字段包括 plus、minus、adx。",
  },
  {
    target: "ta.adx",
    signature: "ta.adx(length)",
    documentation: "JFTrade lower 为 dmi(length, length).adx。",
  },
  {
    target: "ta.supertrend",
    signature: "[line, direction] = ta.supertrend(factor, atrPeriod)",
    documentation: "JFTrade 支持 Supertrend line/direction tuple assignment。",
  },
  {
    target: "ta.sar",
    signature: "ta.sar(start, increment, max)",
    documentation: "JFTrade 支持 Parabolic SAR，planner requirement key 形如 sar:0.02:0.02:0.2。",
  },
  {
    target: "ta.barssince",
    signature: "ta.barssince(condition)",
    documentation: "首次触发前返回 na，当前 bar 触发返回 0。",
  },
  {
    target: "ta.valuewhen",
    signature: "ta.valuewhen(condition, sourceExpression, occurrence)",
    documentation: "occurrence 必须为非负整数；同一 bar 多次读取不会重复推进状态。",
  },
  {
    target: "timestamp",
    signature: "timestamp(year, month, day[, hour, minute])",
    documentation: "返回 Unix milliseconds；第一版不支持 timezone 参数。",
  },
  {
    target: "input.time",
    signature: "input.time(defval, title?)",
    documentation: "JFTrade 只取默认时间值；常用 defval 可写 timestamp(year, month, day[, hour, minute])。",
  },
  {
    target: "input.timeframe",
    signature: "input.timeframe(defval, title?)",
    documentation: "JFTrade 只取默认 timeframe 字符串；支持 1/5/15/30/45/60/120/240/D/W/M 的 request.security 子集。",
  },
  {
    target: "input.color",
    signature: "input.color(defval, title?)",
    documentation: "JFTrade 只取默认颜色值；颜色主要用于兼容 Pine 模板，不参与交易数值语义。",
  },
  {
    target: "barstate.isconfirmed",
    signature: "barstate.isconfirmed",
    documentation: "closed-bar runtime 中当前已知 K 线执行时为 true；同批支持 isfirst/isnew/ishistory/isrealtime/islast。",
  },
  {
    target: "session.ismarket",
    signature: "session.ismarket",
    documentation: "当前 K 线属于 regular session 时为 true；同批支持 ispremarket/ispostmarket。",
  },
  {
    target: "dayofweek.monday",
    signature: "dayofweek.monday",
    documentation: "JFTrade 将 dayofweek.sunday...saturday lower 为 1...7。",
  },
  {
    target: "month.january",
    signature: "month.january",
    documentation: "JFTrade 将 month.january...december lower 为 1...12。",
  },
  {
    target: "color.rgb",
    signature: "color.rgb(r, g, b)",
    documentation: "JFTrade lower 为稳定十六进制颜色字符串。",
  },
  {
    target: "color.new",
    signature: "color.new(color, transp)",
    documentation: "JFTrade 当前忽略 transp 并返回原颜色，用于兼容常见 Pine 模板。",
  },
  {
    target: "input.int",
    signature: "input.int(defval, title?)",
    documentation: "JFTrade 取默认值并作为常量执行，不提供 TradingView 设置面板运行时覆盖。",
  },
  {
    target: "input.source",
    signature: "input.source(defval, title?)",
    documentation: "JFTrade 取默认 OHLCV source；后续 ta.sma(src, n) 会按 source-aware MA lower。",
  },
  {
    target: "math.max",
    signature: "math.max(a, b, ...)",
    documentation: "JFTrade 支持 math.abs/min/max/round/floor/ceil/sqrt/pow/log/sign。",
  },
  {
    target: "bar_index",
    signature: "bar_index",
    documentation: "当前策略收到的 K 线序号，从 0 开始。",
  },
  {
    target: "time",
    signature: "time",
    documentation: "当前 K 线时间，Unix milliseconds；同时支持 hour/minute/dayofweek/dayofmonth/month/year。",
  },
  {
    target: "strategy.entry",
    signature: "strategy.entry(id, direction, qty?)",
    documentation: "显式 qty/qty_percent 优先；未写 qty 时继承 strategy(...) 的 default_qty_type/default_qty_value。",
  },
  {
    target: "strategy.order",
    signature: "strategy.order(id, direction, qty?, qty_percent?, limit?)",
    documentation: "JFTrade 将其作为净额订单执行，不套用 strategy.entry 的 pyramiding gate；stop/OCA 暂不支持。",
  },
  {
    target: "strategy.close",
    signature: "strategy.close(id, qty?, qty_percent?)",
    documentation: "映射为 JFTrade 平仓；qty_percent 表示当前 symbol 持仓百分比。",
  },
  {
    target: "strategy.close_all",
    signature: "strategy.close_all()",
    documentation: "按当前实际持仓方向 flatten 当前策略 symbol。",
  },
  {
    target: "var",
    signature: "var name = expression",
    documentation: "声明跨 K 线保留的变量；当前 JFTrade runtime 会保存当前值和上一值。",
  },
  {
    target: "nz",
    signature: "nz(value, fallback?)",
    documentation: "value 为 na 时返回 fallback；未传 fallback 时返回 0。",
  },
  {
    target: "na",
    signature: "na",
    documentation: "空值常量，可用于比较或配合 nz。",
  },
  {
    target: "request.security",
    signature: "request.security(syminfo.tickerid, timeframe, source | source[n] | ta.*(source, n))",
    documentation: "JFTrade 支持同标的 1/5/15/30/45/60/120/240/D/W/M，source/source[n] 和 source-aware 均线子集；lookahead_on/gaps_on、多标的和任意表达式会被明确诊断。",
  },
  {
    target: "strategy.exit",
    signature: "strategy.exit(id, from_entry, stop/limit/trail_points/trail_offset, qty?, qty_percent?)",
    documentation: "支持基础止损、止盈、stop+limit bracket、追踪止损和部分退出；OCA、partial fill 和 intrabar broker emulator 语义不会静默执行。",
  },
  {
    target: "strategy.cancel",
    signature: "strategy.cancel(id)",
    documentation: "取消当前策略 symbol 中指定 id 的未触发 pending order；不存在的 id 会跳过。",
  },
  {
    target: "strategy.cancel_all",
    signature: "strategy.cancel_all()",
    documentation: "取消当前策略 symbol 的全部未触发 pending orders。",
  },
];
