import type { MonacoCompletionDefinition } from "./strategyMonacoIntelliSenseTypes";

export const strategyPineEditorCompletionCatalogPart3: MonacoCompletionDefinition[] = [
  {
    label: "type",
    detail: "v2.4 pure UDT subset",
    documentation: "v2.4 支持纯 UDT constructor、字段默认值、命名 constructor 参数、局部和 var object 字段重赋值；library/import 和完整 Pine type 系统仍只做诊断。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06834",
    insertText: ["type ${1:TradeBox}", "    ${2:float} ${3:price}"].join("\n"),
  },
  {
    label: "method",
    detail: "v2.4 pure method subset",
    documentation: "v2.4 支持单表达式和受控多语句纯 method、默认值与命名参数；表达式 method 可在受限 MTF pure expression 内调用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06835",
    insertText: "method ${1:score}(${2:TradeBox} ${3:self}, ${4:float} ${5:factor} = ${6:1}) => ${3:self}.${7:price} * ${5:factor}",
  },
  {
    label: "method block",
    detail: "v2.4 pure method subset",
    documentation: "多语句纯 method 会在 PineTS worker 中执行；receiver 字段可读，method 内不执行订单、绘图或 collection 副作用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068351",
    insertText: ["method ${1:score}(${2:TradeBox} ${3:self}, ${4:float} ${5:factor} = ${6:1}) =>", "    ${7:base} = ${3:self}.${8:price} * ${5:factor}", "    ${7:base}"].join("\n"),
  },
  {
    label: "object field set",
    detail: "v2.4 persistent object",
    documentation: "object 字段可用 := 重赋值；var object 字段值会随变量跨 K 线持久化。method 内副作用和跨 library method 仍不执行。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068352",
    insertText: "${1:box}.${2:price} := ${3:close}",
  },
  {
    label: "object collection field",
    detail: "v2.6 UDT collection field",
    documentation: "v2.6 支持 UDT 字段持有 collection 引用，并执行 box.values.push(close) 等字段 collection method。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068353",
    insertText: ["type ${1:Box}", "    array<float> ${2:values}", "${3:box} = ${1:Box}.new(array.new_float())", "${3:box}.${2:values}.push(${4:close})"].join("\n"),
  },
  {
    label: "object history",
    detail: "v2.8 object snapshot",
    documentation: "v2.8 支持 object 历史字段读取，例如 box[1].price；历史对象仍为只读 snapshot。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683531",
    insertText: "${1:previousPrice} = ${2:box}[${3:1}].${4:price}",
  },
  {
    label: "method chain",
    detail: "v2.8 pure method chain",
    documentation: "v2.8 支持无副作用 method chain，例如 box.identity().score(2)，不执行 method 内副作用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683532",
    insertText: "${1:value} = ${2:box}.${3:identity}().${4:score}(${5:2})",
  },
  {
    label: "object history method",
    detail: "v2.9 object snapshot method",
    documentation: "v2.9 支持历史 object snapshot 作为纯 method receiver，例如 box[1].score(factor=2)。历史对象仍为只读。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683533",
    insertText: "${1:previousScore} = ${2:box}[${3:1}].${4:score}(${5:factor=2})",
  },
  {
    label: "request.security object history",
    detail: "v2.9 MTF pure object history",
    documentation: "v2.9 支持同标的静态 timeframe 下的纯 object history field/method 表达式；动态 symbol/timeframe、nested request 和副作用会分码诊断。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683534",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ${2:box}[${3:1}].${4:price})",
  },
  {
    label: "varip",
    detail: "PineTS worker varip compatibility",
    documentation: "v3.0 中 varip 在 PineTS worker 下按 var 语义执行，并输出兼容性 warning。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683535",
    insertText: "varip ${1:state} = ${2:0}",
  },
  {
    label: "str helpers",
    detail: "v2.5 string helpers",
    documentation: "v2.5 支持 str.length/contains/pos/substring/replace/upper/lower/format 纯表达式 helper。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068354",
    insertText: "${1:text} = str.${2|format,upper,lower,length,contains,pos,substring,replace|}(${3:\"value\"})",
  },
  {
    label: "str.length",
    detail: "string helper",
    documentation: "返回字符串长度。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683541",
    insertText: "str.length(${1:text})",
  },
  {
    label: "str.tostring",
    detail: "string helper",
    documentation: "把值转换为字符串；可选 format。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06835415",
    insertText: "str.tostring(${1:value})",
  },
  {
    label: "str.contains",
    detail: "string helper",
    documentation: "判断 source 是否包含 needle。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683542",
    insertText: "str.contains(${1:text}, ${2:\"needle\"})",
  },
  {
    label: "str.pos",
    detail: "string helper",
    documentation: "返回 needle 在 source 中的位置，未找到时返回 -1。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683543",
    insertText: "str.pos(${1:text}, ${2:\"needle\"})",
  },
  {
    label: "str.substring",
    detail: "string helper",
    documentation: "返回字符串子串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683544",
    insertText: "str.substring(${1:text}, ${2:0}, ${3:3})",
  },
  {
    label: "str.replace",
    detail: "string helper",
    documentation: "替换 source 中的 target。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683545",
    insertText: "str.replace(${1:text}, ${2:\"target\"}, ${3:\"replacement\"})",
  },
  {
    label: "str.upper",
    detail: "string helper",
    documentation: "返回大写字符串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683546",
    insertText: "str.upper(${1:text})",
  },
  {
    label: "str.lower",
    detail: "string helper",
    documentation: "返回小写字符串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683547",
    insertText: "str.lower(${1:text})",
  },
  {
    label: "str.format",
    detail: "string helper",
    documentation: "使用 {0}/{1} 占位替换参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683548",
    insertText: "str.format(\"${1:{0}}\", ${2:value})",
  },
  {
    label: "timeframe.change",
    detail: "v2.5 timeframe helper",
    documentation: "v2.5 支持静态 timeframe.change，用于 K 线周期边界判断；同批支持 time_close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068355",
    insertText: "timeframe.change(\"${1:15}\")",
  },
  {
    label: "timeframe.in_seconds",
    detail: "v2.7 timeframe helper",
    documentation: "v2.7 支持 timeframe.in_seconds(timeframe?)、timeframe.multiplier 与 timeframe.isseconds。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683551",
    insertText: "timeframe.in_seconds(\"${1:15}\")",
  },
  {
    label: "import",
    detail: "v2 parse-only declaration",
    documentation: "v2.0 语言底座：import 会进入 semantic declarations 与 alias 诊断；当前不会加载 TradingView library。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06836",
    insertText: "import ${1:TradingView/ta/7}",
  },
  {
    label: "library",
    detail: "v2 parse-only declaration",
    documentation: "v2.0 语言底座：library(...) 会进入 semantic declarations；JFTrade 策略运行仍要求 strategy(...) 主入口。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06837",
    insertText: "library(\"${1:LibraryName}\")",
  },
  {
    label: "export",
    detail: "v2.8 semantic metadata",
    documentation: "v2.8 会为 export function/type/method 标记 exportedKind metadata；不会加载或执行跨 library 代码。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068362",
    insertText: "export ${1:helper}(${2:float src}) => ${3:src}",
  },
  {
    label: "ternary",
    detail: "conditional expression",
    documentation: "基础条件表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "069",
    insertText: "${1:condition} ? ${2:trueValue} : ${3:falseValue}",
  },
  {
    label: "ta.crossover",
    detail: "condition",
    documentation: "判断左侧序列上穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "07",
    insertText: "ta.crossover(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.crossunder",
    detail: "condition",
    documentation: "判断左侧序列下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "08",
    insertText: "ta.crossunder(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.cross",
    detail: "condition",
    documentation: "判断左侧序列上穿或下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "081",
    insertText: "ta.cross(${1:fast}, ${2:slow})",
  },
  {
    label: "if crossover entry",
    detail: "strategy pattern",
    documentation: "均线上穿后开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "09",
    insertText: [
      "if ta.crossover(${1:fast}, ${2:slow})",
      "    strategy.entry(\"${3:Long}\", strategy.long, qty=${4:1})",
    ].join("\n"),
  },
  {
    label: "strategy.entry long",
    detail: "order",
    documentation: "开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "10",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty=${2:1})",
  },
  {
    label: "strategy.entry qty_percent",
    detail: "order",
    documentation: "按账户权益百分比开仓；PineTS worker normalizes 为 account_position_percent。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "101",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty_percent=${2:10})",
  },
  {
    label: "strategy.entry stop",
    detail: "pending order",
    documentation: "基础 stop pending；突破 stop 价后按 PineTS worker + Go 订单链路触发。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "102",
    insertText: "strategy.entry(\"${1:Breakout}\", strategy.long, stop=${2:ta.highest(high, 20)}, qty=${3:1})",
  },
  {
    label: "strategy.entry short",
    detail: "order",
    documentation: "开空。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "11",
    insertText: "strategy.entry(\"${1:Short}\", strategy.short, qty=${2:1})",
  },
  {
    label: "strategy.order",
    detail: "net order",
    documentation: "提交净额买入/卖出；不受 strategy.entry pyramiding gate 限制。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "115",
    insertText: "strategy.order(\"${1:Net}\", strategy.${2|long,short|}, qty=${3:1})",
  },
  {
    label: "strategy.order stop",
    detail: "pending net order",
    documentation: "净额 stop pending；不套用 strategy.entry pyramiding gate。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "116",
    insertText: "strategy.order(\"${1:Net stop}\", strategy.${2|long,short|}, stop=${3:close}, qty=${4:1})",
  },
  {
    label: "strategy.close",
    detail: "order",
    documentation: "按 entry id 平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "12",
    insertText: "strategy.close(\"${1:Long}\")",
  },
  {
    label: "strategy.close qty_percent",
    detail: "order",
    documentation: "按当前 symbol 持仓百分比平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "121",
    insertText: "strategy.close(\"${1:Long}\", qty_percent=${2:50})",
  },
  {
    label: "strategy.close_all",
    detail: "order",
    documentation: "按当前实际持仓方向 flatten 当前策略 symbol。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "122",
    insertText: "strategy.close_all()",
  },
  {
    label: "strategy.cancel",
    detail: "pending order",
    documentation: "取消当前策略 symbol 中指定 id 的未触发 pending order。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "123",
    insertText: "strategy.cancel(\"${1:Breakout}\")",
  },
  {
    label: "strategy.cancel_all",
    detail: "pending order",
    documentation: "取消当前策略 symbol 的全部未触发 pending orders。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "124",
    insertText: "strategy.cancel_all()",
  },
  {
    label: "strategy.exit stop",
    detail: "exit",
    documentation: "基础止损；stop 可使用普通数值表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "125",
    insertText: "strategy.exit(\"${1:Long stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100))",
  },
  {
    label: "strategy.exit qty_percent",
    detail: "exit",
    documentation: "stop/limit/trailing 子集可按当前持仓百分比部分退出。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1251",
    insertText: "strategy.exit(\"${1:Half stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100), qty_percent=${4:50})",
  },
  {
    label: "strategy.exit bracket",
    detail: "exit",
    documentation: "基础 stop+limit bracket；同 bar 两侧触发时采用 stop-first。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1252",
    insertText: "strategy.exit(\"${1:Bracket}\", \"${2:Long}\", stop=${3:close * 0.98}, limit=${4:close * 1.04}, qty_percent=${5:100})",
  },
  {
    label: "request.security MTF MA",
    detail: "multi-timeframe",
    documentation: "受限多周期 source-aware 均线与 v2.4 ta.stoch 子集；支持 5/15/30/45/60/120/240 分钟和 D/W/M。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "126",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ta.${2|ema,sma,rma,wma,hma,vwma|}(${3|close,hlc3,hl2,ohlc4,open,high,low,volume|}, ${4:20}))",
  },
  {
    label: "request.security MTF source",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 OHLCV/hl2/hlc3/ohlc4 source。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1261",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|})",
  },
  {
    label: "request.security MTF source[1]",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 source 历史值，例如上一根日线 close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1262",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|}[${3:1}])",
  },
  {
    label: "request.security MTF tuple",
    detail: "multi-timeframe tuple",
    documentation: "支持 source、source[n]、source-aware MA、v2.4 ta.stoch、纯表达式组合和 v2.2 2-8 元 tuple。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1263",
    insertText: "[${1:mtfClose}, ${2:mtfFast}] = request.security(syminfo.tickerid, \"${3:15}\", [${4:close}, ta.${5|ema,sma,rma,wma,hma,vwma|}(${6:close}, ${7:20})])",
  },
  {
    label: "request.security MTF object/collection",
    detail: "v2.4 multi-timeframe expression",
    documentation: "v2.4 支持同标的静态 timeframe 中的纯 collection read、纯 object field/method 表达式和命名/default method 参数；副作用、nested request、动态 symbol/timeframe 仍诊断失败。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1264",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ${2:box}.${3:score}(${4:2}))",
  },
  {
    label: "request.security MTF stoch",
    detail: "v2.4 multi-timeframe indicator",
    documentation: "支持同标的静态 timeframe 的 ta.stoch(source, high, low, length)，会规划带 timeframe 后缀的 stoch requirement。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1265",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ta.stoch(${2:close}, high, low, ${3:14}))",
  },
  {
    label: "ticker.heikinashi",
    detail: "extended ticker",
    documentation: "创建当前标的的 Heikin Ashi ticker；只能作为同标的 request.security 的 ticker 参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "1266",
    insertText: "ticker.heikinashi(syminfo.tickerid)",
  },
  {
    label: "ticker.standard",
    detail: "extended ticker",
    documentation: "移除当前主图的 Heikin Ashi 修饰符，以便在 HA 图上通过 request.security 读取标准 OHLC。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "1267",
    insertText: "ticker.standard()",
  },
  {
    label: "ticker.inherit",
    detail: "extended ticker",
    documentation: "将当前标的允许的 extended ticker 修饰符继承到当前标的；外部或动态标的不支持。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "1268",
    insertText: "ticker.inherit(${1:syminfo.tickerid}, syminfo.tickerid)",
  },
  {
    label: "chart.is_heikinashi",
    detail: "chart type",
    documentation: "当前策略主图使用 Heikin Ashi 蜡烛时为 true。",
    kind: "variable",
    sortText: "1269",
    insertText: "chart.is_heikinashi",
  },
  {
    label: "chart.is_standard",
    detail: "chart type",
    documentation: "当前策略主图使用标准 K 线时为 true。",
    kind: "variable",
    sortText: "1270",
    insertText: "chart.is_standard",
  },
  {
    label: "alert",
    detail: "notification",
    documentation: "写入策略通知通道。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "13",
    insertText: "alert(\"${1:message}\")",
  },
];

