import type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export type {
  MonacoCompletionDefinition,
  MonacoExtraLibDefinition,
  MonacoHoverDefinition,
} from "./strategyMonacoIntelliSenseTypes";

export const strategyPineEditorExtraLibs: MonacoExtraLibDefinition[] = [];

export const strategyPineEditorCompletions: MonacoCompletionDefinition[] = [
  {
    label: "//@version=6",
    detail: "Pine version",
    documentation: "声明 Pine Script v6。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "01",
    insertText: "//@version=6",
  },
  {
    label: "strategy",
    detail: "Pine strategy declaration",
    documentation: "声明可由 JFTrade 编译的 Pine 策略；支持默认仓位、initial_capital、commission_type/value、slippage 和 process_orders_on_close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "02",
    insertText: "strategy(\"${1:策略名称}\", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=${2:10}, initial_capital=${3:100000}, commission_type=strategy.commission.percent, commission_value=${4:0.1}, slippage=${5:0}, process_orders_on_close=true)",
  },
  {
    label: "ta.ema",
    detail: "indicator",
    documentation: "EMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "03",
    insertText: "ta.ema(${1:close}, ${2:20})",
  },
  {
    label: "ta.sma",
    detail: "indicator",
    documentation: "SMA 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04",
    insertText: "ta.sma(${1:close}, ${2:20})",
  },
  {
    label: "input.int",
    detail: "input default",
    documentation: "读取默认整数值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "041",
    insertText: "input.int(${1:20}, \"${2:Length}\")",
  },
  {
    label: "input",
    detail: "input default",
    documentation: "读取默认值；JFTrade 不实现 TradingView 设置面板运行时覆盖。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0410",
    insertText: "input(${1:20}, \"${2:Value}\")",
  },
  {
    label: "input.float",
    detail: "input default",
    documentation: "读取默认浮点值；支持 defval= 命名参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "042",
    insertText: "input.float(defval=${1:2.0}, title=\"${2:Mult}\")",
  },
  {
    label: "input.bool",
    detail: "input default",
    documentation: "读取默认 bool 值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0421",
    insertText: "input.bool(${1:true}, \"${2:Enabled}\")",
  },
  {
    label: "input.string",
    detail: "input default",
    documentation: "读取默认字符串值；JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0422",
    insertText: "input.string(\"${1:value}\", \"${2:Text}\")",
  },
  {
    label: "input.source",
    detail: "input default",
    documentation: "读取默认 source；第一版请使用 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "043",
    insertText: "input.source(${1:close}, \"${2:Source}\")",
  },
  {
    label: "input.time",
    detail: "input default",
    documentation: "读取默认时间值；常配合 timestamp(...)，JFTrade 不实现运行时 UI 调参。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0431",
    insertText: "input.time(timestamp(${1:2026}, ${2:1}, ${3:1}), \"${4:Start}\")",
  },
  {
    label: "input.timeframe",
    detail: "input default",
    documentation: "读取默认 timeframe 字符串；可用于受支持的 request.security 周期。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "04315",
    insertText: "input.timeframe(\"${1|15,30,60,240,D,W,M|}\", \"${2:Timeframe}\")",
  },
  {
    label: "input.color",
    detail: "input default",
    documentation: "读取默认颜色值；主要用于兼容 TradingView 模板和视觉参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0432",
    insertText: "input.color(color.${1|green,red,blue,orange,purple,gray,white,black|}, \"${2:Color}\")",
  },
  {
    label: "math.max",
    detail: "math",
    documentation: "取最大值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "044",
    insertText: "math.max(${1:left}, ${2:right})",
  },
  {
    label: "math.min",
    detail: "math",
    documentation: "取最小值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "045",
    insertText: "math.min(${1:left}, ${2:right})",
  },
  {
    label: "math.abs",
    detail: "math",
    documentation: "取绝对值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0451",
    insertText: "math.abs(${1:value})",
  },
  {
    label: "math.avg",
    detail: "math",
    documentation: "返回参数平均值；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0452",
    insertText: "math.avg(${1:left}, ${2:right})",
  },
  {
    label: "math.round",
    detail: "math",
    documentation: "四舍五入；可选 precision。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0453",
    insertText: "math.round(${1:value})",
  },
  {
    label: "math.round_to_mintick",
    detail: "math",
    documentation: "按当前市场 tick size 四舍五入，缺省 tick 为 0.01。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0454",
    insertText: "math.round_to_mintick(${1:close})",
  },
  {
    label: "math.floor",
    detail: "math",
    documentation: "向下取整；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0455",
    insertText: "math.floor(${1:value})",
  },
  {
    label: "math.ceil",
    detail: "math",
    documentation: "向上取整；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0456",
    insertText: "math.ceil(${1:value})",
  },
  {
    label: "math.sqrt",
    detail: "math",
    documentation: "平方根；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0457",
    insertText: "math.sqrt(${1:value})",
  },
  {
    label: "math.pow",
    detail: "math",
    documentation: "幂运算；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0458",
    insertText: "math.pow(${1:base}, ${2:exponent})",
  },
  {
    label: "math.log",
    detail: "math",
    documentation: "自然对数；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0459",
    insertText: "math.log(${1:value})",
  },
  {
    label: "math.sign",
    detail: "math",
    documentation: "返回 -1、0 或 1；由 PineTS worker 执行 math helper。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0460",
    insertText: "math.sign(${1:value})",
  },
  {
    label: "ta.rsi",
    detail: "indicator",
    documentation: "RSI 指标；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "05",
    insertText: "ta.rsi(${1:close}, ${2:14})",
  },
  {
    label: "ta.macd",
    detail: "indicator",
    documentation: "MACD 指标三元组。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06",
    insertText: "[${1:macdLine}, ${2:signalLine}, ${3:histLine}] = ta.macd(close, ${4:12}, ${5:26}, ${6:9})",
  },
  {
    label: "ta.highest",
    detail: "rolling window",
    documentation: "窗口最高值；单参数形式默认 source=high。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "061",
    insertText: "ta.highest(${1:high}, ${2:20})",
  },
  {
    label: "ta.lowest",
    detail: "rolling window",
    documentation: "窗口最低值；单参数形式默认 source=low。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "062",
    insertText: "ta.lowest(${1:low}, ${2:20})",
  },
  {
    label: "ta.roc",
    detail: "rolling window",
    documentation: "Rate of Change；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "063",
    insertText: "ta.roc(${1:close}, ${2:12})",
  },
  {
    label: "ta.sum",
    detail: "rolling window",
    documentation: "滚动求和；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0635",
    insertText: "ta.sum(${1:volume}, ${2:20})",
  },
  {
    label: "ta.rma",
    detail: "moving average",
    documentation: "Pine v6 RMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06351",
    insertText: "ta.rma(${1:close}, ${2:20})",
  },
  {
    label: "ta.wma",
    detail: "moving average",
    documentation: "Pine v6 WMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06352",
    insertText: "ta.wma(${1:close}, ${2:20})",
  },
  {
    label: "ta.hma",
    detail: "moving average",
    documentation: "Pine v6 HMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06353",
    insertText: "ta.hma(${1:close}, ${2:20})",
  },
  {
    label: "ta.vwma",
    detail: "moving average",
    documentation: "Pine v6 VWMA；使用 source 与 volume 计算成交量加权均线。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06354",
    insertText: "ta.vwma(${1:close}, ${2:20})",
  },
  {
    label: "ta.atr",
    detail: "indicator",
    documentation: "Average True Range；length 必须为静态正整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06355",
    insertText: "ta.atr(${1:14})",
  },
  {
    label: "ta.cci",
    detail: "indicator",
    documentation: "Commodity Channel Index；source-aware CCI，默认常用 hlc3。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "063555",
    insertText: "ta.cci(${1:hlc3}, ${2:20})",
  },
  {
    label: "ta.highestbars",
    detail: "rolling window",
    documentation: "返回窗口最高值相对当前 bar 的偏移。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06356",
    insertText: "ta.highestbars(${1:high}, ${2:20})",
  },
  {
    label: "ta.lowestbars",
    detail: "rolling window",
    documentation: "返回窗口最低值相对当前 bar 的偏移。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06357",
    insertText: "ta.lowestbars(${1:low}, ${2:20})",
  },
  {
    label: "ta.change",
    detail: "momentum",
    documentation: "返回 source 与 length 根前的差值；未传 length 时默认 1。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06358",
    insertText: "ta.change(${1:close}, ${2:1})",
  },
  {
    label: "ta.mom",
    detail: "momentum",
    documentation: "Momentum；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06359",
    insertText: "ta.mom(${1:close}, ${2:10})",
  },
  {
    label: "ta.range",
    detail: "rolling window",
    documentation: "窗口最高值与最低值之差。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06360",
    insertText: "ta.range(${1:close}, ${2:20})",
  },
  {
    label: "ta.mode",
    detail: "rolling window",
    documentation: "窗口众数；并列时返回较小值。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06361",
    insertText: "ta.mode(${1:close}, ${2:20})",
  },
  {
    label: "ta.rising",
    detail: "condition",
    documentation: "判断 source 是否连续上升 length 根。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06362",
    insertText: "ta.rising(${1:close}, ${2:3})",
  },
  {
    label: "ta.falling",
    detail: "condition",
    documentation: "判断 source 是否连续下降 length 根。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06363",
    insertText: "ta.falling(${1:close}, ${2:3})",
  },
  {
    label: "ta.stdev",
    detail: "rolling statistic",
    documentation: "滚动标准差；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06364",
    insertText: "ta.stdev(${1:close}, ${2:20})",
  },
  {
    label: "ta.variance",
    detail: "rolling statistic",
    documentation: "滚动方差；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06365",
    insertText: "ta.variance(${1:close}, ${2:20})",
  },
  {
    label: "ta.cum",
    detail: "stateful series",
    documentation: "从首根 bar 起累计 source。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06366",
    insertText: "ta.cum(${1:volume})",
  },
  {
    label: "ta.stoch",
    detail: "indicator",
    documentation: "Stochastic；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06367",
    insertText: "ta.stoch(${1:close}, high, low, ${2:14})",
  },
  {
    label: "ta.tr",
    detail: "indicator",
    documentation: "True Range；可传 handle_na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06368",
    insertText: "ta.tr(${1:true})",
  },
  {
    label: "ta.bb",
    detail: "indicator tuple",
    documentation: "Bollinger Bands 三元组；支持 [basis, upper, lower] = ta.bb(close, length, mult)。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "064",
    insertText: "[${1:basis}, ${2:upper}, ${3:lower}] = ta.bb(close, ${4:20}, ${5:2})",
  },
  {
    label: "ta.wpr",
    detail: "indicator",
    documentation: "Williams %R 指标。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "ta.wpr(${1:14})",
  },
  {
    label: "ta.vwap",
    detail: "indicator",
    documentation: "按交易日累计 VWAP；也支持 timeframe.change(\"D\"|\"W\"|\"M\") 的闭盘锚定重置。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0651",
    insertText: "ta.vwap(${1:hlc3})",
  },
  {
    label: "ta.bbw",
    detail: "indicator",
    documentation: "Bollinger Band Width；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06511",
    insertText: "ta.bbw(${1:close}, ${2:20}, ${3:2})",
  },
  {
    label: "ta.cog",
    detail: "indicator",
    documentation: "Center of Gravity；支持静态同标的 request.security。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06512",
    insertText: "ta.cog(${1:close}, ${2:10})",
  },
  {
    label: "ta.mfi",
    detail: "indicator",
    documentation: "Money Flow Index；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0652",
    insertText: "ta.mfi(${1:hlc3}, ${2:14})",
  },
  {
    label: "ta.dmi",
    detail: "indicator tuple",
    documentation: "DMI 三元组，返回 plusDI/minusDI/adx。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0653",
    insertText: "[${1:plusDI}, ${2:minusDI}, ${3:adx}] = ta.dmi(${4:14}, ${5:14})",
  },
  {
    label: "ta.supertrend",
    detail: "indicator tuple",
    documentation: "Supertrend 二元组，返回 line/direction。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0655",
    insertText: "[${1:st}, ${2:direction}] = ta.supertrend(${3:3}, ${4:10})",
  },
  {
    label: "ta.sar",
    detail: "indicator",
    documentation: "Parabolic SAR；生成 sar:start:increment:max requirement，支持 value/previous。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06555",
    insertText: "ta.sar(${1:0.02}, ${2:0.02}, ${3:0.2})",
  },
  {
    label: "ta.linreg",
    detail: "indicator",
    documentation: "线性回归值；offset 必须是非负静态整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065551",
    insertText: "ta.linreg(${1:close}, ${2:20}, ${3:0})",
  },
  {
    label: "ta.obv",
    detail: "indicator",
    documentation: "按价格 source 涨跌对 volume 做增量累计。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "065552",
    insertText: "ta.obv",
  },
  {
    label: "ta.pivothigh",
    detail: "indicator",
    documentation: "在 right bars 后确认 pivot high；确认前返回 na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065553",
    insertText: "ta.pivothigh(${1:high}, ${2:2}, ${3:2})",
  },
  {
    label: "ta.pivotlow",
    detail: "indicator",
    documentation: "在 right bars 后确认 pivot low；确认前返回 na。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065554",
    insertText: "ta.pivotlow(${1:low}, ${2:2}, ${3:2})",
  },
  {
    label: "ta.kc",
    detail: "indicator tuple",
    documentation: "Keltner Channel 三元组，返回 basis/upper/lower。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "065555",
    insertText: "[${1:basis}, ${2:upper}, ${3:lower}] = ta.kc(${4:close}, ${5:20}, ${6:1.5})",
  },
  {
    label: "ta.kcw",
    detail: "indicator",
    documentation: "返回归一化 Keltner Channel 宽度。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065556",
    insertText: "ta.kcw(${1:close}, ${2:20}, ${3:1.5})",
  },
  {
    label: "ta.alma",
    detail: "indicator",
    documentation: "Arnaud Legoux Moving Average。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065557",
    insertText: "ta.alma(${1:close}, ${2:20}, ${3:0.85}, ${4:6})",
  },
  {
    label: "ta.cmo",
    detail: "indicator",
    documentation: "Chande Momentum Oscillator；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065558",
    insertText: "ta.cmo(${1:close}, ${2:14})",
  },
  {
    label: "ta.tsi",
    detail: "indicator",
    documentation: "True Strength Index；使用短/长 EMA 平滑。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065559",
    insertText: "ta.tsi(${1:close}, ${2:13}, ${3:25})",
  },
  {
    label: "ta.correlation",
    detail: "rolling statistic",
    documentation: "滚动 Pearson 相关系数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065560",
    insertText: "ta.correlation(${1:close}, ${2:high}, ${3:20})",
  },
  {
    label: "ta.dev",
    detail: "rolling statistic",
    documentation: "滚动平均绝对偏差。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065561",
    insertText: "ta.dev(${1:close}, ${2:20})",
  },
  {
    label: "ta.median",
    detail: "rolling statistic",
    documentation: "滚动中位数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065562",
    insertText: "ta.median(${1:close}, ${2:20})",
  },
  {
    label: "ta.percentile_linear_interpolation",
    detail: "rolling statistic",
    documentation: "滚动百分位线性插值，percentage 必须为 0..100。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065563",
    insertText: "ta.percentile_linear_interpolation(${1:close}, ${2:20}, ${3:50})",
  },
  {
    label: "ta.percentile_nearest_rank",
    detail: "rolling statistic",
    documentation: "滚动 nearest-rank 百分位，percentage 必须为 0..100。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065564",
    insertText: "ta.percentile_nearest_rank(${1:close}, ${2:20}, ${3:80})",
  },
  {
    label: "ta.percentrank",
    detail: "rolling statistic",
    documentation: "当前值在滚动窗口中的百分排名。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065565",
    insertText: "ta.percentrank(${1:close}, ${2:20})",
  },
  {
    label: "ta.swma",
    detail: "moving average",
    documentation: "4-bar symmetric weighted moving average。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "065566",
    insertText: "ta.swma(${1:close})",
  },
  {
    label: "ta.barssince",
    detail: "stateful event",
    documentation: "首次触发前返回 na，触发 bar 返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0656",
    insertText: "ta.barssince(${1:condition})",
  },
  {
    label: "ta.valuewhen",
    detail: "stateful event",
    documentation: "返回第 occurrence 次最近触发时的 sourceExpression；occurrence 必须是非负整数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0657",
    insertText: "ta.valuewhen(${1:condition}, ${2:close}, ${3:0})",
  },
  {
    label: "timestamp",
    detail: "time",
    documentation: "按当前标的交易所时区解释并返回 Unix milliseconds；支持 timestamp(year, month, day[, hour, minute])，不支持显式 timezone 参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0658",
    insertText: "timestamp(${1:2026}, ${2:1}, ${3:1}, ${4:9}, ${5:30})",
  },
  {
    label: "barstate.isconfirmed",
    detail: "bar state",
    documentation: "PineTS worker 中已确认 K 线为 true；可用于兼容 TradingView 模板过滤。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06581",
    insertText: "barstate.isconfirmed",
  },
  {
    label: "session.ismarket",
    detail: "session state",
    documentation: "当前 K 线属于 regular market session 时为 true。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06582",
    insertText: "session.ismarket",
  },
  {
    label: "dayofweek.monday",
    detail: "Pine constant",
    documentation: "TradingView dayofweek 常量；PineTS worker normalizes 为数值 2。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06583",
    insertText: "dayofweek.monday",
  },
  {
    label: "month.january",
    detail: "Pine constant",
    documentation: "TradingView month 常量；PineTS worker normalizes 为数值 1。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "06584",
    insertText: "month.january",
  },
  {
    label: "color.rgb",
    detail: "color helper",
    documentation: "返回稳定颜色字符串；主要用于 input.color/视觉模板兼容。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06585",
    insertText: "color.rgb(${1:76}, ${2:175}, ${3:80})",
  },
  {
    label: "color.new",
    detail: "color helper",
    documentation: "JFTrade 当前忽略透明度并返回原颜色，用于兼容模板。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06586",
    insertText: "color.new(color.${1:green}, ${2:80})",
  },
  {
    label: "var",
    detail: "persistent variable",
    documentation: "声明跨 K 线保留的 Pine 变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "065",
    insertText: "var ${1:name} = ${2:0}",
  },
  {
    label: ":=",
    detail: "reassign",
    documentation: "更新已声明变量。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "066",
    insertText: "${1:name} := ${2:expression}",
  },
  {
    label: "nz",
    detail: "na helper",
    documentation: "当 value 为 na 时返回 fallback，未传 fallback 时返回 0。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "067",
    insertText: "nz(${1:value}, ${2:0})",
  },
  {
    label: "history reference",
    detail: "series[n]",
    documentation: "读取前 n 根 closed bar 的序列值；支持简单 identifier/member，最大 lookback 500。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068",
    insertText: "${1:close}[${2:1}]",
  },
  {
    label: "expression function",
    detail: "UDF expression",
    documentation: "UDF 会在编译期内联；支持局部赋值和最终 if/else 返回，不支持递归、method/type。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06801",
    insertText: "${1:isBull}(${2:src}) => ${2:src} > ${2:src}[1]",
  },
  {
    label: "switch expression",
    detail: "static switch",
    documentation: "switch 作为 PineTS worker 可执行分支表达式使用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068015",
    insertText: ["${1:signal} = switch", "    ${2:condition} => ${3:value}", "    => ${4:fallback}"].join("\n"),
  },
  {
    label: "for static",
    detail: "static for unroll",
    documentation: "静态 for 会按 inclusive to 语义编译期展开；v2.4 中包含条件 break/continue 时会 fallback 到有界 runtime loop。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06802",
    insertText: ["for ${1:i} = ${2:0} to ${3:3}", "    ${4:sum} := ${4:sum} + ${5:close}[${1:i}]"].join("\n"),
  },
  {
    label: "for dynamic",
    detail: "v2.2 dynamic loop",
    documentation: "v2.2 支持动态 for、break/continue；PineTS worker 会限制嵌套深度和单 bar 最大迭代数。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068021",
    insertText: ["for ${1:i} = ${2:0} to ${3:limit}", "    ${4:total} := ${4:total} + ${1:i}"].join("\n"),
  },
  {
    label: "while",
    detail: "v2.2 bounded loop",
    documentation: "v2.2 支持 while、break/continue；请确保循环状态会在同一根 closed bar 内推进。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068022",
    insertText: ["while ${1:count} < ${2:limit}", "    ${1:count} := ${1:count} + 1"].join("\n"),
  },
  {
    label: "tuple destructure",
    detail: "v2.2 tuple",
    documentation: "v2.2 支持 2 到 8 元 tuple literal/destructure，支持 _ discard。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068023",
    insertText: "[${1:a}, ${2:b}, _, ${3:d}] = [${4:open}, ${5:high}, ${6:low}, ${7:close}]",
  },
  {
    label: "plot",
    detail: "PineTS visual output",
    documentation: "PineTS worker 会计算 plot 序列并通过 worker response 透出；交易执行仍只消费 strategy.* order intents。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0681",
    insertText: "plot(${1:close})",
  },
  {
    label: "plotshape",
    detail: "PineTS visual output",
    documentation: "PineTS 支持形状标记；JFTrade 将其归入 visual output，不参与 Go 侧下单和风控。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06811",
    insertText: "plotshape(${1:condition}, title=\"${2:Signal}\", text=\"${3:S}\")",
  },
  {
    label: "plotchar",
    detail: "PineTS visual output",
    documentation: "PineTS 支持字符标记；JFTrade 将其归入 visual output，不参与 Go 侧下单和风控。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06812",
    insertText: "plotchar(${1:condition}, title=\"${2:Signal}\", char=\"${3:*}\")",
  },
  {
    label: "label.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 drawing 对象；JFTrade worker 会按 visual output 边界透出，流程图块不把绘图对象当作交易动作。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06813",
    insertText: "label.new(bar_index, ${1:close}, \"${2:Signal}\")",
  },
  {
    label: "line.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 line drawing；JFTrade worker 会按 visual output 边界透出，交易语义仍由 strategy.* 决定。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06814",
    insertText: "line.new(bar_index[1], ${1:close[1]}, bar_index, ${2:close})",
  },
  {
    label: "box.new",
    detail: "PineTS drawing output",
    documentation: "PineTS 支持 box drawing；JFTrade worker 会按 visual output 边界透出，不进入订单 intent。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06815",
    insertText: "box.new(bar_index[1], ${1:high[1]}, bar_index, ${2:low})",
  },
  {
    label: "table.new",
    detail: "PineTS table output",
    documentation: "PineTS 支持 table 对象；JFTrade 将 table 归为 visual output，不作为流程图交易图块。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06816",
    insertText: "table.new(position.${1|top_right,bottom_right,top_left,bottom_left|}, ${2:2}, ${3:2})",
  },
  {
    label: "hline/fill",
    detail: "PineTS visual output",
    documentation: "PineTS 支持 hline/fill 视觉层；JFTrade 将其归为 visual output。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06817",
    insertText: ["${1:upper} = hline(${2:70})", "${3:lower} = hline(${4:30})", "fill(${1:upper}, ${3:lower})"].join("\n"),
  },
  {
    label: "alertcondition",
    detail: "PineTS alert event",
    documentation: "PineTS worker 会产出 alertcondition 事件；JFTrade 将其通过 alerts 边界透出，交易通知仍建议用 alert() 或订单 alert metadata 明确表达。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0682",
    insertText: "alertcondition(${1:condition}, \"${2:Title}\")",
  },
  {
    label: "array.new_float",
    detail: "v2.4 executable collection",
    documentation: "v2.4 支持 array constructor、from/concat/sort/sort_indices/binary_search/join/median/mode/range 和常用读写，并保留跨 K 线引用状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06831",
    insertText: "${1:arr} = array.new_float(${2:0})",
  },
  {
    label: "array.copy/slice",
    detail: "v2.3 executable collection",
    documentation: "复制并切片 array；slice 使用 [from, to) 范围，结果可继续调用 array method。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068311",
    insertText: ["${1:copyValues} = ${2:arr}.copy()", "${3:window} = ${1:copyValues}.slice(${4:0}, ${5:2})"].join("\n"),
  },
  {
    label: "array.aggregate",
    detail: "v2.4 executable collection",
    documentation: "array min/max/avg/sum/median/mode/range/includes/indexof/lastindexof 可在表达式、条件和受限 request.security 纯表达式中使用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068312",
    insertText: "${1:total} = ${2:arr}.${3|sum,avg,min,max,median,mode,range,size,last,first|}()",
  },
  {
    label: "array.from/concat/join",
    detail: "v2.4 executable collection",
    documentation: "array.from(...) 构造值列表；concat 会追加另一个 array；join 使用稳定字符串化结果。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068313",
    insertText: ["${1:values} = array.from(${2:close}, ${3:open})", "${1:values}.concat(array.from(${4:high}))", "${5:text} = ${1:values}.join(\"${6:,}\")"].join("\n"),
  },
  {
    label: "array.sort/sort_indices",
    detail: "v2.4 deterministic sort",
    documentation: "支持 number/string/bool/nil；nil 稳定放末尾。order.ascending/order.descending 表示确定性排序方向。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068314",
    insertText: ["${1:values}.sort(order.${2|ascending,descending|})", "${3:idx} = ${1:values}.sort_indices(order.${4|ascending,descending|})"].join("\n"),
  },
  {
    label: "array.binary_search",
    detail: "v2.4 executable collection",
    documentation: "在已排序 array 中查找目标值，未命中返回 -1；排序比较采用 JFTrade deterministic 规则。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068315",
    insertText: "${1:index} = ${2:values}.binary_search(${3:close})",
  },
  {
    label: "array.stats",
    detail: "v2.5 executable collection",
    documentation: "v2.5 支持 array abs、leftmost/rightmost binary search、percentrank、percentile、stdev、variance、covariance。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683151",
    insertText: "${1:value} = ${2:values}.${3|percentrank,percentile_nearest_rank,percentile_linear_interpolation,stdev,variance,covariance,abs|}(${4:50})",
  },
  {
    label: "for in array",
    detail: "v2.6 collection loop",
    documentation: "v2.6 支持 array for-in；map 请先使用 keys()/values() 得到确定性 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683152",
    insertText: ["for [${1:i}, ${2:value}] in ${3:values}", "    ${4:total} := ${4:total} + ${2:value}"].join("\n"),
  },
  {
    label: "collection history",
    detail: "v2.6 read-only snapshot",
    documentation: "v2.6 支持只读 array history snapshot，例如 arr[1].get(0)/size()/first()/last()。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683153",
    insertText: "${1:previousValue} = ${2:values}[${3:1}].${4|get,size,first,last|}(${5:0})",
  },
  {
    label: "collection history aggregate",
    detail: "v2.7 read-only aggregate",
    documentation: "v2.7 支持历史 array 上的 range/median/mode/stdev/variance 等只读 aggregate/stat snapshot。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683154",
    insertText: "${1:previousStat} = ${2:values}[${3:1}].${4|range,median,mode,stdev,variance|}()",
  },
  {
    label: "order.ascending",
    detail: "v2.4 sort constant",
    documentation: "array.sort/sort_indices 排序方向常量；同批支持 order.descending。",
    kind: "variable",
    insertTextRule: "snippet",
    sortText: "068316",
    insertText: "order.ascending",
  },
  {
    label: "map.new",
    detail: "v2.4 executable collection",
    documentation: "v2.4 支持 map.new/get/put/remove/contains/size/clear/copy/keys/values；keys/values 按 key 的稳定字符串序返回 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06832",
    insertText: "${1:values} = map.new<${2:string}, ${3:float}>()",
  },
  {
    label: "map.keys/values",
    detail: "v2.4 deterministic views",
    documentation: "keys() 和 values() 返回 array，并按 key 的稳定字符串序排序，保证回测可复现。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068321",
    insertText: ["${1:keys} = ${2:values}.keys()", "${3:items} = ${2:values}.values()", "${4:copy} = ${2:values}.copy()"].join("\n"),
  },
  {
    label: "for in map keys",
    detail: "v2.7 deterministic map iteration",
    documentation: "v2.7 支持通过 map.keys()/values() 返回的确定性 array 进行 for-in。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068322",
    insertText: ["for ${1:key} in ${2:values}.keys()", "    ${3:total} := ${3:total} + ${2:values}.get(${1:key})"].join("\n"),
  },
  {
    label: "matrix.new",
    detail: "v2.3 executable collection",
    documentation: "v2.3 支持 matrix.new/get/set/rows/columns/fill/copy/reshape/add_row/add_col/remove_row/remove_col，并保留跨 K 线引用状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06833",
    insertText: "${1:grid} = matrix.new<${2:float}>(${3:1}, ${4:1})",
  },
  {
    label: "matrix.reshape",
    detail: "v2.3 executable collection",
    documentation: "matrix.reshape(rows, columns) 要求总 cell 数不变；remove_row/remove_col 返回 array。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068331",
    insertText: ["${1:grid}.reshape(${2:1}, ${3:4})", "${4:row} = ${1:grid}.remove_row(${5:0})"].join("\n"),
  },
  {
    label: "matrix cell",
    detail: "v2.7 matrix read/write",
    documentation: "v2.7 锁定 matrix rows/columns/get/set 组合，用于 PineTS worker 中的基础二维状态。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068332",
    insertText: ["${1:grid}.set(${2:0}, ${3:0}, ${4:close})", "${5:value} = ${1:grid}.get(${2:0}, ${3:0})", "${6:rows} = ${1:grid}.rows()", "${7:cols} = ${1:grid}.columns()"].join("\n"),
  },
  {
    label: "type",
    detail: "v2.4 pure UDT subset",
    documentation: "v2.4 支持纯 UDT constructor、字段默认值、命名 constructor 参数、局部和 var object 字段重赋值；library/import 和完整 Pine type 系统仍只做诊断。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06834",
    insertText: ["type ${1:TradeBox}", "    ${2:float} ${3:price}"].join("\n"),
  },
  {
    label: "method",
    detail: "v2.4 pure method subset",
    documentation: "v2.4 支持单表达式和受控多语句纯 method、默认值与命名参数；表达式 method 可在受限 MTF pure expression 内调用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06835",
    insertText: "method ${1:score}(${2:TradeBox} ${3:self}, ${4:float} ${5:factor} = ${6:1}) => ${3:self}.${7:price} * ${5:factor}",
  },
  {
    label: "method block",
    detail: "v2.4 pure method subset",
    documentation: "多语句纯 method 会在 PineTS worker 中执行；receiver 字段可读，method 内不执行订单、绘图或 collection 副作用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068351",
    insertText: ["method ${1:score}(${2:TradeBox} ${3:self}, ${4:float} ${5:factor} = ${6:1}) =>", "    ${7:base} = ${3:self}.${8:price} * ${5:factor}", "    ${7:base}"].join("\n"),
  },
  {
    label: "object field set",
    detail: "v2.4 persistent object",
    documentation: "object 字段可用 := 重赋值；var object 字段值会随变量跨 K 线持久化。method 内副作用和跨 library method 仍不执行。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068352",
    insertText: "${1:box}.${2:price} := ${3:close}",
  },
  {
    label: "object collection field",
    detail: "v2.6 UDT collection field",
    documentation: "v2.6 支持 UDT 字段持有 collection 引用，并执行 box.values.push(close) 等字段 collection method。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068353",
    insertText: ["type ${1:Box}", "    array<float> ${2:values}", "${3:box} = ${1:Box}.new(array.new_float())", "${3:box}.${2:values}.push(${4:close})"].join("\n"),
  },
  {
    label: "object history",
    detail: "v2.8 object snapshot",
    documentation: "v2.8 支持 object 历史字段读取，例如 box[1].price；历史对象仍为只读 snapshot。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683531",
    insertText: "${1:previousPrice} = ${2:box}[${3:1}].${4:price}",
  },
  {
    label: "method chain",
    detail: "v2.8 pure method chain",
    documentation: "v2.8 支持无副作用 method chain，例如 box.identity().score(2)，不执行 method 内副作用。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683532",
    insertText: "${1:value} = ${2:box}.${3:identity}().${4:score}(${5:2})",
  },
  {
    label: "object history method",
    detail: "v2.9 object snapshot method",
    documentation: "v2.9 支持历史 object snapshot 作为纯 method receiver，例如 box[1].score(factor=2)。历史对象仍为只读。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683533",
    insertText: "${1:previousScore} = ${2:box}[${3:1}].${4:score}(${5:factor=2})",
  },
  {
    label: "request.security object history",
    detail: "v2.9 MTF pure object history",
    documentation: "v2.9 支持同标的静态 timeframe 下的纯 object history field/method 表达式；动态 symbol/timeframe、nested request 和副作用会分码诊断。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683534",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ${2:box}[${3:1}].${4:price})",
  },
  {
    label: "varip",
    detail: "PineTS worker varip compatibility",
    documentation: "v3.0 中 varip 在 PineTS worker 下按 var 语义执行，并输出兼容性 warning。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683535",
    insertText: "varip ${1:state} = ${2:0}",
  },
  {
    label: "str helpers",
    detail: "v2.5 string helpers",
    documentation: "v2.5 支持 str.length/contains/pos/substring/replace/upper/lower/format 纯表达式 helper。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068354",
    insertText: "${1:text} = str.${2|format,upper,lower,length,contains,pos,substring,replace|}(${3:\"value\"})",
  },
  {
    label: "str.length",
    detail: "string helper",
    documentation: "返回字符串长度。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683541",
    insertText: "str.length(${1:text})",
  },
  {
    label: "str.tostring",
    detail: "string helper",
    documentation: "把值转换为字符串；可选 format。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "06835415",
    insertText: "str.tostring(${1:value})",
  },
  {
    label: "str.contains",
    detail: "string helper",
    documentation: "判断 source 是否包含 needle。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683542",
    insertText: "str.contains(${1:text}, ${2:\"needle\"})",
  },
  {
    label: "str.pos",
    detail: "string helper",
    documentation: "返回 needle 在 source 中的位置，未找到时返回 -1。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683543",
    insertText: "str.pos(${1:text}, ${2:\"needle\"})",
  },
  {
    label: "str.substring",
    detail: "string helper",
    documentation: "返回字符串子串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683544",
    insertText: "str.substring(${1:text}, ${2:0}, ${3:3})",
  },
  {
    label: "str.replace",
    detail: "string helper",
    documentation: "替换 source 中的 target。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683545",
    insertText: "str.replace(${1:text}, ${2:\"target\"}, ${3:\"replacement\"})",
  },
  {
    label: "str.upper",
    detail: "string helper",
    documentation: "返回大写字符串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683546",
    insertText: "str.upper(${1:text})",
  },
  {
    label: "str.lower",
    detail: "string helper",
    documentation: "返回小写字符串。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683547",
    insertText: "str.lower(${1:text})",
  },
  {
    label: "str.format",
    detail: "string helper",
    documentation: "使用 {0}/{1} 占位替换参数。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "0683548",
    insertText: "str.format(\"${1:{0}}\", ${2:value})",
  },
  {
    label: "timeframe.change",
    detail: "v2.5 timeframe helper",
    documentation: "v2.5 支持静态 timeframe.change，用于 K 线周期边界判断；同批支持 time_close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068355",
    insertText: "timeframe.change(\"${1:15}\")",
  },
  {
    label: "timeframe.in_seconds",
    detail: "v2.7 timeframe helper",
    documentation: "v2.7 支持 timeframe.in_seconds(timeframe?)、timeframe.multiplier 与 timeframe.isseconds。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "0683551",
    insertText: "timeframe.in_seconds(\"${1:15}\")",
  },
  {
    label: "import",
    detail: "v2 parse-only declaration",
    documentation: "v2.0 语言底座：import 会进入 semantic declarations 与 alias 诊断；当前不会加载 TradingView library。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06836",
    insertText: "import ${1:TradingView/ta/7}",
  },
  {
    label: "library",
    detail: "v2 parse-only declaration",
    documentation: "v2.0 语言底座：library(...) 会进入 semantic declarations；JFTrade 策略运行仍要求 strategy(...) 主入口。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "06837",
    insertText: "library(\"${1:LibraryName}\")",
  },
  {
    label: "export",
    detail: "v2.8 semantic metadata",
    documentation: "v2.8 会为 export function/type/method 标记 exportedKind metadata；不会加载或执行跨 library 代码。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "068362",
    insertText: "export ${1:helper}(${2:float src}) => ${3:src}",
  },
  {
    label: "ternary",
    detail: "conditional expression",
    documentation: "基础条件表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "069",
    insertText: "${1:condition} ? ${2:trueValue} : ${3:falseValue}",
  },
  {
    label: "ta.crossover",
    detail: "condition",
    documentation: "判断左侧序列上穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "07",
    insertText: "ta.crossover(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.crossunder",
    detail: "condition",
    documentation: "判断左侧序列下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "08",
    insertText: "ta.crossunder(${1:fast}, ${2:slow})",
  },
  {
    label: "ta.cross",
    detail: "condition",
    documentation: "判断左侧序列上穿或下穿右侧序列。",
    kind: "function",
    insertTextRule: "snippet",
    sortText: "081",
    insertText: "ta.cross(${1:fast}, ${2:slow})",
  },
  {
    label: "if crossover entry",
    detail: "strategy pattern",
    documentation: "均线上穿后开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "09",
    insertText: [
      "if ta.crossover(${1:fast}, ${2:slow})",
      "    strategy.entry(\"${3:Long}\", strategy.long, qty=${4:1})",
    ].join("\n"),
  },
  {
    label: "strategy.entry long",
    detail: "order",
    documentation: "开多。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "10",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty=${2:1})",
  },
  {
    label: "strategy.entry qty_percent",
    detail: "order",
    documentation: "按账户权益百分比开仓；PineTS worker normalizes 为 account_position_percent。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "101",
    insertText: "strategy.entry(\"${1:Long}\", strategy.long, qty_percent=${2:10})",
  },
  {
    label: "strategy.entry stop",
    detail: "pending order",
    documentation: "基础 stop pending；突破 stop 价后按 PineTS worker + Go 订单链路触发。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "102",
    insertText: "strategy.entry(\"${1:Breakout}\", strategy.long, stop=${2:ta.highest(high, 20)}, qty=${3:1})",
  },
  {
    label: "strategy.entry short",
    detail: "order",
    documentation: "开空。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "11",
    insertText: "strategy.entry(\"${1:Short}\", strategy.short, qty=${2:1})",
  },
  {
    label: "strategy.order",
    detail: "net order",
    documentation: "提交净额买入/卖出；不受 strategy.entry pyramiding gate 限制。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "115",
    insertText: "strategy.order(\"${1:Net}\", strategy.${2|long,short|}, qty=${3:1})",
  },
  {
    label: "strategy.order stop",
    detail: "pending net order",
    documentation: "净额 stop pending；不套用 strategy.entry pyramiding gate。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "116",
    insertText: "strategy.order(\"${1:Net stop}\", strategy.${2|long,short|}, stop=${3:close}, qty=${4:1})",
  },
  {
    label: "strategy.close",
    detail: "order",
    documentation: "按 entry id 平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "12",
    insertText: "strategy.close(\"${1:Long}\")",
  },
  {
    label: "strategy.close qty_percent",
    detail: "order",
    documentation: "按当前 symbol 持仓百分比平仓。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "121",
    insertText: "strategy.close(\"${1:Long}\", qty_percent=${2:50})",
  },
  {
    label: "strategy.close_all",
    detail: "order",
    documentation: "按当前实际持仓方向 flatten 当前策略 symbol。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "122",
    insertText: "strategy.close_all()",
  },
  {
    label: "strategy.cancel",
    detail: "pending order",
    documentation: "取消当前策略 symbol 中指定 id 的未触发 pending order。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "123",
    insertText: "strategy.cancel(\"${1:Breakout}\")",
  },
  {
    label: "strategy.cancel_all",
    detail: "pending order",
    documentation: "取消当前策略 symbol 的全部未触发 pending orders。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "124",
    insertText: "strategy.cancel_all()",
  },
  {
    label: "strategy.exit stop",
    detail: "exit",
    documentation: "基础止损；stop 可使用普通数值表达式。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "125",
    insertText: "strategy.exit(\"${1:Long stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100))",
  },
  {
    label: "strategy.exit qty_percent",
    detail: "exit",
    documentation: "stop/limit/trailing 子集可按当前持仓百分比部分退出。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1251",
    insertText: "strategy.exit(\"${1:Half stop}\", \"${2:Long}\", stop=close * (1 - ${3:2} / 100), qty_percent=${4:50})",
  },
  {
    label: "strategy.exit bracket",
    detail: "exit",
    documentation: "基础 stop+limit bracket；同 bar 两侧触发时采用 stop-first。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1252",
    insertText: "strategy.exit(\"${1:Bracket}\", \"${2:Long}\", stop=${3:close * 0.98}, limit=${4:close * 1.04}, qty_percent=${5:100})",
  },
  {
    label: "request.security MTF MA",
    detail: "multi-timeframe",
    documentation: "受限多周期 source-aware 均线与 v2.4 ta.stoch 子集；支持 5/15/30/45/60/120/240 分钟和 D/W/M。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "126",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ta.${2|ema,sma,rma,wma,hma,vwma|}(${3|close,hlc3,hl2,ohlc4,open,high,low,volume|}, ${4:20}))",
  },
  {
    label: "request.security MTF source",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 OHLCV/hl2/hlc3/ohlc4 source。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1261",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|})",
  },
  {
    label: "request.security MTF source[1]",
    detail: "multi-timeframe",
    documentation: "读取同标的高周期 source 历史值，例如上一根日线 close。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1262",
    insertText: "request.security(syminfo.tickerid, \"${1:D}\", ${2|close,hlc3,hl2,ohlc4,open,high,low,volume|}[${3:1}])",
  },
  {
    label: "request.security MTF tuple",
    detail: "multi-timeframe tuple",
    documentation: "支持 source、source[n]、source-aware MA、v2.4 ta.stoch、纯表达式组合和 v2.2 2-8 元 tuple。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1263",
    insertText: "[${1:mtfClose}, ${2:mtfFast}] = request.security(syminfo.tickerid, \"${3:15}\", [${4:close}, ta.${5|ema,sma,rma,wma,hma,vwma|}(${6:close}, ${7:20})])",
  },
  {
    label: "request.security MTF object/collection",
    detail: "v2.4 multi-timeframe expression",
    documentation: "v2.4 支持同标的静态 timeframe 中的纯 collection read、纯 object field/method 表达式和命名/default method 参数；副作用、nested request、动态 symbol/timeframe 仍诊断失败。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1264",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ${2:box}.${3:score}(${4:2}))",
  },
  {
    label: "request.security MTF stoch",
    detail: "v2.4 multi-timeframe indicator",
    documentation: "支持同标的静态 timeframe 的 ta.stoch(source, high, low, length)，会规划带 timeframe 后缀的 stoch requirement。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "1265",
    insertText: "request.security(syminfo.tickerid, \"${1:15}\", ta.stoch(${2:close}, high, low, ${3:14}))",
  },
  {
    label: "alert",
    detail: "notification",
    documentation: "写入策略通知通道。",
    kind: "snippet",
    insertTextRule: "snippet",
    sortText: "13",
    insertText: "alert(\"${1:message}\")",
  },
];

export const strategyPineEditorHoverItems: MonacoHoverDefinition[] = [
  {
    target: "ta.ema",
    signature: "ta.ema(source, length)",
    documentation: "Pine v6 EMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "ta.sma",
    signature: "ta.sma(source, length)",
    documentation: "Pine v6 SMA；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "ta.rsi",
    signature: "ta.rsi(source, length)",
    documentation: "Pine v6 RSI；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.macd",
    signature: "[macdLine, signalLine, histLine] = ta.macd(source, fast, slow, signal)",
    documentation: "Pine v6 MACD 三元组；可在 tuple assignment、字段读取和支持的 MTF 表达式中使用。",
  },
  {
    target: "ta.roc",
    signature: "ta.roc(source, length)",
    documentation: "Rate of Change；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "ta.crossover",
    signature: "ta.crossover(left, right) -> bool",
    documentation: "Pine v6 交叉检测；在 PineTS worker 中按上一根与当前 closed bar 判断。",
  },
  {
    target: "ta.crossunder",
    signature: "ta.crossunder(left, right) -> bool",
    documentation: "Pine v6 下穿检测；在 PineTS worker 中按上一根与当前 closed bar 判断。",
  },
  {
    target: "ta.cross",
    signature: "ta.cross(left, right) -> bool",
    documentation: "Pine v6 任意方向交叉检测；在 PineTS worker 中执行。",
  },
  {
    target: "ta.highest",
    signature: "ta.highest(source, length) / ta.highest(length)",
    documentation: "JFTrade 支持 open/high/low/close/volume/hl2/hlc3/ohlc4 source；单参数 highest(length) 默认 high。",
  },
  {
    target: "ta.lowest",
    signature: "ta.lowest(source, length) / ta.lowest(length)",
    documentation: "JFTrade 支持 open/high/low/close/volume/hl2/hlc3/ohlc4 source；单参数 lowest(length) 默认 low。",
  },
  {
    target: "ta.bb",
    signature: "[basis, upper, lower] = ta.bb(close, length, mult)",
    documentation: "Pine v6 Bollinger Bands 三元组；可在条件、字段读取和支持的 MTF 表达式中使用。",
  },
  {
    target: "ta.wpr",
    signature: "ta.wpr(length)",
    documentation: "Pine v6 Williams %R；按 closed bar 数据计算。",
  },
  {
    target: "ta.sum",
    signature: "ta.sum(source, length)",
    documentation: "滚动窗口求和；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "ta.rma",
    signature: "ta.rma(source, length)",
    documentation: "Pine v6 RMA；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.wma",
    signature: "ta.wma(source, length)",
    documentation: "Pine v6 WMA；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.hma",
    signature: "ta.hma(source, length)",
    documentation: "Pine v6 HMA；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.vwma",
    signature: "ta.vwma(source, length)",
    documentation: "Pine v6 VWMA；使用 source 与 volume 计算成交量加权均线。",
  },
  {
    target: "ta.atr",
    signature: "ta.atr(length)",
    documentation: "Average True Range；可在策略条件、变量和静态同标的 MTF 表达式中使用。",
  },
  {
    target: "ta.cci",
    signature: "ta.cci(source, length)",
    documentation: "Commodity Channel Index；source-aware CCI，默认常用 hlc3。",
  },
  {
    target: "ta.highestbars",
    signature: "ta.highestbars(source, length)",
    documentation: "返回窗口最高值相对当前 bar 的偏移。",
  },
  {
    target: "ta.lowestbars",
    signature: "ta.lowestbars(source, length)",
    documentation: "返回窗口最低值相对当前 bar 的偏移。",
  },
  {
    target: "ta.change",
    signature: "ta.change(source[, length])",
    documentation: "返回 source 与 length 根前的差值；未传 length 时默认 1。",
  },
  {
    target: "ta.mom",
    signature: "ta.mom(source, length)",
    documentation: "Momentum；source 支持 open/high/low/close/volume/hl2/hlc3/ohlc4。",
  },
  {
    target: "ta.range",
    signature: "ta.range(source, length)",
    documentation: "滚动最高值与最低值之差。",
  },
  {
    target: "ta.mode",
    signature: "ta.mode(source, length)",
    documentation: "滚动众数；并列时返回较小值。",
  },
  {
    target: "ta.rising",
    signature: "ta.rising(source, length)",
    documentation: "判断 source 是否连续上升 length 根。",
  },
  {
    target: "ta.falling",
    signature: "ta.falling(source, length)",
    documentation: "判断 source 是否连续下降 length 根。",
  },
  {
    target: "ta.stdev",
    signature: "ta.stdev(source, length)",
    documentation: "滚动标准差；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.variance",
    signature: "ta.variance(source, length)",
    documentation: "滚动方差；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.cum",
    signature: "ta.cum(source)",
    documentation: "从首根 bar 起累计 source。",
  },
  {
    target: "ta.stoch",
    signature: "ta.stoch(source, high, low, length)",
    documentation: "Stochastic；支持静态同标的 request.security。",
  },
  {
    target: "ta.tr",
    signature: "ta.tr(handle_na?)",
    documentation: "True Range；可直接读取当前 bar 的 TR。",
  },
  {
    target: "hlc3",
    signature: "hlc3",
    documentation: "派生价格源 (high + low + close) / 3；同批支持 hl2 和 ohlc4。",
  },
  {
    target: "series[n]",
    signature: "identifier[n] / object.field[n]",
    documentation: "读取前 n 根 closed bar 的历史值；函数调用结果请先赋值后再使用历史引用。",
  },
  {
    target: "=>",
    signature: "name(arg1, arg2) => expression",
    documentation: "JFTrade 支持顶层表达式 UDF，编译期内联；参数数量必须匹配，不支持递归或多语句函数。",
  },
  {
    target: "for",
    signature: "for i = start to end [by step]",
    documentation: "JFTrade 支持静态整数边界循环，按 Pine inclusive to 语义最多展开 100 次；v2.4 中静态 for 遇到条件 break/continue 会 fallback 到有界 runtime loop。",
  },
  {
    target: "alertcondition",
    signature: "alertcondition(condition, title?, message?)",
    documentation: "PineTS worker 会产出 alertcondition 事件；JFTrade 通过 alerts 边界透出，交易执行不消费该声明。",
  },
  {
    target: "plot",
    signature: "plot(series, ...)",
    documentation: "PineTS worker 会计算 plot 序列并透出到 plots；Go 交易链路不消费 plot。",
  },
  {
    target: "plotshape",
    signature: "plotshape(condition, title?, text?, ...)",
    documentation: "PineTS worker 支持形状标记；JFTrade 将其归为 visual output，不进入订单 intent。",
  },
  {
    target: "plotchar",
    signature: "plotchar(condition, title?, char?, ...)",
    documentation: "PineTS worker 支持字符标记；JFTrade 将其归为 visual output，不进入订单 intent。",
  },
  {
    target: "label.new",
    signature: "label.new(x, y, text, ...)",
    documentation: "PineTS worker 支持 label drawing；JFTrade 将 drawing 对象归为 visual output。",
  },
  {
    target: "line.new",
    signature: "line.new(x1, y1, x2, y2, ...)",
    documentation: "PineTS worker 支持 line drawing；JFTrade 将 drawing 对象归为 visual output。",
  },
  {
    target: "box.new",
    signature: "box.new(left, top, right, bottom, ...)",
    documentation: "PineTS worker 支持 box drawing；JFTrade 将 drawing 对象归为 visual output。",
  },
  {
    target: "table.new",
    signature: "table.new(position, columns, rows, ...)",
    documentation: "PineTS worker 支持 table 对象；JFTrade 将 table 归为 visual output。",
  },
  {
    target: "array.new_float",
    signature: "array.new_float(size, initial_value?)",
    documentation: "v2.4 可执行 array 核心；支持常用读写、队列操作、from/concat/sort/sort_indices/binary_search/join/median/mode/range 与跨 K 线 var 状态。",
  },
  {
    target: "array.from",
    signature: "array.from(value1, value2, ...)",
    documentation: "v2.4 支持从参数列表构造 array，可继续使用 method 形式调用 concat/sort/join/aggregate。",
  },
  {
    target: "array.sort",
    signature: "array.sort(id, order?) / id.sort(order?)",
    documentation: "v2.4 支持 number/string/bool/nil 的确定性排序；nil 放末尾，order 支持 order.ascending/order.descending。",
  },
  {
    target: "array.sort_indices",
    signature: "array.sort_indices(id, order?) / id.sort_indices(order?)",
    documentation: "v2.4 返回排序后的原索引 array，不修改原 array；排序规则与 array.sort 一致。",
  },
  {
    target: "array.binary_search",
    signature: "array.binary_search(id, value) / id.binary_search(value)",
    documentation: "v2.4 在已排序 array 中查找目标值，未命中返回 -1。",
  },
  {
    target: "array.percentile_linear_interpolation",
    signature: "array.percentile_linear_interpolation(id, percentage) / id.percentile_linear_interpolation(percentage)",
    documentation: "v2.5 支持数值 array percentile/percentrank/stdev/variance/covariance 统计子集。",
  },
  {
    target: "for...in",
    signature: "for value in array / for [index, value] in array",
    documentation: "v2.6 支持 array for-in，使用 bounded runtime loop；map 请通过 keys()/values() 转为确定性 array。",
  },
  {
    target: "array history",
    signature: "arr[n].get(index) / arr[n].size() / arr[n].range() / arr[n].stdev()",
    documentation: "v2.7 支持只读 collection history snapshot 和常用 aggregate/stat；历史 collection mutation 不执行。",
  },
  {
    target: "str.format",
    signature: "str.format(format, value1, value2, ...)",
    documentation: "v2.5 支持常用 str.* helper；str.format 使用 {0}/{1} 占位替换。",
  },
  {
    target: "str.length",
    signature: "str.length(source)",
    documentation: "返回字符串长度。",
  },
  {
    target: "str.tostring",
    signature: "str.tostring(value, format?)",
    documentation: "把值转换为字符串；可选 format。",
  },
  {
    target: "str.contains",
    signature: "str.contains(source, needle)",
    documentation: "判断 source 是否包含 needle。",
  },
  {
    target: "str.pos",
    signature: "str.pos(source, needle)",
    documentation: "返回 needle 在 source 中的位置，未找到时返回 -1。",
  },
  {
    target: "str.substring",
    signature: "str.substring(source, begin, end?)",
    documentation: "返回字符串子串。",
  },
  {
    target: "str.replace",
    signature: "str.replace(source, target, replacement)",
    documentation: "替换 source 中的 target。",
  },
  {
    target: "str.upper",
    signature: "str.upper(source)",
    documentation: "返回大写字符串。",
  },
  {
    target: "str.lower",
    signature: "str.lower(source)",
    documentation: "返回小写字符串。",
  },
  {
    target: "timeframe.change",
    signature: "timeframe.change(static_timeframe)",
    documentation: "v2.5 支持静态 timeframe 边界判断；同批支持 time_close。",
  },
  {
    target: "timeframe.in_seconds",
    signature: "timeframe.in_seconds(timeframe?)",
    documentation: "v2.7 支持静态 timeframe 秒数转换；无参数时使用当前 runtime interval。",
  },
  {
    target: "array.median",
    signature: "array.median(id) / id.median()",
    documentation: "v2.4 支持数值 array 中位数；同批支持 mode/range 聚合。",
  },
  {
    target: "order.ascending",
    signature: "order.ascending / order.descending",
    documentation: "v2.4 array.sort 和 array.sort_indices 的排序方向常量。",
  },
  {
    target: "map.new",
    signature: "map.new<key_type, value_type>()",
    documentation: "v2.4 可执行 map 核心；支持 get/put/remove/contains/size/clear/copy/keys/values。",
  },
  {
    target: "map.keys",
    signature: "map.keys(id) / id.keys()",
    documentation: "v2.4 返回 key array；顺序按 key 的稳定字符串序排序，保证回测可复现。",
  },
  {
    target: "map.values",
    signature: "map.values(id) / id.values()",
    documentation: "v2.4 返回 value array；顺序跟 map.keys 一致，按 key 的稳定字符串序排序。",
  },
  {
    target: "map iteration",
    signature: "for key in map.keys()",
    documentation: "v2.7 支持通过 keys()/values() 得到的确定性 array 做 for-in。",
  },
  {
    target: "matrix.new",
    signature: "matrix.new<T>(rows, columns, initial_value?)",
    documentation: "v2.3 可执行 matrix 核心；支持 get/set/rows/columns/fill/copy/reshape/add_row/add_col/remove_row/remove_col。",
  },
  {
    target: "type",
    signature: "type Name",
    documentation: "v2.6 支持纯 UDT constructor、字段默认值、命名 constructor 参数、局部和 var object 字段重赋值，以及 collection 字段引用；完整 Pine type/library 系统仍只进入诊断。",
  },
  {
    target: "method",
    signature: "method name(Type self, ...)",
    documentation: "v2.8 支持单表达式和受控多语句纯 method、默认值、命名参数与无副作用 method chain；表达式 method 可在受限 request.security pure expression 内调用。",
  },
  {
    target: "object history",
    signature: "box[n].field / box[n].method(args)",
    documentation: "v2.9 支持 object 历史字段读取和纯 method receiver，返回只读历史 snapshot 的字段值或 method 结果。",
  },
  {
    target: "varip",
    signature: "varip name = expression",
    documentation: "v3.0 PineTS worker 将 varip 按 var 语义执行，并通过 warning 标出 intrabar 语义边界。",
  },
  {
    target: "semantic declarations",
    signature: "signature / unsupportedReason",
    documentation: "v3.0 AnalyzeScript declarations 增补稳定 signature 与 unsupportedReason 字段；旧 reason 字段保留兼容。",
  },
  {
    target: "export",
    signature: "export function/type/method",
    documentation: "v2.8 export 会进入 semantic declarations，并标记 exportedKind=function/type/method；不加载外部 library。",
  },
  {
    target: "import",
    signature: "import user/library/version",
    documentation: "v2.0 语言底座：import 会进入 semantic declarations 与 alias 诊断；当前不会加载 TradingView library。",
  },
  {
    target: "library",
    signature: "library(title, ...)",
    documentation: "v2.0 语言底座：library(...) 会进入 semantic declarations；JFTrade 可运行脚本仍以 strategy(...) 为主入口。",
  },
  {
    target: "ta.vwap",
    signature: "ta.vwap(source?) / ta.vwap(source, timeframe.change(\"D\"|\"W\"|\"M\"))",
    documentation: "JFTrade 支持交易日 VWAP 和闭盘日/周/月锚定重置；source 省略时默认 hlc3。",
  },
  {
    target: "ta.bbw",
    signature: "ta.bbw(source, length, mult)",
    documentation: "PineTS worker 支持 Bollinger Band Width 与静态同标的 MTF 计算。",
  },
  {
    target: "ta.cog",
    signature: "ta.cog(source, length)",
    documentation: "PineTS worker 支持 Center of Gravity 与静态同标的 MTF 计算。",
  },
  {
    target: "ta.mfi",
    signature: "ta.mfi(source, length)",
    documentation: "JFTrade 支持基于 source 与 volume 的 Money Flow Index。",
  },
  {
    target: "ta.dmi",
    signature: "[plusDI, minusDI, adx] = ta.dmi(diLength, adxSmoothing)",
    documentation: "JFTrade 支持 DMI tuple assignment；字段包括 plus、minus、adx。",
  },
  {
    target: "ta.supertrend",
    signature: "[line, direction] = ta.supertrend(factor, atrPeriod)",
    documentation: "JFTrade 支持 Supertrend line/direction tuple assignment。",
  },
  {
    target: "ta.sar",
    signature: "ta.sar(start, increment, max)",
    documentation: "JFTrade 支持 Parabolic SAR，planner requirement key 形如 sar:0.02:0.02:0.2。",
  },
  {
    target: "ta.linreg",
    signature: "ta.linreg(source, length, offset)",
    documentation: "线性回归值；offset 必须是非负静态整数。",
  },
  {
    target: "ta.pivothigh",
    signature: "ta.pivothigh(source?, leftbars, rightbars)",
    documentation: "在 right bars 后确认 pivot high；确认前返回 na。",
  },
  {
    target: "ta.pivotlow",
    signature: "ta.pivotlow(source?, leftbars, rightbars)",
    documentation: "在 right bars 后确认 pivot low；确认前返回 na。",
  },
  {
    target: "ta.kc",
    signature: "[basis, upper, lower] = ta.kc(source, length, mult, useTrueRange?)",
    documentation: "JFTrade 支持 Keltner Channel tuple assignment 与字段读取。",
  },
  {
    target: "ta.kcw",
    signature: "ta.kcw(source, length, mult, useTrueRange?)",
    documentation: "返回归一化 Keltner Channel 宽度。",
  },
  {
    target: "ta.alma",
    signature: "ta.alma(source, length, offset, sigma)",
    documentation: "Arnaud Legoux Moving Average。",
  },
  {
    target: "ta.cmo",
    signature: "ta.cmo(source, length)",
    documentation: "Chande Momentum Oscillator；PineTS worker 支持 source-aware 计算。",
  },
  {
    target: "ta.tsi",
    signature: "ta.tsi(source, shortLength, longLength)",
    documentation: "True Strength Index；使用双 EMA 平滑 momentum 和绝对 momentum。",
  },
  {
    target: "ta.correlation",
    signature: "ta.correlation(source1, source2, length)",
    documentation: "滚动 Pearson 相关系数。",
  },
  {
    target: "ta.dev",
    signature: "ta.dev(source, length)",
    documentation: "滚动平均绝对偏差。",
  },
  {
    target: "ta.median",
    signature: "ta.median(source, length)",
    documentation: "滚动中位数。",
  },
  {
    target: "ta.percentile_linear_interpolation",
    signature: "ta.percentile_linear_interpolation(source, length, percentage)",
    documentation: "滚动百分位线性插值，percentage 必须为 0..100。",
  },
  {
    target: "ta.percentile_nearest_rank",
    signature: "ta.percentile_nearest_rank(source, length, percentage)",
    documentation: "滚动 nearest-rank 百分位，percentage 必须为 0..100。",
  },
  {
    target: "ta.percentrank",
    signature: "ta.percentrank(source, length)",
    documentation: "当前值在滚动窗口中的百分排名。",
  },
  {
    target: "ta.swma",
    signature: "ta.swma(source)",
    documentation: "4-bar symmetric weighted moving average。",
  },
  {
    target: "ta.barssince",
    signature: "ta.barssince(condition)",
    documentation: "首次触发前返回 na，当前 bar 触发返回 0。",
  },
  {
    target: "ta.valuewhen",
    signature: "ta.valuewhen(condition, sourceExpression, occurrence)",
    documentation: "occurrence 必须为非负整数；同一 bar 多次读取不会重复推进状态。",
  },
  {
    target: "timestamp",
    signature: "timestamp(year, month, day[, hour, minute])",
    documentation: "按当前标的交易所时区解释并返回 Unix milliseconds；第一版不支持显式 timezone 参数。",
  },
  {
    target: "input.time",
    signature: "input.time(defval, title?)",
    documentation: "JFTrade 只取默认时间值；常用 defval 可写 timestamp(year, month, day[, hour, minute])。",
  },
  {
    target: "input.timeframe",
    signature: "input.timeframe(defval, title?)",
    documentation: "JFTrade 只取默认 timeframe 字符串；支持 1/5/15/30/45/60/120/240/D/W/M 的 request.security 子集。",
  },
  {
    target: "input.color",
    signature: "input.color(defval, title?)",
    documentation: "JFTrade 只取默认颜色值；颜色主要用于兼容 Pine 模板，不参与交易数值语义。",
  },
  {
    target: "barstate.isconfirmed",
    signature: "barstate.isconfirmed",
    documentation: "PineTS worker 中当前已知 K 线执行时为 true；同批支持 isfirst/isnew/ishistory/isrealtime/islast。",
  },
  {
    target: "session.ismarket",
    signature: "session.ismarket",
    documentation: "当前 K 线属于 regular session 时为 true；同批支持 ispremarket/ispostmarket。",
  },
  {
    target: "dayofweek.monday",
    signature: "dayofweek.monday",
    documentation: "PineTS worker 将 dayofweek.sunday...saturday 归一为 1...7。",
  },
  {
    target: "month.january",
    signature: "month.january",
    documentation: "PineTS worker 将 month.january...december 归一为 1...12。",
  },
  {
    target: "color.rgb",
    signature: "color.rgb(r, g, b)",
    documentation: "PineTS worker normalizes 为稳定十六进制颜色字符串。",
  },
  {
    target: "color.new",
    signature: "color.new(color, transp)",
    documentation: "JFTrade 当前忽略 transp 并返回原颜色，用于兼容常见 Pine 模板。",
  },
  {
    target: "input.int",
    signature: "input.int(defval, title?)",
    documentation: "JFTrade 取默认值并作为常量执行，不提供 TradingView 设置面板运行时覆盖。",
  },
  {
    target: "input",
    signature: "input(defval, title?)",
    documentation: "JFTrade 取默认值并作为常量执行，不提供 TradingView 设置面板运行时覆盖。",
  },
  {
    target: "input.float",
    signature: "input.float(defval, title?)",
    documentation: "JFTrade 取默认浮点值；支持 defval= 命名参数。",
  },
  {
    target: "input.bool",
    signature: "input.bool(defval, title?)",
    documentation: "JFTrade 取默认 bool 值并作为常量执行。",
  },
  {
    target: "input.string",
    signature: "input.string(defval, title?)",
    documentation: "JFTrade 取默认字符串值并作为常量执行。",
  },
  {
    target: "input.source",
    signature: "input.source(defval, title?)",
    documentation: "PineTS worker 取默认 OHLCV source；后续 ta.sma(src, n) 按 source-aware MA 计算。",
  },
  {
    target: "math.abs",
    signature: "math.abs(number)",
    documentation: "PineTS worker normalizes 到 abs(number)。",
  },
  {
    target: "math.min",
    signature: "math.min(a, b, ...)",
    documentation: "PineTS worker normalizes 到 min(a, b, ...)。",
  },
  {
    target: "math.max",
    signature: "math.max(a, b, ...)",
    documentation: "PineTS worker normalizes 到 max(a, b, ...)。",
  },
  {
    target: "math.avg",
    signature: "math.avg(a, b, ...)",
    documentation: "PineTS worker normalizes 到 avg(a, b, ...)。",
  },
  {
    target: "math.round",
    signature: "math.round(number, precision?)",
    documentation: "PineTS worker normalizes 到 round(number, precision?)。",
  },
  {
    target: "math.round_to_mintick",
    signature: "math.round_to_mintick(number)",
    documentation: "按当前市场 tick size 四舍五入，缺省 tick 为 0.01。",
  },
  {
    target: "math.floor",
    signature: "math.floor(number)",
    documentation: "PineTS worker normalizes 到 floor(number)。",
  },
  {
    target: "math.ceil",
    signature: "math.ceil(number)",
    documentation: "PineTS worker normalizes 到 ceil(number)。",
  },
  {
    target: "math.sqrt",
    signature: "math.sqrt(number)",
    documentation: "PineTS worker normalizes 到 sqrt(number)。",
  },
  {
    target: "math.pow",
    signature: "math.pow(base, exponent)",
    documentation: "PineTS worker normalizes 到 pow(base, exponent)。",
  },
  {
    target: "math.log",
    signature: "math.log(number)",
    documentation: "PineTS worker normalizes 到 log(number)。",
  },
  {
    target: "math.sign",
    signature: "math.sign(number)",
    documentation: "PineTS worker normalizes 到 sign(number)。",
  },
  {
    target: "bar_index",
    signature: "bar_index",
    documentation: "当前策略收到的 K 线序号，从 0 开始。",
  },
  {
    target: "time",
    signature: "time",
    documentation: "当前 K 线时间，Unix milliseconds；同时支持 hour/minute/dayofweek/dayofmonth/month/year。",
  },
  {
    target: "strategy.entry",
    signature: "strategy.entry(id, direction, qty?)",
    documentation: "显式 qty/qty_percent 优先；未写 qty 时继承 strategy(...) 的 default_qty_type/default_qty_value。",
  },
  {
    target: "strategy.order",
    signature: "strategy.order(id, direction, qty?, qty_percent?, stop?, limit?)",
    documentation: "JFTrade 将其作为净额订单执行，不套用 strategy.entry 的 pyramiding gate；支持 stop、limit 和 stop-limit，OCA 暂不支持。",
  },
  {
    target: "strategy.close",
    signature: "strategy.close(id, qty?, qty_percent?, immediately?, comment?, alert_message?, disable_alert?)",
    documentation: "映射为 JFTrade 平仓；支持立即平仓和订单日志/通知元数据。",
  },
  {
    target: "strategy.close_all",
    signature: "strategy.close_all(immediately?, comment?, alert_message?, disable_alert?)",
    documentation: "按当前实际持仓方向 flatten 当前策略 symbol；支持 immediately=true。",
  },
  {
    target: "var",
    signature: "var name = expression",
    documentation: "声明跨 K 线保留的变量；当前 JFTrade runtime 会保存当前值和上一值。",
  },
  {
    target: "nz",
    signature: "nz(value, fallback?)",
    documentation: "value 为 na 时返回 fallback；未传 fallback 时返回 0。",
  },
  {
    target: "na",
    signature: "na",
    documentation: "空值常量，可用于比较或配合 nz。",
  },
  {
    target: "request.security",
    signature: "request.security(syminfo.tickerid, timeframe, source | source[n] | ta.* | [expr, expr] | pure object/collection expr)",
    documentation: "PineTS worker 支持同标的 1/5/15/30/45/60/120/240/D/W/M，source/source[n]、source-aware 均线、v2.4 ta.stoch、纯表达式、2-8 元 tuple，以及纯 collection/object 表达式；lookahead_on/gaps_on、多标的和副作用表达式会被明确诊断。",
  },
  {
    target: "strategy.exit",
    signature: "strategy.exit(id, from_entry, stop/limit | trail_points|trail_price + trail_offset, qty?, qty_percent?)",
    documentation: "支持基础止损、止盈、stop+limit bracket、按 tick 解释的追踪止损和部分退出；OCA、partial fill 和 intrabar broker emulator 语义不会静默执行。",
  },
  {
    target: "strategy.cancel",
    signature: "strategy.cancel(id)",
    documentation: "取消当前策略 symbol 中指定 id 的未触发 pending order；不存在的 id 会跳过。",
  },
  {
    target: "strategy.cancel_all",
    signature: "strategy.cancel_all()",
    documentation: "取消当前策略 symbol 的全部未触发 pending orders。",
  },
];
